const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
const {PGlite}=require('@electric-sql/pglite');
(async()=>{const db=new PGlite();try{
 const admin='10000000-0000-0000-0000-000000000001',member='10000000-0000-0000-0000-000000000002';
 await db.exec(`CREATE ROLE anon;CREATE ROLE authenticated;CREATE SCHEMA auth;CREATE SCHEMA ojjuda_house_admin;CREATE SCHEMA ojjuda_note;CREATE SCHEMA ojjuda_note_internal;CREATE SCHEMA ojjuda_photo_internal;
 GRANT USAGE ON SCHEMA auth,public,ojjuda_house_admin,ojjuda_note TO authenticated;
 CREATE FUNCTION auth.uid() RETURNS uuid LANGUAGE sql STABLE AS $$SELECT nullif(current_setting('request.jwt.claim.sub',true),'')::uuid$$;
 CREATE FUNCTION public.is_admin() RETURNS boolean LANGUAGE sql STABLE AS $$SELECT auth.uid()='${admin}'::uuid$$;
 CREATE FUNCTION public.photo_is_admin() RETURNS boolean LANGUAGE sql STABLE AS $$SELECT public.is_admin()$$;
 CREATE FUNCTION ojjuda_photo_internal.member_allowed() RETURNS boolean LANGUAGE sql STABLE AS $$SELECT coalesce(current_setting('test.adult',true),'yes')<>'no'$$;
 CREATE FUNCTION ojjuda_note_internal.is_note_moderator() RETURNS boolean LANGUAGE sql STABLE AS $$SELECT public.is_admin()$$;
 CREATE FUNCTION public.risk_pattern() RETURNS text LANGUAGE sql AS $$SELECT '협박'$$;
 CREATE TABLE public.profiles(id uuid PRIMARY KEY,nickname text,bio text,mood_text text,updated_at timestamptz DEFAULT now(),door_closed bool DEFAULT false,profile_photo_path text);
 INSERT INTO public.profiles(id,nickname) VALUES('${admin}','관리자'),('${member}','작성자');
 CREATE TABLE ojjuda_house_admin.active_content(kind text,id text,author_id uuid,author_nick text,owner_id uuid,body text,created_at timestamptz,is_private bool,revision text,folder_name text);
 CREATE TABLE ojjuda_note.cards(id uuid PRIMARY KEY,kind text,author_id uuid,body text,created_at timestamptz,tags text[],parent_id uuid,archived_at timestamptz);
 CREATE TABLE ojjuda_note_internal.card_moderation(card_id uuid PRIMARY KEY,hidden bool);
 CREATE TABLE ojjuda_note_internal.card_photos(card_id uuid,photo_path text);
 CREATE TABLE ojjuda_note_internal.event_ads(card_id uuid,photo_path text);
 CREATE TABLE public.diaries(id text,user_id uuid,title text,body text,created_at timestamptz,visibility text);
 CREATE TABLE public.media(id text,type text,user_id uuid,caption text,created_at timestamptz,visibility text,folder_id uuid,thumb_path text,path text);
 CREATE TABLE public.media_folders(id uuid,visibility text);
 CREATE TABLE public.guestbook(id text,author_id uuid,author_nick text,owner_id uuid,body text,reply text,created_at timestamptz,secret bool,hidden bool);
 CREATE TABLE public.intros(owner_id uuid,author_id uuid,author_nick text,body text,created_at timestamptz);
 CREATE TABLE public.place_messages(id bigint,author_id uuid,author_nick text,room text,body text,created_at timestamptz);
 CREATE TABLE public.photo_stages(id uuid PRIMARY KEY,owner uuid,nick text,created_at timestamptz,visibility text,status text,image_path text,full_path text,report_count int);
 CREATE TABLE public.reports(id bigint,kind text,target_id text,target_user uuid,content text,reason text,detail text,status text,created_at timestamptz);
 CREATE TABLE ojjuda_note_internal.reports(report_id uuid,card_id uuid,reason text,status text,created_at timestamptz);
 CREATE TABLE public.audit(action text,kind text);
 CREATE FUNCTION public.admin_note(text,uuid,text,jsonb) RETURNS void LANGUAGE sql AS $$INSERT INTO public.audit VALUES($1,$4->>'kind')$$;
 CREATE FUNCTION public.photo_set_status(uuid,text) RETURNS void LANGUAGE sql AS $$UPDATE public.photo_stages SET status=$2 WHERE id=$1$$;
 CREATE FUNCTION public.admin_set_report(bigint,text) RETURNS void LANGUAGE sql AS $$UPDATE public.reports SET status=$2 WHERE id=$1$$;
 CREATE FUNCTION ojjuda_note.resolve_report(uuid) RETURNS void LANGUAGE sql AS $$UPDATE ojjuda_note_internal.reports SET status='resolved' WHERE report_id=$1$$;
 CREATE FUNCTION ojjuda_note.moderate_card(uuid,bool,text) RETURNS void LANGUAGE sql AS $$INSERT INTO ojjuda_note_internal.card_moderation VALUES($1,$2) ON CONFLICT(card_id) DO UPDATE SET hidden=excluded.hidden$$;
 INSERT INTO ojjuda_note.cards SELECT ('20000000-0000-0000-0000-'||lpad(i::text,12,'0'))::uuid,'memo','${member}',repeat('긴 글 내용 ',400),'2026-10-01'::timestamptz,ARRAY['일상'],NULL,NULL FROM generate_series(1,40) i;
 INSERT INTO public.photo_stages VALUES('30000000-0000-0000-0000-000000000001','${member}','작성자','2026-01-01','public','pending','thumb.jpg','full.jpg',0);
 INSERT INTO public.place_messages VALUES(1,'${member}','작성자','park-1','협박이 의심되는 문장','2026-10-02');
 INSERT INTO public.reports VALUES(1,'chat','1','${member}','신고된 내용','abuse','상세 신고','open','2026-01-02');
 INSERT INTO ojjuda_note_internal.reports VALUES('40000000-0000-0000-0000-000000000001','20000000-0000-0000-0000-000000000001','spam','open','2026-01-03');`);
 const root=path.resolve(__dirname,'..'),migrations=fs.readdirSync(path.join(root,'supabase/migrations'));
 const migration=migrations.find(x=>x.endsWith('_admin_review_inbox.sql'));
 await db.exec(fs.readFileSync(migration?path.join(root,'supabase/migrations',migration):path.join(root,'admin/review-inbox.sql'),'utf8'));
 const actor=async id=>db.exec(`SET ROLE authenticated;SET request.jwt.claim.sub='${id||''}'`);
 const feed=async(cursor=null,kind='all',state='all')=>(await db.query('SELECT public.admin_review_feed($1,$2,$3,$4,NULL,30) result',[kind,state,'',cursor])).rows[0].result;
 const act=async row=>(await db.query("SELECT public.admin_review_action($1,$2,'reviewed','') result",[row.key,row.revision])).rows[0].result;
 await actor(member);await assert.rejects(feed(),/not_admin/);await assert.rejects(db.query("SELECT public.admin_review_detail('chat:1')"),/not_admin/);
 await actor(null);await assert.rejects(feed(),/not_admin/);await actor(admin);
 await assert.rejects(db.query('SELECT * FROM ojjuda_house_admin.review_sources'));
 const first=await feed();assert.equal(first.counts.pending,1);assert.equal(first.counts.reports,2);assert.equal(first.counts.risk,1);
 assert.deepEqual(first.items.slice(0,4).map(x=>x.priority),[0,0,1,2],'old pending photos and reports rank above newer ordinary content');
 const second=await feed(first.next_cursor);assert.equal(new Set([...first.items,...second.items].map(x=>x.key)).size,44);assert.equal(second.has_more,false);
 const card=first.items.find(x=>x.kind==='card');assert.equal(card.body.length,500);assert.equal(card.body_truncated,true);
 const detail=(await db.query('SELECT public.admin_review_detail($1) result',[card.key])).rows[0].result;assert.equal(detail.body.length,2800);
 const risk=(await feed(null,'all','risk')).items[0];assert((await act(risk)).ok);assert.equal((await feed()).counts.risk,0);
 await db.exec('RESET ROLE');await db.exec("UPDATE public.place_messages SET body='협박 내용이 변경됨' WHERE id=1");await actor(admin);assert.equal((await feed()).counts.risk,1,'editing reviewed text reopens review');
 const photo=(await feed(null,'game_photo','pending')).items[0];assert((await db.query("SELECT public.admin_review_action($1,$2,'approved','') result",[photo.key,photo.revision])).rows[0].result.ok);assert.equal((await feed()).counts.pending,0);
 assert.equal((await db.query("SELECT public.admin_review_action($1,$2,'rejected','') result",[photo.key,photo.revision])).rows[0].result.reason,'conflict');
 const report=(await feed(null,'world_report','reports')).items[0];assert((await act(report)).ok);assert.equal((await feed()).counts.reports,1);
 await db.exec("SET test.adult='no'");assert.equal((await feed(null,'game_photo')).items.length,0,'existing adult gate remains enforced');
 await db.exec('RESET ROLE');assert.equal((await db.query('SELECT count(*)::int n FROM public.audit')).rows[0].n,3);
 console.log('PASS: administrator-only unified feed/detail/actions, old approval priority, reports, keyset pagination, full long text, stale decisions, review reopening and adult gate.');
}finally{await db.close();}})().catch(e=>{console.error(e);process.exitCode=1});
