const assert=require('node:assert/strict');
const {randomUUID}=require('node:crypto');
const {fixture,A,B,C,MINOR}=require('./arcade-rooms-fixture.cjs');
(async()=>{
  const f=await fixture(),{db,arcade,call}=f;
  const create=(actor,kind,title='같이 한 판',options={})=>arcade(actor,'create',{p_kind:kind,p_title:title,p_options:{request_id:randomUUID(),...options}});
  const join=(actor,room,options={})=>arcade(actor,'join',{p_room:room.room_no,p_options:options});
  const cancel=(actor,room)=>arcade(actor,'cancel',{p_room:room.room_no});
  const expireRate=()=>db.exec("update ojjuda_arcade_internal.rooms set created_at=created_at-interval '2 minutes'");
  try{
    // A private room lookup must not widen the public privacy helper's scope.
    await assert.rejects(()=>db.transaction(async tx=>{
      await tx.query("select set_config('request.jwt.claim.sub',$1,true)",[B]);
      await tx.exec('set local role authenticated');
      await tx.query('select public.is_banned($1)',[A]);
    }),/helper_scope_denied/);
    await assert.rejects(()=>arcade(null,'list'),/not_signed_in/);
    await db.query('update auth.users set is_anonymous=true where id=$1',[C]);
    await assert.rejects(()=>arcade(C,'list'),/not_signed_in/);
    await db.query('update auth.users set is_anonymous=false where id=$1',[C]);
    for(const title of ['', '   ','가'.repeat(41)])await assert.rejects(()=>create(A,'chess',title),/invalid_title/);
    await assert.rejects(()=>create(A,'other'),/bad_kind/);
    await assert.rejects(()=>create(MINOR,'matgo'),/adult_required/);
    let previous=1000;
    for(const kind of ['chess','janggi','carom4','carom3','pool8']){
      const request=randomUUID(),params={request_id:request,layout:'ehhe'};
      const {room}=await create(A,kind,'  초보  환영 <b> & "  ',params);
      assert.ok(room.room_no>previous);previous=room.room_no;
      assert.equal(room.title,'초보 환영 <b> & "');assert.equal(room.match_id,null);assert.equal(room.players,1);
      assert.equal((await create(A,kind,room.title,params)).room.room_no,room.room_no,'retry creates no duplicate');
      await assert.rejects(()=>create(A,kind,'different',params),/invalid_request/);
      await assert.rejects(()=>create(A,'chess'),/room_in_progress/);
      const list=await arcade(B,'list');assert.equal(list.rooms[0].room_no,room.room_no);assert.equal(list.rooms[0].match_id,null);
      await assert.rejects(()=>cancel(B,room),/not_room_owner/);
      const joined=(await join(B,room,{layout:'heeh'})).room;
      assert.equal(joined.status,'playing');assert.equal(joined.players,2);
      const record=(await db.query('select * from public.board_games where id=$1',[joined.match_id])).rows[0];
      assert.equal(record.kind,kind);assert.equal(record.p1,A);assert.equal(record.p2,B);assert.equal(record.status,'playing');
      assert.deepEqual(record.janggi_layout,{c:'ehhe',h:'heeh'});
      assert.equal((await join(B,room)).room.match_id,record.id,'joining again resumes same game');
      assert.equal((await arcade(A,'list')).mine.match_id,record.id,'host discovers exact same game');
      assert.equal((await arcade(C,'list')).rooms[0].match_id,null,'spectators receive no game identifier');
      await assert.rejects(()=>join(C,room),/room_full/);
      await assert.rejects(()=>cancel(A,room),/room_already_started/);
      await db.query("update public.board_games set status='done' where id=$1",[record.id]);
      assert.equal((await arcade(A,'list')).mine,null);await expireRate();
    }
    const racing=(await create(A,'chess')).room;
    const race=await Promise.allSettled([join(B,racing),join(C,racing)]);
    assert.equal(race.filter(r=>r.status==='fulfilled').length,1);assert.match(race.find(r=>r.status==='rejected').reason.message,/room_full/);
    assert.equal((await db.query('select count(*)::int n from public.board_games where status=\'playing\'')).rows[0].n,1);
    await db.exec("update public.board_games set status='done'");
    const blocked=(await create(A,'pool8')).room;
    await db.query('insert into public.blocks values($1,$2)',[A,B]);
    assert.equal((await arcade(B,'list')).rooms.length,0);await assert.rejects(()=>join(B,blocked),/room_unavailable/);
    await db.exec('delete from public.blocks');await db.query("update public.user_private set banned_until=now()+interval '1 hour' where user_id=$1",[A]);
    assert.equal((await arcade(B,'list')).rooms.length,0);await assert.rejects(()=>join(B,blocked),/room_unavailable/);
    await assert.rejects(()=>arcade(A,'list'),/banned/);await db.query('update public.user_private set banned_until=null where user_id=$1',[A]);
    await cancel(A,blocked);await assert.rejects(()=>join(B,blocked),/room_unavailable/);
    const expired=(await create(A,'chess')).room;
    await db.query("update ojjuda_arcade_internal.rooms set expires_at=now()-interval '1 second' where room_no=$1",[expired.room_no]);
    assert.equal((await arcade(B,'list')).rooms.length,0);await assert.rejects(()=>join(B,expired),/room_unavailable/);
    await expireRate();
    const publicMatgo=(await create(A,'matgo','회원 맞고방')).room;
    assert.ok(publicMatgo.match_id);assert.equal((await arcade(MINOR,'list')).rooms.length,0);
    await assert.rejects(()=>join(MINOR,publicMatgo),/adult_required/);
    const publicJSON=JSON.stringify(await arcade(B,'list'));assert.ok(!publicJSON.includes('seed'));assert.ok(!publicJSON.includes('match_code'));assert.ok(!publicJSON.includes(publicMatgo.match_id));
    const matched=(await join(B,publicMatgo)).room;assert.equal(matched.match_id,publicMatgo.match_id);
    const one=await call(A,{action:'online_read',room_id:matched.match_id}),two=await call(B,{action:'online_read',room_id:matched.match_id});
    assert.equal(one.status,200);assert.equal(two.status,200);assert.equal(one.room.id,two.room.id);assert.notEqual(one.room.seat,two.room.seat);
    assert.ok(!JSON.stringify(one).includes('seed'));assert.equal(one.room.status,'active');
    await assert.rejects(()=>join(C,publicMatgo),/room_full/);
    await call(A,{action:'online_leave',room_id:matched.match_id});
    assert.equal((await arcade(C,'list')).rooms.length,0,'departed game leaves public listing');
    await call(B,{action:'online_leave',room_id:matched.match_id});await expireRate();
    const cancelled=(await create(A,'matgo')).room;await cancel(A,cancelled);
    assert.equal((await arcade(B,'list')).rooms.length,0);
    const native=await call(A,{action:'online_create'});assert.equal(native.status,200);
    await assert.rejects(()=>create(A,'matgo'),/match_in_progress/);
    await call(A,{action:'online_leave',room_id:native.room.id});await expireRate();
    for(let i=0;i<5;i++)await cancel(A,(await create(A,'chess')).room);
    await assert.rejects(()=>create(A,'chess'),/room_rate_limit/);
    await assert.rejects(()=>db.transaction(async tx=>{await tx.exec('set local role authenticated');await tx.query('select * from ojjuda_arcade_internal.rooms');}),/permission denied/);
    await assert.rejects(()=>db.transaction(async tx=>{await tx.exec('set local role authenticated');await tx.query('select ojjuda_arcade_internal.sync_rooms()');}),/permission denied/);
    await assert.rejects(()=>db.transaction(async tx=>{await tx.exec('set local role authenticated');await tx.query("select ojjuda_matgo_internal.wallet_service_v1($1,'status')",[A]);}),/permission denied/);
    assert.equal((await db.query("select has_function_privilege('authenticated','ojjuda_matgo_internal.wallet_service_v1(uuid,text,uuid,boolean,uuid,bigint,smallint,integer)','execute') allowed")).rows[0].allowed,false);
    await assert.rejects(()=>db.transaction(async tx=>{await tx.exec('set local role anon');await tx.query("select public.arcade_room_service('list')");}),/permission denied/);
    console.log('PASS: all 6 room kinds, real Matgo seats, number/title, retry, one winner on concurrent joins, capacity, expiry, cancellation, age, blocks, bans, secrets, rate limit and SQL privileges.');
  }finally{await f.close();}
})().catch(error=>{console.error(error);process.exitCode=1;});
