const assert=require('node:assert/strict'),fs=require('fs'),path=require('path');const {chromium}=require('playwright');
(async()=>{const browser=await chromium.launch({headless:true,executablePath:process.env.PLAYWRIGHT_CHROMIUM_EXECUTABLE_PATH||undefined,args:['--no-sandbox']});try{const page=await browser.newPage({viewport:{width:390,height:844}});const errors=[];page.on('pageerror',e=>errors.push(e.message));const root=path.join(__dirname,'..');
await page.route('https://test.local/**',async route=>{const p=new URL(route.request().url()).pathname;const file=p==='/comics/'?'comics/index.html':p.slice(1);if(fs.existsSync(path.join(root,file)))return route.fulfill({body:fs.readFileSync(path.join(root,file)),contentType:p.endsWith('.js')?'text/javascript':p.endsWith('.css')?'text/css':'text/html'});return route.fulfill({status:404,body:''})});
await page.route('https://cdn.jsdelivr.net/**',route=>route.fulfill({contentType:'text/javascript',body:`window.allowed=true;window.admin=true;window.calls=[];window.books=[];window.pages=[];window.uploadNames=[];window.authHandler=null;window.supabase={createClient(){return {
auth:{getUser:async()=>({data:{user:{id:'00000000-0000-4000-8000-000000000001'}}}),onAuthStateChange(fn){authHandler=fn}},rpc:async(name)=>({data:{allowed:window.allowed,admin:window.admin}}),
from(table){let action='select',value,filters=[],one=false;const q={select(){return q},eq(k,v){filters.push([k,v]);return q},order(){return q},single(){one=true;return q},insert(v){action='insert';value=v;return q},update(v){action='update';value=v;return q},delete(){action='delete';return q},then(done){calls.push({table,action,value});let list=table==='creative_comics'?books:pages;let found=list.filter(x=>filters.every(([k,v])=>x[k]===v));if(action==='insert'){const x={id:crypto.randomUUID(),published:false,...value};list.push(x);found=[x]}if(action==='update')found.forEach(x=>Object.assign(x,value));if(action==='delete'){for(const x of found)list.splice(list.indexOf(x),1)}return Promise.resolve({data:one?found[0]:found}).then(done)}};return q},
storage:{from(){return{upload:async(p,f)=>{uploadNames.push(f.name);return{data:{path:p}}},remove:async()=>({data:[]}),download:async(p)=>{calls.push({download:p});const c=document.createElement('canvas');c.width=80;c.height=120;c.getContext('2d').fillRect(0,0,80,120);return {data:await new Promise(r=>c.toBlob(r))}}}}
}}}};` }));
await page.goto('https://test.local/comics/');await page.getByRole('button',{name:'＋ 만화 올리기'}).click();await page.locator('#title').fill('창작 만화 테스트');
await page.evaluate(async()=>{const canvas=document.createElement('canvas');canvas.width=80;canvas.height=120;const blob=await new Promise(r=>canvas.toBlob(r));const dt=new DataTransfer();for(const name of ['41-1.png','40-1.png','41.png','40.png'])dt.items.add(new File([blob],name,{type:'image/png'}));const input=document.querySelector('#fileInput');input.files=dt.files;input.dispatchEvent(new Event('change',{bubbles:true}))});
assert.deepEqual(await page.locator('#fileList span').allTextContents(),['40.png','40-1.png','41.png','41-1.png']);await page.getByRole('button',{name:'업로드 후 공개'}).click();await page.waitForFunction(()=>document.querySelector('#shelf').hidden===false&&books.length===1&&books[0].published===true);
assert.deepEqual(await page.evaluate(()=>uploadNames),['40.png','40-1.png','41.png','41-1.png']);await page.getByRole('button',{name:'읽기',exact:true}).click();await page.waitForFunction(()=>document.querySelector('.sheet img')?.src.startsWith('blob:'));assert.equal(await page.locator('.sheet img').getAttribute('alt'),'40.png');await page.getByRole('button',{name:'다음',exact:true}).click();await page.waitForFunction(()=>document.querySelector('.sheet img')?.getAttribute('alt')==='40-1.png');
await page.selectOption('#viewMode','spread');assert.equal(await page.locator('.sheet').count(),2);await page.getByRole('button',{name:'확대',exact:true}).click();assert.equal(await page.locator('#zoomValue').textContent(),'125%');await page.selectOption('#viewMode','scroll');assert.equal(await page.locator('.sheet').count(),4);assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false,'mobile no document overflow');
await page.evaluate(()=>{window.allowed=false;window.admin=false;window.authHandler('SIGNED_OUT',null)});await page.waitForFunction(()=>!document.querySelector('#gate').hidden&&document.querySelector('#gateMessage').textContent.includes('만 19세'));assert.equal(await page.locator('.sheet img').count(),0,'logout clears images');assert.equal(await page.locator('#uploadOpen').isVisible(),false);
const downloadsBefore=await page.evaluate(()=>calls.filter(x=>x.download).length);await page.locator('#retry').click();await page.waitForTimeout(100);assert.equal(await page.evaluate(()=>calls.filter(x=>x.download).length),downloadsBefore,'denied member never downloads');
assert.deepEqual(errors,[]);console.log('Creative comics UI: sorted upload, publication, reading, modes, zoom, mobile layout, logout and age gate passed');
}finally{await browser.close()}})().catch(e=>{console.error(e);process.exitCode=1});
