const assert=require('node:assert/strict'),fs=require('fs'),path=require('path');const {JSDOM}=require('jsdom');
const root=path.join(__dirname,'..');const wait=()=>new Promise(r=>setTimeout(r,10));
async function until(fn){for(let i=0;i<150;i++){if(fn())return;await wait()}throw Error('condition timed out')}
function setup(allowed=true,admin=true){
const dom=new JSDOM(fs.readFileSync(path.join(root,'comics/index.html'),'utf8'),{url:'https://test.local/comics/',runScripts:'outside-only'}),w=dom.window;
w.URL.createObjectURL=()=> 'blob:https://test.local/'+Math.random();w.URL.revokeObjectURL=()=>{};w.Image=class{naturalWidth=80;naturalHeight=120;decode(){return Promise.resolve()}};w.ResizeObserver=class{observe(){}};w.IntersectionObserver=class{constructor(fn){this.fn=fn}observe(target){this.fn([{isIntersecting:true,target}])}disconnect(){}};w.HTMLElement.prototype.scrollTo=function(){};w.HTMLElement.prototype.scrollIntoView=function(){};w.confirm=()=>true;
let state={allowed,admin,books:[],pages:[],downloads:0,uploads:[],handler:null};w.OJJUDA_CONFIG={supabaseUrl:'https://test.local',supabaseKey:'test'};
w.supabase={createClient(){return{auth:{getUser:async()=>({data:{user:{id:'00000000-0000-4000-8000-000000000001'}}}),onAuthStateChange(fn){state.handler=fn}},rpc:async()=>({data:{allowed:state.allowed,admin:state.admin}}),from(table){let action='select',value,filters=[],one=false;const q={select(){return q},eq(k,v){filters.push([k,v]);return q},order(){return q},single(){one=true;return q},insert(v){action='insert';value=v;return q},update(v){action='update';value=v;return q},delete(){action='delete';return q},then(done){const list=table==='creative_comics'?state.books:state.pages;let rows=list.filter(x=>filters.every(([k,v])=>x[k]===v));if(action==='insert'){const x={id:w.crypto.randomUUID(),published:false,...value};list.push(x);rows=[x]}if(action==='update')rows.forEach(x=>Object.assign(x,value));if(action==='delete')for(const x of rows)list.splice(list.indexOf(x),1);return Promise.resolve({data:one?rows[0]:rows}).then(done)}};return q},storage:{from(){return{upload:async(p,f)=>{state.uploads.push(f.name);return{data:{path:p}}},remove:async()=>({data:[]}),download:async()=>{state.downloads++;if(state.failDownloadOnce){state.failDownloadOnce=false;return{error:new Error('temporary download failure')}}return{data:new Blob(['fixture'])}}}}}}}};w.eval(fs.readFileSync(path.join(root,'comics/app.js'),'utf8'));return {dom,w,state,$:id=>w.document.getElementById(id)}}
(async()=>{const x=setup(),{dom,w,state,$}=x;try{await until(()=>!$('shelf').hidden);$('uploadOpen').click();$('title').value='테스트';const files=['41-1.png','40-1.png','41.png','40.png'].map(name=>({name,size:8,slice(){return{arrayBuffer:async()=>Uint8Array.from([137,80,78,71,13,10,26,10]).buffer}}}));Object.defineProperty($('fileInput'),'files',{value:files});$('fileInput').dispatchEvent(new w.Event('change'));
assert.deepEqual([...w.document.querySelectorAll('#fileList span')].map(n=>n.textContent),['40.png','40-1.png','41.png','41-1.png']);
$('uploadForm').dispatchEvent(new w.Event('submit',{cancelable:true}));await until(()=>state.books[0]?.published&&!$('shelf').hidden);assert.deepEqual(state.uploads,['40.png','40-1.png','41.png','41-1.png']);
state.failDownloadOnce=true;
[...w.document.querySelectorAll('.book button')].find(b=>b.textContent==='읽기').click();await until(()=>!$('reader').hidden&&state.downloads>0);await until(()=>w.document.querySelector('.sheet .loading button'));w.document.querySelector('.sheet .loading button').click();await until(()=>state.downloads>=2&&w.document.querySelector('.sheet img').getAttribute('src'));assert.equal(w.document.querySelector('.sheet img').alt,'40.png');await until(()=>state.downloads===4);const warmed=state.downloads;$('next').click();await until(()=>w.document.querySelector('.sheet img')?.alt==='40-1.png'&&w.document.querySelector('.sheet img').getAttribute('src'));assert.ok(state.downloads<=warmed+1,'turn uses prefetched page and fetches only the next lookahead');$('prev').click();await until(()=>w.document.querySelector('.sheet img')?.alt==='40.png'&&w.document.querySelector('.sheet img').getAttribute('src'));assert.equal(state.downloads,warmed+1,'back uses cached original');$('next').click();$('viewMode').value='spread';$('viewMode').dispatchEvent(new w.Event('change'));assert.equal(w.document.querySelectorAll('.sheet').length,2);$('zoomIn').click();assert.equal($('zoomValue').textContent,'125%');$('viewMode').value='scroll';$('viewMode').dispatchEvent(new w.Event('change'));assert.equal(w.document.querySelectorAll('.sheet').length,4);
state.allowed=false;state.admin=false;state.handler('SIGNED_OUT',null);await until(()=>$('gateMessage').textContent.includes('만 19세 이상 회원만 볼'));assert.equal(w.document.querySelectorAll('.sheet').length,0);assert.equal($('uploadOpen').hidden,true);const count=state.downloads;$('retry').click();await until(()=>$('gateMessage').textContent.includes('만 19세 이상 회원만 볼'));assert.equal(state.downloads,count);
console.log('Comics DOM: upload order/publication, reader modes/zoom, logout cleanup and denied member downloads passed');
}finally{dom.window.close()}
for(const admin of [false,true]){const y=setup(false,admin);try{await until(()=>y.$('gateMessage').textContent.includes('만 19세 이상 회원만 볼'));assert.equal(y.$('uploadOpen').hidden,true);assert.equal(y.state.downloads,0)}finally{y.dom.window.close()}}
})().catch(e=>{console.error(e);process.exitCode=1});
