const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),{chromium}=require('playwright');
const root=path.resolve(__dirname,'..');
const fixture=`window.owner='10000000-0000-0000-0000-000000000001';window.fail=false;window.lost=false;
window.client={from(table){let uid;let start=0,end=499;const q={select(){return q},eq(k,v){if(k==='user_id')uid=v;return q},order(){return q},range(a,b){start=a;end=b;return q},async maybeSingle(){if(fail)return {error:{message:'offline'}};return {data:JSON.parse(localStorage.getItem('cloud:'+uid)||'null')}},then(resolve,reject){return Promise.resolve({data:JSON.parse(localStorage.getItem('legacy:'+uid)||'[]').slice(start,end+1),error:null}).then(resolve,reject)}};return q},async rpc(name,args){if(fail)return {error:{message:'offline'}};const old=JSON.parse(localStorage.getItem('cloud:'+owner)||'null');if((old?.revision||null)!==args.p_expected)return {error:{code:'40001'}};localStorage.setItem('cloud:'+owner,JSON.stringify({revision:args.p_revision,payload:args.p_payload}));if(lost){lost=false;return {error:{message:'timeout'}}}return {data:args.p_revision}}};`;
const html=`<!doctype html><html><meta charset="utf-8"><meta name="viewport" content="width=device-width"><link rel="stylesheet" href="/world-life.css"><main data-life-root><details open class="life-tool"><summary>가계부</summary><div id="ledger" class="life-tool-body"></div></details></main><script>${fixture}</script><script src="/world-donflow.js"></script><script>window.show=()=>{window.dispose?.();document.querySelector('#ledger').replaceChildren();const captured=owner;window.dispose=OjjudaDonflow.mount(document.querySelector('#ledger'),{owner,client,authorized:()=>owner===captured});};show();</script>`;
(async()=>{const browser=await chromium.launch({headless:true,executablePath:process.env.PLAYWRIGHT_CHROMIUM_EXECUTABLE_PATH||undefined,args:['--no-sandbox']});try{
 const context=await browser.newContext({viewport:{width:390,height:844},timezoneId:'Asia/Seoul'});await context.route('https://donflow.test/**',r=>{const u=new URL(r.request().url());if(u.pathname==='/')return r.fulfill({contentType:'text/html',body:html});if(u.pathname==='/proof.ttf')return r.fulfill({path:'/tmp/ojjuda-visitor-proof.ttf'});const p=path.join(root,u.pathname);if(!fs.existsSync(p))return r.fulfill({status:404,body:'missing'});const type=p.endsWith('.js')?'text/javascript':p.endsWith('.css')?'text/css':'text/html';return r.fulfill({contentType:type,body:fs.readFileSync(p)})});
 if(fs.existsSync('/tmp/ojjuda-visitor-proof.ttf'))await context.addInitScript(()=>document.addEventListener('DOMContentLoaded',()=>{const s=document.createElement('style');s.textContent='@font-face{font-family:Proof;src:url(/proof.ttf)}html,body,button,input,textarea,select{font-family:Proof,sans-serif!important}';document.head.append(s)}));
 const page=await context.newPage(),errors=[];page.on('pageerror',e=>errors.push(e.message));page.on('dialog',d=>d.accept());await page.goto('https://donflow.test/');let f=page.frameLocator('iframe');
 await f.getByText('수입·지출 기록 ＋',{exact:true}).click();await f.getByRole('heading',{name:'수입·지출 기록',exact:true}).waitFor();
 const account=async(name)=>{await f.locator('.oj-account details').evaluate(e=>e.open=true);await f.getByRole('button',{name,exact:true}).click()};
 const fill=async(name,amount)=>{await f.getByLabel('내용',{exact:true}).fill(name);await f.getByLabel('금액',{exact:true}).fill(amount);await f.getByRole('button',{name:'기록 저장',exact:true}).click()};
 await fill('점심','9000');await page.waitForFunction(()=>JSON.parse(localStorage.getItem('cloud:'+owner)||'null')?.payload.tables.transactions.length===1);
 assert.equal(await f.getByRole('heading',{name:'오쭈다 가계부'}).count(),1);
 await f.getByRole('link',{name:'데이터 입력'}).click();await f.getByRole('button',{name:'점심 수정',exact:true}).click();await f.getByLabel('금액',{exact:true}).fill('10000');await f.getByRole('button',{name:'수정 저장',exact:true}).click();await page.waitForFunction(()=>JSON.parse(localStorage.getItem('cloud:'+owner)).payload.tables.transactions[0].amount===10000);
 // A failed account write must keep the local transaction after reopening.
 await page.evaluate(()=>fail=true);await fill('오프라인 기록','3000');await f.getByText('이 기기에는 저장됐어요.',{exact:false}).waitFor();await page.reload();f=page.frameLocator('iframe');await f.getByText('수입·지출 기록 ＋',{exact:true}).click();await f.getByRole('heading',{name:'수입·지출 기록',exact:true}).waitFor();await page.waitForFunction(()=>JSON.parse(localStorage.getItem('cloud:'+owner))?.payload.tables.transactions.length===2);
 // A lost response is recovered without duplicating the recorded transaction.
 await page.evaluate(()=>lost=true);await fill('응답 유실','4000');await f.getByText('이 기기에는 저장됐어요.',{exact:false}).waitFor();await account('다시 저장·새로고침');await f.getByText('계정에 저장되어 있어요.',{exact:true}).waitFor();assert.equal(await page.evaluate(()=>JSON.parse(localStorage.getItem('cloud:'+owner)).payload.tables.transactions.length),3);
 // Import is a copy and its persistent marker prevents resurrection after deletion.
 await page.evaluate(()=>localStorage.setItem('legacy:'+owner,JSON.stringify([{id:'30000000-0000-0000-0000-000000000001',date:'2026-10-04',type:'income',category:'용돈',memo:'옛 기록',amount:20000,deleted_at:null}])));
 await account('기존 가계부 가져오기');await f.getByText('1개 가져왔어요.',{exact:false}).waitFor();await f.getByRole('link',{name:'데이터 입력'}).click();await f.getByRole('button',{name:'옛 기록 삭제',exact:true}).click();await account('기존 가계부 가져오기');await f.getByText('0개 가져왔어요.',{exact:false}).waitFor();assert.equal(await f.getByRole('button',{name:'옛 기록 삭제',exact:true}).count(),0);
 await page.waitForFunction(()=>JSON.parse(localStorage.getItem('cloud:'+owner)).payload.tables.appSettings.some(r=>r.key.startsWith('legacy:')));
 // Conflicting remote revision does not overwrite either version.
 await page.evaluate(()=>{const k='cloud:'+owner,v=JSON.parse(localStorage.getItem(k));v.revision=crypto.randomUUID();v.payload.tables.transactions[0].amount=777;localStorage.setItem(k,JSON.stringify(v))});await fill('충돌 보존','500');await f.getByText('다른 기기와 변경이 겹쳤어요.',{exact:false}).waitFor();assert.equal(await page.evaluate(()=>JSON.parse(localStorage.getItem('cloud:'+owner)).payload.tables.transactions[0].amount),777);
 // Backup includes budget settings and migration markers.
 const [download]=await Promise.all([page.waitForEvent('download'),account('파일로 백업')]);const backup=JSON.parse(fs.readFileSync(await download.path(),'utf8'));assert(backup.tables.appSettings.some(r=>r.key.startsWith('legacy:')));assert(backup.tables.transactions.some(r=>r.merchantName==='충돌 보존'));
 for(const width of [320,390,760]){await page.setViewportSize({width,height:844});assert(await page.frames()[1].evaluate(()=>document.documentElement.scrollWidth<=innerWidth));}
 await page.setViewportSize({width:390,height:844});await account('크게 보기·접기');assert.equal(await page.locator('.donflow-expanded').count(),1);await account('크게 보기·접기');
 await f.getByRole('link',{name:'대시보드'}).click();await f.getByText('수입·지출 기록 ＋',{exact:true}).waitFor();await page.frames()[1].evaluate(()=>document.fonts.ready);await page.screenshot({path:'/tmp/donflow-proof.png',fullPage:true});
 await page.evaluate(()=>{owner='10000000-0000-0000-0000-000000000002';show()});f=page.frameLocator('iframe');await f.getByText('수입·지출 기록 ＋',{exact:true}).click();await f.getByRole('heading',{name:'수입·지출 기록',exact:true}).waitFor();await f.getByRole('link',{name:'데이터 입력'}).click();assert.equal(await f.getByRole('button',{name:'점심 수정',exact:true}).count(),0);
 await page.evaluate(()=>{owner=null;show()});assert.equal(await page.locator('iframe').count(),0);assert.deepEqual(errors,[]);
 console.log('PASS DonFlow: imported app, CRUD, cloud/local retry, uncertain save, migration, account conflict, export, mobile widths and account isolation');
}finally{await browser.close()}})().catch(e=>{console.error(e);process.exitCode=1});
