const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
const {chromium}=require('playwright');
const root=path.resolve(__dirname,'..');
const parent=`<!doctype html><html><body><button id="open">제작실</button><script type="module">import{openFurnitureStudio}from'/house-test/studio-host.js?v=20261003-cushions3';window.auth={admin:true,id:'admin-a'};document.querySelector('#open').onclick=()=>{const owner=auth.id;openFurnitureStudio({owner,authorized:()=>auth.admin&&auth.id===owner});};</script></body></html>`;
(async()=>{const browser=await chromium.launch({headless:true,executablePath:process.env.PLAYWRIGHT_CHROMIUM_EXECUTABLE_PATH||undefined,args:['--no-sandbox']});try{
const context=await browser.newContext({viewport:{width:1440,height:1050}}),errors=[],missing=[];
await context.route('**/*',route=>{const u=new URL(route.request().url());if(u.hostname!=='fixture.test')return route.abort();if(process.env.STUDIO_FONT_DIR&&u.pathname.startsWith('/_fonts/'))return route.fulfill({path:path.join(process.env.STUDIO_FONT_DIR,u.pathname.slice(8))});if(u.pathname==='/fixture')return route.fulfill({contentType:'text/html',body:parent});const f=path.join(root,u.pathname);if(!f.startsWith(root+'/')||!fs.existsSync(f)||!fs.statSync(f).isFile()){missing.push(u.pathname);return route.abort();}return route.fulfill({path:f});});
if(process.env.STUDIO_FONT_DIR)await context.addInitScript(()=>document.addEventListener('DOMContentLoaded',()=>{const link=document.createElement('link');link.rel='stylesheet';link.href='/_fonts/400.css';document.head.append(link);const style=document.createElement('style');style.textContent='body,button,input,select,textarea{font-family:"Noto Sans KR",sans-serif!important}';document.head.append(style);}));
const page=await context.newPage();page.on('pageerror',e=>{errors.push(e.message);console.log('PAGEERROR',e.message)});page.on('dialog',d=>d.accept());
await page.goto('https://fixture.test/house-test/anchor-editor/index.html');assert.equal(await page.locator('#studio-editor').isVisible(),false);
await page.goto('https://fixture.test/fixture');await page.evaluate(()=>auth.admin=false);await page.locator('#open').click();assert.equal(await page.locator('iframe').count(),0);await page.evaluate(()=>auth.admin=true);await page.locator('#open').click();
const studio=()=>page.frames().find(f=>f.url().includes('/anchor-editor/index.html'));const home=()=>page.frames().find(f=>/house-test\/index.html/.test(f.url()));
await page.frameLocator('iframe').locator('#studio-editor').waitFor({state:'visible'});let f=studio();console.log('studio open');assert(await f.locator('#studio-apply').isDisabled());await f.locator('#studio-side-table').click();await f.waitForFunction(()=>!document.querySelector('#studio-apply').disabled,{},{timeout:30000});console.log('project ready');
await f.evaluate(()=>document.fonts.ready);await page.screenshot({path:'/tmp/studio-desktop.png'});
const bundle=await f.evaluate(async()=>{const a=await import('./app.js?v=20261003-cushions3');return a.studioBundle()});
assert.equal(bundle.project.complete,true);
await f.evaluate(async runtime=>{const {validateRuntime}=await import('./runtime.js?v=20261003-cushions3');runtime.views.left.drawings[0].data='https://example.test/not-a-png';let rejected=false;try{validateRuntime(runtime);}catch{rejected=true;}if(!rejected)throw new Error('External image URL must be rejected');},structuredClone(bundle.runtime));
const before=await page.evaluate(()=>JSON.stringify({...localStorage}));await f.locator('#studio-preview').click();
await page.waitForFunction(()=>document.querySelectorAll('iframe').length===2);await page.frameLocator('iframe[title="우리집"]').locator('#app').waitFor({state:'visible'});await home().locator('#app').waitFor({state:'visible'});let h=home();await h.locator('[data-furniture^="made-"][data-render-state="ready"]').waitFor();console.log('preview ready');
for(const d of ['center','left','right']){await h.locator(`button[data-direction="${d}"]:not(.furniture)`).click();await h.locator('[data-furniture^="made-"][data-render-state="ready"]').waitFor();await page.screenshot({path:`/tmp/studio-preview-${d}.png`});}
assert.equal(await h.locator('nav').isVisible(),false);await h.locator('#exit').click();await page.waitForFunction(()=>document.querySelectorAll('iframe').length===1);assert.equal(await page.evaluate(()=>JSON.stringify({...localStorage})),before,'preview must not write saved room');console.log('preview unchanged');
await f.locator('#studio-apply').click();await page.waitForFunction(()=>document.querySelectorAll('iframe').length===2);await page.frameLocator('iframe[title="우리집"]').locator('#app').waitFor({state:'visible'});h=home();await h.locator('#app').waitFor({state:'visible'});await h.locator('[data-furniture^="made-"][data-render-state="ready"]').waitFor();const id=await h.locator('[data-furniture^="made-"]').getAttribute('data-furniture');await h.locator('#placement-done').click();await h.locator('#exit').click();console.log('applied',id);
const saved=await page.evaluate(()=>JSON.parse(localStorage.getItem('ojjuda-house-playtest-v1:admin-a')));assert(saved.rooms[0].furniture[id]);await f.locator('#studio-refresh').click();await f.locator(`#studio-saved-items option[value="${id}"]`).waitFor({state:'attached'});await f.locator('#studio-saved-items').selectOption(id);await f.locator('#studio-open-saved').click();console.log('reopened');
await f.locator('#studio-home').click();await page.waitForFunction(()=>document.querySelectorAll('iframe').length===2);await page.frameLocator('iframe[title="우리집"]').locator('#app').waitFor({state:'visible'});h=home();await h.locator('[data-furniture^="made-"][data-render-state="ready"]').waitFor();assert.equal(await h.locator('[data-furniture^="made-"]').getAttribute('data-furniture'),id);await h.locator('#exit').click();
await page.setViewportSize({width:390,height:844});await page.screenshot({path:'/tmp/studio-mobile.png'});assert(await f.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),'no horizontal overflow');
await f.locator('#studio-preview').click();await page.frameLocator('iframe[title="우리집"]').locator('#app').waitFor({state:'visible'});await page.evaluate(()=>auth.admin=false);await page.waitForFunction(()=>document.querySelectorAll('iframe').length===0);await page.evaluate(()=>{auth.admin=true;auth.id='admin-b'});await page.locator('#open').click();await page.frameLocator('iframe').locator('#studio-editor').waitFor({state:'visible'});f=studio();assert.equal(await f.locator('#studio-saved-items option').count(),1);assert(await f.locator('#studio-apply').isDisabled());assert.equal(await f.locator('#draft-resume').isVisible(),false);console.log('owner isolation');
// Missing custom records cannot be silently removed by normalize/persist.
const missingSave={version:11,rooms:[{x:0,y:0,curtains:true,shelf:null,furniture:{'made-111111111111111111111111':{x:0,y:0,direction:'left'}}}],diary:'preserve'};
await page.evaluate(value=>localStorage.setItem('ojjuda-house-playtest-v1:admin-b',JSON.stringify(value)),missingSave);
await f.locator('#studio-home').click();await page.frameLocator('iframe[title="우리집"]').locator('#locked p').filter({hasText:'기존 배치는 보존'}).waitFor();
assert.deepEqual(await page.evaluate(()=>JSON.parse(localStorage.getItem('ojjuda-house-playtest-v1:admin-b'))),missingSave);

console.log(JSON.stringify({errors,missing}));assert.deepEqual(errors,[]);assert.deepEqual(missing,[]);console.log('STUDIO PASS');
} finally {await browser.close();}})().catch(e=>{console.error(e);process.exit(1)});
