const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
const {chromium}=require('playwright'),makeFixture=require('./fixtures/house-album.cjs'),root=path.resolve(__dirname,'..');
const fixture=`<!doctype html><meta charset="utf-8"><button id="open">우리집</button><script type="module">
import {openHouseTest} from '/house-test/host.js';import{createWorldRecords}from'/house-test/world-records.js';
const make=${makeFixture.toString()};window.fixture=make();window.owner=fixture.owner;
document.querySelector('#open').onclick=()=>{const account=owner;const authorized=()=>owner===account;const records=createWorldRecords({client:fixture.client,owner:account,authorized,getFriends:()=>[{id:'friend-a',nick:'오랜 친구'}],prepareMedia:async file=>({body:file,thumb:file,kind:file.type.startsWith('video/')?'video':'image',mime:file.type})});openHouseTest({owner:account,authorized,records});};</script>`;
(async()=>{
 const browser=await chromium.launch({headless:true,executablePath:process.env.PLAYWRIGHT_CHROMIUM_EXECUTABLE_PATH||undefined,args:['--no-sandbox']});
 try{
  const context=await browser.newContext({viewport:{width:390,height:844}});await context.route('**/*',route=>{const u=new URL(route.request().url());if(u.hostname!=='fixture.test')return route.abort();if(u.pathname==='/fixture')return route.fulfill({contentType:'text/html',body:fixture});if(u.pathname==='/proof.ttf'&&process.env.HOUSE_RECORDS_PROOF_FONT)return route.fulfill({path:process.env.HOUSE_RECORDS_PROOF_FONT});const file=path.resolve(root,'.'+u.pathname);return file.startsWith(root+path.sep)&&fs.existsSync(file)?route.fulfill({path:file}):route.abort();});
  if(process.env.HOUSE_RECORDS_PROOF_FONT)await context.addInitScript(()=>document.addEventListener('DOMContentLoaded',()=>{const s=document.createElement('style');s.textContent='@font-face{font-family:ManagementProof;src:url(/proof.ttf)}html,body,button,input,textarea,select{font-family:ManagementProof,sans-serif!important}';document.head.append(s);},{once:true}));
  const page=await context.newPage(),errors=[];page.on('pageerror',e=>errors.push(e.message));await page.goto('https://fixture.test/fixture');await page.locator('#open').click();await page.frameLocator('iframe').locator('[data-cloud-record-id="old-video"]').waitFor();const f=page.frames().find(x=>x.url().includes('/house-test/index.html')),cloud=f.locator('.cloud-records'),gear=f.getByRole('button',{name:'우리집 설정',exact:true});
  const before=await page.evaluate(()=>JSON.stringify(fixture.db.media));
  const proof=async name=>{if(!process.env.HOUSE_MANAGEMENT_PROOF_DIR)return;fs.mkdirSync(process.env.HOUSE_MANAGEMENT_PROOF_DIR,{recursive:true});await f.evaluate(()=>document.fonts.ready);await page.screenshot({path:path.join(process.env.HOUSE_MANAGEMENT_PROOF_DIR,name+'.png')});};
  for(const width of [320,360,390,1280]){
   await page.setViewportSize({width,height:844});const video=await f.getByRole('tab',{name:'동영상',exact:true}).boundingBox(),settings=await gear.boundingBox();assert(settings.x>=video.x+video.width&&settings.x-video.x-video.width<12,'gear sits immediately beside video');
   await gear.click();const modal=f.getByRole('dialog',{name:'우리집 설정',exact:true});await modal.waitFor();
   const layout=await modal.evaluate(el=>({widthFits:el.scrollWidth<=el.clientWidth,height:el.getBoundingClientRect().height,buttons:[...el.querySelectorAll('button')].filter(b=>b.getClientRects().length).map(b=>({label:b.getAttribute('aria-label')||b.textContent,height:b.getBoundingClientRect().height,width:b.getBoundingClientRect().width}))}));
   assert.equal(layout.widthFits,true,'settings fit without horizontal scrolling');assert(layout.height<=420,'first settings screen stays compact');assert.equal(layout.buttons.length,5,'first screen contains only close and four choices');assert(layout.buttons.every(button=>button.height>=44&&button.width>=44),'settings choices and close have comfortable touch targets');
   for(const name of ['폴더 관리','친구 그룹','게시물 정리','휴지통'])assert.equal(await modal.getByRole('button',{name,exact:true}).isVisible(),true);
   assert.equal(await modal.getByRole('button',{name:/폴더 수정|폴더 삭제|그룹 삭제/}).count(),0,'detail and destructive actions are kept out of the overview');await proof('settings-menu-'+width);
   await modal.getByRole('button',{name:'폴더 관리',exact:true}).click();assert.equal(await modal.getByRole('heading',{name:'폴더 관리',exact:true}).isVisible(),true);assert.equal(await modal.getByRole('button',{name:'추억 폴더 수정',exact:true}).isVisible(),true);assert.equal(await modal.getByRole('button',{name:/폴더 삭제/}).count(),0,'deleting a folder requires opening its editor');await proof('settings-folders-'+width);
   await modal.getByRole('button',{name:'뒤로',exact:true}).click();assert.equal(await modal.getByRole('heading',{name:'우리집 설정',exact:true}).isVisible(),true);
   await modal.getByRole('button',{name:'친구 그룹',exact:true}).click();assert.equal(await modal.getByRole('button',{name:'새 그룹',exact:true}).isVisible(),true);await modal.getByRole('button',{name:'뒤로',exact:true}).click();
   await page.keyboard.press('Escape');await modal.waitFor({state:'detached'});assert.equal(await page.locator('iframe').count(),1);
  }
  // A long folder list scrolls inside the dialog, while close/back stay reachable.
  await page.setViewportSize({width:360,height:640});await page.evaluate(()=>{for(let i=0;i<18;i++)fixture.db.media_folders.push({id:'layout-'+i,user_id:fixture.owner,name:'오래 간직하고 싶은 가족과 여행 추억 '+i,visibility:'me',allowed:[],created_at:'2026-10-01'});});
  await cloud.getByRole('button',{name:'새로고침',exact:true}).click();await f.waitForFunction(()=>!document.querySelector('.cloud-records .record-status').textContent);await gear.click();let modal=f.getByRole('dialog',{name:'우리집 설정',exact:true});await modal.getByRole('button',{name:'폴더 관리',exact:true}).click();
  const closeBefore=await modal.getByRole('button',{name:'닫기',exact:true}).boundingBox();await modal.getByRole('button',{name:'오래 간직하고 싶은 가족과 여행 추억 17 폴더 수정',exact:true}).scrollIntoViewIfNeeded();const closeAfter=await modal.getByRole('button',{name:'닫기',exact:true}).boundingBox();
  assert(Math.abs(closeBefore.y-closeAfter.y)<1,'long lists retain the close button position');assert.equal(await modal.evaluate(el=>el.scrollWidth<=el.clientWidth&&el.getBoundingClientRect().bottom<=innerHeight&&el.getBoundingClientRect().top>=0),true,'long lists stay within the phone viewport');assert.equal(await modal.getByRole('button',{name:'뒤로',exact:true}).isVisible(),true);await proof('settings-long-folders-360');await modal.getByRole('button',{name:'뒤로',exact:true}).click();assert.equal(await modal.getByRole('button',{name:'친구 그룹',exact:true}).isVisible(),true);await modal.getByRole('button',{name:'닫기',exact:true}).click();
  await page.evaluate(()=>fixture.db.media_folders.splice(2));await cloud.getByRole('button',{name:'새로고침',exact:true}).click();await f.waitForFunction(()=>!document.querySelector('.cloud-records .record-status').textContent);
  await page.setViewportSize({width:390,height:844});await gear.click();await f.getByRole('button',{name:'폴더 관리',exact:true}).click();await f.getByRole('button',{name:'추억 폴더 수정',exact:true}).click();await cloud.getByLabel('폴더 이름',{exact:true}).fill('가족');await cloud.getByRole('button',{name:'폴더 저장',exact:true}).click();await cloud.getByRole('status').filter({hasText:'폴더를 저장'}).waitFor();assert.equal(await page.evaluate(()=>fixture.db.media_folders.find(x=>x.id==='old-folder').name),'가족');assert.equal(await page.evaluate(()=>JSON.stringify(fixture.db.media)),before,'rename changes no post or file');
  const askDelete=async()=>{await gear.click();await f.getByRole('button',{name:'폴더 관리',exact:true}).click();await f.getByRole('button',{name:'가족 폴더 수정',exact:true}).click();await f.getByRole('button',{name:'가족 폴더 삭제',exact:true}).click();};
  await askDelete();await cloud.getByRole('button',{name:'취소',exact:true}).click();assert.equal(await page.evaluate(()=>fixture.db.media_folders.length),2);
  await askDelete();await page.evaluate(()=>fixture.state.fail='rpc');await cloud.getByRole('button',{name:'폴더만 삭제',exact:true}).click();await cloud.getByRole('status').filter({hasText:'연결을 확인'}).waitFor();assert.equal(await page.evaluate(()=>JSON.stringify(fixture.db.media)),before);
  await page.evaluate(()=>fixture.state.fail=null);await cloud.getByRole('button',{name:'폴더만 삭제',exact:true}).click();await cloud.getByRole('status').filter({hasText:'사진·동영상은 미분류'}).waitFor();assert.equal(await page.evaluate(()=>fixture.db.media.length),4);assert.equal(await page.evaluate(()=>fixture.db.media.find(x=>x.id==='old-photo').path),'member-a/photo.jpg');assert.deepEqual(await page.evaluate(()=>{const x=fixture.db.media.find(x=>x.id==='old-photo');return [x.folder_id,x.visibility];}),[null,'me']);assert.equal(await f.locator('[data-folder-id="none"]').getAttribute('aria-pressed'),'true');
  await gear.click();await f.getByRole('button',{name:'게시물 정리',exact:true}).click();await cloud.getByRole('checkbox',{name:'기존 사진 선택',exact:true}).check();await cloud.getByRole('checkbox',{name:'기존 영상 선택',exact:true}).check();assert.equal(await cloud.locator('.record-selection-count').textContent(),'2개 선택');await cloud.getByRole('combobox',{name:'선택한 게시물을 옮길 폴더'}).selectOption('note-folder');await cloud.getByRole('button',{name:'선택한 게시물 이동',exact:true}).click();assert.match(await cloud.locator('.record-management-confirm').textContent(),/나만 보기/);await cloud.getByRole('button',{name:'취소',exact:true}).click();assert.equal(await page.evaluate(()=>fixture.db.media.find(x=>x.id==='old-video').folder_id),null);
  await cloud.getByRole('button',{name:'선택한 게시물 이동',exact:true}).click();await page.evaluate(()=>fixture.state.fail='rpc');await cloud.getByRole('button',{name:'이동하기',exact:true}).click();await cloud.getByRole('status').filter({hasText:'연결을 확인'}).waitFor();assert.equal(await cloud.locator('.record-selection-count').textContent(),'2개 선택');await page.evaluate(()=>fixture.state.fail=null);await cloud.getByRole('button',{name:'이동하기',exact:true}).click();await cloud.getByRole('status').filter({hasText:'2개 게시물을 옮겼어요'}).waitFor();assert.deepEqual(await page.evaluate(()=>fixture.db.media.filter(x=>['old-photo','old-video'].includes(x.id)).map(x=>x.folder_id)),['note-folder','note-folder']);assert.equal(await cloud.locator('[data-cloud-record-id]').count(),3);assert.equal(await cloud.locator('.record-selection-count').textContent(),'0개 선택');
  assert.equal(await cloud.locator('[data-cloud-record-id]').evaluateAll(els=>els.every(el=>el.getBoundingClientRect().height===els[0].getBoundingClientRect().height&&el.getBoundingClientRect().height<=128)),true);await cloud.getByRole('button',{name:'선택 끝내기',exact:true}).click();assert.equal(await cloud.getByRole('checkbox').count(),0);
  if(process.env.HOUSE_MANAGEMENT_PROOF_DIR){fs.mkdirSync(process.env.HOUSE_MANAGEMENT_PROOF_DIR,{recursive:true});await f.evaluate(()=>document.fonts.ready);await page.screenshot({path:path.join(process.env.HOUSE_MANAGEMENT_PROOF_DIR,'management-feed.png')});await gear.click();await page.screenshot({path:path.join(process.env.HOUSE_MANAGEMENT_PROOF_DIR,'management-settings.png')});await page.keyboard.press('Escape');}
  await page.evaluate(()=>{for(let i=0;i<14;i++)fixture.db.media.push({...fixture.db.media[0],id:'extra-'+i,caption:'추억 '+i,created_at:'2026-10-05'});});await cloud.getByRole('button',{name:'새로고침',exact:true}).click();await cloud.getByRole('button',{name:'더 보기',exact:true}).waitFor();await gear.click();await f.getByRole('button',{name:'게시물 정리',exact:true}).click();await cloud.getByRole('checkbox').first().check();const selectedLabel=await cloud.getByRole('checkbox').first().getAttribute('aria-label');await cloud.getByRole('button',{name:'더 보기',exact:true}).click();await f.waitForFunction(()=>document.querySelectorAll('[data-cloud-record-id]').length===17);assert.equal(await cloud.getByRole('checkbox',{name:selectedLabel,exact:true}).isChecked(),true,'loading more keeps earlier choices');
  await f.locator('[data-folder-id="all"]').click();await f.waitForFunction(()=>document.querySelector('.record-selection-count').textContent==='0개 선택');
  await f.locator('[data-folder-id="note-folder"]').click();await f.waitForFunction(()=>document.querySelectorAll('[data-cloud-record-id]').length===12);
  await page.evaluate(()=>fixture.client.rpc('house_delete_media_folder',{p_folder_id:'note-folder'}));await cloud.getByRole('button',{name:'새로고침',exact:true}).click();
  await f.waitForFunction(()=>document.querySelector('.cloud-records .record-status').textContent==='');
  assert.equal(await f.locator('[data-folder-id="all"]').getAttribute('aria-pressed'),'true','a folder deleted elsewhere returns to the complete list');
  assert.equal(await cloud.locator('[data-cloud-record-id]').count(),12,'remaining records stay visible after an externally deleted folder');
  assert.equal(await page.evaluate(()=>fixture.calls.some(x=>x.remove)),false);await page.evaluate(()=>owner='member-b');await page.locator('iframe').waitFor({state:'detached'});assert.deepEqual(errors,[]);
  console.log('PASS: gear placement, compact settings overview, detail/back navigation, long-list scrolling, modal keyboard/mobile layout, folder rename/cancel/delete/retry with retained private files, atomic selected moves/retry, pagination selection, account cleanup');
 }finally{await browser.close();}
})().catch(e=>{console.error(e);process.exitCode=1;});
