const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
const fixture=require('./fixtures/house-album.cjs'),root=path.resolve(__dirname,'..');
(async()=>{
 const {createWorldRecords}=await import('data:text/javascript;base64,'+fs.readFileSync(path.join(root,'house-test/world-records.js')).toString('base64'));
 const f=fixture();let owner=f.owner,changes=[];
 const api=createWorldRecords({client:f.client,owner:f.owner,authorized:()=>owner===f.owner,getFriends:()=>[{id:'friend-a',nick:'친구'}],prepareMedia:async file=>({body:file,thumb:file,kind:'image',mime:'image/jpeg'}),onChange:change=>changes.push(change)});
 const first=await api('list',{kind:'photo'});assert.deepEqual(first.records.map(x=>x.id),['old-photo','note-photo']);assert.equal(first.records[1].visibility,'me');assert(first.records.every(row=>!('path'in row)&&!('thumb_path'in row)));
 assert.deepEqual(f.calls.find(x=>x.signed).signed,['member-a/thumb.jpg','member-a/note-thumb.jpg']);
 assert.equal((await api('list',{kind:'video'})).records[0].id,'old-video');assert.equal((await api('list',{kind:'photo',folder:'note-folder'})).records[0].id,'note-photo');
 const combined=await api('list',{kind:'all'});assert.deepEqual(combined.records.map(x=>x.id),['old-photo','note-photo','old-video']);
 assert.equal((await api('list',{kind:'all',folder:'none'})).records.length,3,'all does not use folder filters');
 assert(first.folders.every(folder=>folder.kind==='photo'),'folder kinds reach the UI');
 assert.equal((await api('list',{kind:'video',folder:'note-folder'})).records.length,0,'folder filter cannot cross record types');
 assert.equal((await api('list',{kind:'photo',folder:'deleted-folder'})).folders.length,2,'a stale folder still returns metadata so the UI can recover');
 assert.equal((await api('list',{kind:'text'})).records.length,0,'local diary is not presented as a server post');
 const pageFixture=fixture(),pageApi=createWorldRecords({client:pageFixture.client,owner:pageFixture.owner,authorized:()=>true});
 for(let i=0;i<20;i++)pageFixture.db.media.push({...pageFixture.db.media[0],id:'page-'+String(i).padStart(2,'0'),type:i%2?'image':'video',created_at:'2026-10-01'});
 const page1=await pageApi('list',{kind:'all'}),page2=await pageApi('list',{kind:'all',offset:12});assert.equal(page1.records.length,12);assert.equal(page1.more,true);assert.equal(page2.more,false);assert.equal(new Set([...page1.records,...page2.records].map(x=>x.id)).size,23,'mixed pagination omits no record and duplicates none');
 await assert.rejects(api('open',{id:'other-photo'}));await api('open',{id:'old-photo'});assert.deepEqual(f.calls.at(-1).signed,['member-a/photo.jpg']);
 const folder=await api('save-folder',{kind:'photo',name:'여행',visibility:'chosen',allowed:['friend-a']});assert.equal(folder.visibility,'chosen');assert.deepEqual(folder.allowed,['friend-a']);
 await assert.rejects(api('save-folder',{kind:'photo',name:'실수',visibility:'chosen',allowed:['stranger']}));
 const group=await api('save-group',{id:'group-a',name:'가족',members:['friend-a','friend-a'],create:true});assert.deepEqual(group.members,['friend-a']);
 f.db.house_friend_groups.push({id:'foreign',user_id:'member-b',name:'남의 그룹',members:[]});
 assert.deepEqual((await api('list',{kind:'all'})).groups.map(row=>row.id),['group-a']);
 await assert.rejects(api('save-group',{id:'bad',name:'금지',members:['stranger'],create:true}));await assert.rejects(api('delete-group',{id:'foreign'}));
 await assert.rejects(api('save-folder',{kind:'photo',name:'오류',visibility:'chosen',allowed_groups:['foreign']}));
 const shared=await api('save-folder',{kind:'photo',name:'그룹 공개',visibility:'chosen',allowed_groups:['group-a']});assert.deepEqual(shared.allowed_groups,['group-a']);
 await api('save-group',{id:'group-a',name:'가족 수정',members:[]});assert.equal(f.db.house_friend_groups[0].name,'가족 수정');
 await api('delete-group',{id:'group-a'});assert.deepEqual(f.db.media_folders.find(row=>row.id===shared.id).allowed_groups,[]);assert.equal(changes.at(-1).deletedGroup,'group-a');
 await api('save-folder',{kind:'photo',id:shared.id,name:'나만 남음',visibility:'chosen',allowed:[],allowed_groups:[]});
 await api('save-media',{id:'old-photo',caption:'가족 사진',visibility:'me',folder_id:folder.id});assert.equal(f.db.media[0].folder_id,folder.id);
 await assert.rejects(api('save-media',{id:'other-photo',caption:'bad',visibility:'all',folder_id:null}));assert.equal(f.db.media.at(-1).visibility,'me');
 await assert.rejects(api('save-media',{id:'old-photo',visibility:'all',folder_id:'someone-elses-folder'}));
 await assert.rejects(api('save-folder',{name:'누락',visibility:'me'}),/폴더 종류/);
 await assert.rejects(api('save-folder',{id:folder.id,kind:'video',name:'종류 변경',visibility:'me'}),/같은 종류/);
 const videoFolder=await api('save-folder',{name:'여행',kind:'video',visibility:'me'});assert.equal(videoFolder.kind,'video');
 await assert.rejects(api('save-media',{id:'old-photo',caption:'이동 실패',visibility:'me',folder_id:videoFolder.id}),/같은 종류/);
 const photo=new Blob(['photo'],{type:'image/jpeg'});await api('upload',{file:photo,kind:'photo',folder_id:'note-folder',caption:'  여행 사진\n좋은 하루  '});const added=f.db.media.at(-1);assert.equal(added.caption,'여행 사진\n좋은 하루');assert.equal(added.user_id,f.owner);assert.equal(added.visibility,'me');assert.equal(added.folder_id,'note-folder');assert(f.files.has(added.path));assert(f.files.has(added.thumb_path));
 await assert.rejects(api('upload',{file:photo,kind:'photo',folder_id:videoFolder.id}),/같은 종류/);
 await assert.rejects(api('upload',{file:photo,kind:'photo',caption:'가'.repeat(101)}),/100자/);
 const count=f.db.media.length,fileCount=f.files.size;f.state.fail='thumb';await assert.rejects(api('upload',{file:photo,kind:'photo'}));assert.equal(f.db.media.length,count);assert.equal(f.files.size,fileCount,'thumbnail failure removes only the new original');
 f.state.fail='insert';await assert.rejects(api('upload',{file:photo,kind:'photo'}));assert.equal(f.files.size,fileCount,'confirmed insert failure rolls back new files');f.state.fail=null;
 for(const call of f.calls.filter(x=>x.table&&x.operation!=='insert'))assert(call.filters.some(([key,value])=>key==='user_id'&&value===f.owner),'every read/update is owner scoped');
 for(const call of f.calls.filter(x=>x.operation==='insert'))assert.equal(call.values.user_id,f.owner);
 const management=fixture(),updates=[],manage=createWorldRecords({client:management.client,owner:management.owner,authorized:()=>true,onChange:change=>updates.push(change)});
 await assert.rejects(manage('move-media',{ids:[],folder_id:null}));await assert.rejects(manage('move-media',{ids:Array(101).fill('old-photo')}));
 await assert.rejects(manage('move-media',{ids:['old-photo','old-video'],folder_id:'note-folder'}),/같은 종류/);
 await manage('move-media',{ids:['old-photo','note-photo'],folder_id:'note-folder'});assert.equal(management.db.media.find(x=>x.id==='old-photo').folder_id,'note-folder');assert.deepEqual(updates.at(-1).movedMedia.ids,['old-photo','note-photo']);
 await assert.rejects(manage('move-media',{ids:['old-photo','other-photo'],folder_id:null}));assert.equal(management.db.media[0].folder_id,'note-folder');
 management.state.fail='rpc';await assert.rejects(manage('delete-folder',{id:'note-folder'}));assert.equal(management.db.media_folders.length,2);management.state.fail=null;
 await manage('delete-folder',{id:'note-folder'});assert.equal(management.db.media.length,4);assert(management.db.media.filter(x=>x.user_id===management.owner).every(x=>x.folder_id===null&&x.visibility==='me'));assert.equal(updates.at(-1).deletedFolder,'note-folder');assert.equal(management.calls.filter(x=>x.remove).length,0,'folder management never deletes storage files');
 const posts=fixture(),events=[],postApi=createWorldRecords({client:posts.client,owner:posts.owner,authorized:()=>true,onChange:change=>events.push(change)});
 await postApi('save-post',{id:'old-photo',body:'동일 ID의 별도 글',create:true});await postApi('save-post',{id:'post-two',body:'두 번째 글',create:true});
 assert.equal((await postApi('list',{kind:'text'})).records.length,2);assert.equal((await postApi('list',{kind:'all'})).records.length,5);
 const textFolder=await postApi('save-folder',{name:'기록',kind:'text',visibility:'me'});
 await assert.rejects(postApi('save-post',{id:'post-two',body:'사진 폴더 금지',folder_id:'note-folder'}),/같은 종류/);
 await postApi('save-post',{id:'post-two',body:'노트 폴더',folder_id:textFolder.id});
 await assert.rejects(postApi('manage-records',{action:'move',media_ids:['old-photo'],post_ids:['post-two'],folder_id:textFolder.id}),/같은 종류/);
 await assert.rejects(postApi('manage-records',{action:'move',media_ids:['old-video'],folder_id:'note-folder'}),/같은 종류/);
 await postApi('manage-records',{action:'move',media_ids:['old-photo'],post_ids:['post-two'],folder_id:null});
 assert.equal(posts.db.house_posts.find(row=>row.id==='post-two').folder_id,null,'mixed selections may be unfiled');
 const text=await postApi('open',{id:'old-photo',type:'text'});assert.equal(text.caption,'동일 ID의 별도 글');assert.equal(text.url,undefined);
 await postApi('manage-records',{action:'trash',media_ids:['old-photo'],post_ids:['post-two']});assert.equal((await postApi('list',{kind:'all'})).records.length,3);assert.equal((await postApi('list',{kind:'all',trash:true,folder:'old-folder'})).records.length,2,'trash is independent of the currently selected folder');assert.deepEqual(events.at(-1).trashedMedia,['old-photo']);
 assert((await postApi('open',{id:'old-photo',type:'image',trash:true})).url.includes('photo.jpg'));
 await postApi('manage-records',{action:'restore',media_ids:['old-photo'],post_ids:['post-two']});assert.equal(events.at(-1).media.visibility,'me');assert.equal((await postApi('list',{kind:'all',trash:true})).records.length,0);assert.equal(posts.calls.some(x=>x.remove),false);
 await assert.rejects(postApi('save-post',{id:'bad',body:'  ',create:true}));await assert.rejects(postApi('manage-records',{action:'trash',media_ids:[]}));await assert.rejects(postApi('manage-records',{action:'trash',post_ids:['missing']}));
 let release;f.state.pause=new Promise(resolve=>release=resolve);const delayed=api('list',{kind:'photo'});await Promise.resolve();owner='member-b';release();await assert.rejects(delayed);await assert.rejects(api('save-folder',{kind:'photo',name:'blocked',visibility:'all'}));assert.equal(f.db.media.find(x=>x.id==='other-photo').caption,'다른 계정 사진');
 console.log('PASS: restored server album, owner scoping, chosen privacy, folder moves, upload rollback, account revocation');
})().catch(error=>{console.error(error);process.exitCode=1;});
