const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
const {PGlite}=require('@electric-sql/pglite');
const root=path.resolve(__dirname,'..'),migration=fs.readdirSync(path.join(root,'supabase/migrations')).find(n=>n.endsWith('_house_record_management.sql'));
const a='10000000-0000-0000-0000-000000000001',b='10000000-0000-0000-0000-000000000002',fa='20000000-0000-0000-0000-000000000001',fb='20000000-0000-0000-0000-000000000002';
(async()=>{const db=new PGlite();try{
 await db.exec(`create role anon;create role authenticated;create schema auth;
 create function auth.uid() returns uuid language sql stable as $$select nullif(current_setting('request.jwt.claim.sub',true),'')::uuid$$;
 create function public.is_banned(uuid) returns boolean language sql stable as $$select coalesce(current_setting('test.banned',true),'')='yes'$$;
 create table public.media_folders(id uuid primary key,user_id uuid not null,name text,visibility text);
 create table public.media(id text primary key,user_id uuid not null,folder_id uuid references public.media_folders(id) on delete set null,visibility text,path text);
 alter table public.media enable row level security;alter table public.media_folders enable row level security;
 create policy own_folder on public.media_folders to authenticated using(user_id=auth.uid()) with check(user_id=auth.uid());
 create policy own_media on public.media to authenticated using(user_id=auth.uid()) with check(user_id=auth.uid());
 grant usage on schema public,auth to authenticated,anon;grant select,update,delete,insert on public.media,public.media_folders to authenticated;
 insert into public.media_folders values('${fa}','${a}','친구','chosen'),('${fb}','${b}','다른 계정','me');
 insert into public.media values('a1','${a}','${fa}','all','original-a.jpg'),('a2','${a}',null,'friends','original-b.mp4'),('b1','${b}','${fb}','me','other.jpg');`);
 await db.exec(fs.readFileSync(path.join(root,'supabase/migrations',migration),'utf8'));
 const permissions=await db.query("select has_function_privilege('anon','public.house_delete_media_folder(uuid)','execute') anon, has_function_privilege('authenticated','public.house_move_media(text[],uuid)','execute') member");assert.deepEqual(permissions.rows,[{anon:false,member:true}]);
 assert((await db.query("select prosecdef from pg_proc where proname in ('house_move_media','house_delete_media_folder')")).rows.every(r=>!r.prosecdef),'RLS is never bypassed');
 await db.exec(`set role authenticated;set request.jwt.claim.sub='${a}';`);
 const snapshot=async()=>JSON.stringify((await db.query('select * from public.media order by id')).rows);
 let original=await snapshot();
 await assert.rejects(db.query('select public.house_move_media($1,$2)',[['a1','b1'],fa]),/house_media_unavailable/);assert.equal(await snapshot(),original,'one foreign ID prevents every update');
 await assert.rejects(db.query('select public.house_move_media($1,$2)',[['a1'],fb]),/house_folder_unavailable/);assert.equal(await snapshot(),original);
 await assert.rejects(db.query('select public.house_delete_media_folder($1)',[fb]),/house_folder_unavailable/);
 for(const ids of [[],null,Array(101).fill('a1'),['a1',null]])await assert.rejects(db.query('select public.house_move_media($1,$2)',[ids,fa]),/house_media_selection_invalid/);
 await db.exec("set test.banned='yes'");await assert.rejects(db.query('select public.house_delete_media_folder($1)',[fa]),/house_management_denied/);await assert.rejects(db.query('select public.house_move_media($1,$2)',[['a1'],fa]),/house_management_denied/);assert.equal(await snapshot(),original);await db.exec("set test.banned='no'");
 await db.exec('reset role');await db.exec("create function public.reject_folder_delete() returns trigger language plpgsql as $$begin raise exception 'fixture_delete_failed';end$$;create trigger reject_delete before delete on public.media_folders for each row execute function public.reject_folder_delete();set role authenticated;");
 await assert.rejects(db.query('select public.house_delete_media_folder($1)',[fa]),/fixture_delete_failed/);assert.equal(await snapshot(),original,'folder failure rolls back all media changes');
 await db.exec('reset role;drop trigger reject_delete on public.media_folders;set role authenticated;');
 let moved=(await db.query('select public.house_move_media($1,$2) result',[['a1','a2','a1'],fa])).rows[0].result;assert.equal(moved.moved,2);assert.deepEqual(moved.ids,['a1','a2']);
 const removed=(await db.query('select public.house_delete_media_folder($1) result',[fa])).rows[0].result;assert.equal(removed.moved,2);assert.equal((await db.query('select * from public.media_folders')).rows.length,0);
 const kept=(await db.query('select id,folder_id,visibility,path from public.media order by id')).rows;assert.deepEqual(kept,[{id:'a1',folder_id:null,visibility:'me',path:'original-a.jpg'},{id:'a2',folder_id:null,visibility:'me',path:'original-b.mp4'}]);
 await db.query("update public.media set visibility='all' where id='a2'");await db.query('select public.house_move_media($1,$2)',[['a2'],null]);assert.equal((await db.query("select visibility from public.media where id='a2'")).rows[0].visibility,'me');
 await db.exec("set request.jwt.claim.sub=''");await assert.rejects(db.query('select public.house_move_media($1,$2)',[['a1'],null]),/house_management_denied/);
 await db.exec(`set request.jwt.claim.sub='${b}'`);assert.deepEqual((await db.query('select * from public.media')).rows,[{id:'b1',user_id:b,folder_id:fb,visibility:'me',path:'other.jpg'}]);
 console.log('PASS: owner-only atomic folder removal/moves, no file deletion, private unfiled media, foreign/missing/null/oversized selections, ban/guest denial and transaction rollback');
 }finally{await db.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
