const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
const {PGlite}=require('@electric-sql/pglite');
const root=path.resolve(__dirname,'..'),a='10000000-0000-0000-0000-000000000001',b='10000000-0000-0000-0000-000000000002',c='10000000-0000-0000-0000-000000000003',fa='20000000-0000-0000-0000-000000000001',fb='20000000-0000-0000-0000-000000000002';
(async()=>{const db=new PGlite();try{
 await db.exec(`create role anon;create role authenticated;create role service_role;create schema auth;
 create function auth.uid() returns uuid language sql stable as $$select nullif(current_setting('request.jwt.claim.sub',true),'')::uuid$$;
 create function public.is_banned(uuid) returns boolean language sql stable as $$select coalesce(current_setting('test.banned',true),'')='yes'$$;
 create function public.door_open(uuid) returns boolean language sql stable as $$select coalesce(current_setting('test.door',true),'open')<>'closed'$$;
 create function public.is_friend(a uuid,b uuid) returns boolean language sql stable as $$select a='${a}'::uuid and b='${b}'::uuid or a='${b}'::uuid and b='${a}'::uuid$$;
 create table public.profiles(id uuid primary key);insert into public.profiles values('${a}'),('${b}'),('${c}');
 create table public.media_folders(id uuid primary key,user_id uuid not null,name text,visibility text,allowed uuid[] default '{}',created_at timestamptz default now());
 create function public.folder_can_see(fid uuid,viewer uuid) returns boolean language sql security definer set search_path='' as $$select exists(select 1 from public.media_folders f where f.id=fid and (f.user_id=viewer or public.door_open(f.user_id) and (f.visibility='all' or f.visibility='friends' and public.is_friend(f.user_id,viewer) or f.visibility='chosen' and viewer=any(f.allowed) and public.is_friend(f.user_id,viewer))))$$;
 create table public.media(id text primary key,user_id uuid not null references public.profiles(id),type text not null,path text not null unique,thumb_path text,caption text not null default '',duration real not null default 0,visibility text not null default 'me',folder_id uuid references public.media_folders(id) on delete set null,created_at timestamptz not null default now());
 alter table public.media enable row level security;alter table public.media_folders enable row level security;
 create policy folder_read on public.media_folders for select to authenticated using(user_id=auth.uid() or folder_can_see(id,auth.uid()));
 create policy folder_write on public.media_folders for all to authenticated using(user_id=auth.uid()) with check(user_id=auth.uid());
 create policy media_read on public.media for select to authenticated using(user_id=auth.uid() or door_open(user_id) and case when folder_id is null then visibility='all' or visibility='friends' and is_friend(user_id,auth.uid()) else folder_can_see(folder_id,auth.uid()) end);
 create policy media_insert on public.media for insert to authenticated with check(user_id=auth.uid() and path like auth.uid()::text||'/%' and not is_banned(auth.uid()));
 create policy media_update on public.media for update to authenticated using(user_id=auth.uid() and not is_banned(auth.uid())) with check(user_id=auth.uid() and not is_banned(auth.uid()));
 create policy media_delete on public.media for delete to authenticated using(user_id=auth.uid());
 grant usage on schema public,auth to authenticated,anon;grant select,insert,update,delete on public.media,public.media_folders to authenticated;
 insert into public.media_folders(id,user_id,name,visibility,allowed) values('${fa}','${a}','고른 친구','chosen',array['${b}'::uuid]),('${fb}','${b}','다른 계정','me','{}');
 insert into public.media(id,user_id,type,path,thumb_path,caption,visibility,folder_id,created_at) values('a-media','${a}','image','${a}/photo.jpg','${a}/thumb.jpg','보존할 사진','all','${fa}','2026-01-01'),('b-media','${b}','video','${b}/video.mp4',null,'다른 기록','me',null,'2026-01-02');`);
 const migration=fs.readdirSync(path.join(root,'supabase/migrations')).find(n=>n.endsWith('_house_posts_trash.sql'));await db.exec(fs.readFileSync(path.join(root,'supabase/migrations',migration),'utf8'));
 assert((await db.query("select prosecdef from pg_proc where proname in ('house_save_post','house_manage_records','house_post_guard')")).rows.every(r=>!r.prosecdef));
 assert.equal((await db.query("select has_function_privilege('anon','public.house_manage_records(text,text[],text[],uuid)','execute') ok")).rows[0].ok,false);
 assert.equal((await db.query("select has_table_privilege('authenticated','public.house_posts','delete') ok")).rows[0].ok,false);
 const as=async id=>db.exec(`set role authenticated;set request.jwt.claim.sub='${id}';`),save=(id,body,folder=null,vis='me',create=true)=>db.query('select public.house_save_post($1,$2,$3,$4,$5)',[id,body,folder,vis,create]),manage=(action,media=[],posts=[],folder=null)=>db.query('select public.house_manage_records($1,$2,$3,$4)',[action,media,posts,folder]),ids=async view=>(await db.query('select id from public.'+view+' order by id')).rows.map(r=>r.id);
 await as(a);await save('post','첫 번째 글',fa,'all');await save('post','재시도한 글',fa,'all');assert.deepEqual(await ids('house_posts'),['post'],'create retries reuse ID');await save('post','수정한 글',fa,'all',false);
 for(const body of ['', '   ', 'x'.repeat(4001)])await assert.rejects(save('bad',body));
 await db.exec('reset role');
 const unlimited=fs.readdirSync(path.join(root,'supabase/migrations')).find(n=>n.endsWith('_house_notes_unlimited_body.sql'));await db.exec(fs.readFileSync(path.join(root,'supabase/migrations',unlimited),'utf8'));await as(a);
 const longBody='긴 노트의 본문과 줄바꿈을 보존합니다.\n'.repeat(500);await save('post',longBody,fa,'all',false);
 assert.equal((await db.query("select body from public.house_posts where id='post'")).rows[0].body,longBody,'house notes preserve more than 4,000 characters');
 await save('post','수정한 글',fa,'all',false);for(const body of ['', '   '])await assert.rejects(save('bad',body));
 await assert.rejects(save('bad','다른 폴더',fb));await assert.rejects(save('missing','실수',null,'me',false));
 await assert.rejects(db.query("update public.house_posts set user_id=$1 where id='post'",[b]));
 await save('public','공개 글',null,'all');await save('friend','친구 글',null,'friends');await save('private','비밀 글');
 await as(b);assert.deepEqual(await ids('house_posts'),['friend','post','public']);await assert.rejects(save('post','남의 글 수정',null,'me',false));await assert.rejects(save('post','남의 ID 사용'));await assert.rejects(manage('trash',['a-media'],['post']));
 await as(c);assert.deepEqual(await ids('house_posts'),['public']);assert.deepEqual(await ids('house_trash_records'),[]);
 await as(a);const original=(await db.query('select * from public.media where id=\'a-media\'')).rows[0];
 await assert.rejects(manage('trash',['a-media','b-media'],['post']));assert.deepEqual(await ids('house_media_trash'),[]);
 for(const args of [['trash',[],[]],['trash',null,[]],['trash',['a-media',null],[]],['trash',Array(101).fill('a-media'),[]],['wrong',['a-media'],[]]])await assert.rejects(manage(...args));
 await db.exec("reset role;create function public.fail_post_update() returns trigger language plpgsql as $$begin if current_setting('test.fail',true)='yes' then raise exception 'forced_failure';end if;return new;end$$;create trigger fail_post before update on public.house_posts for each row execute function public.fail_post_update();set role authenticated;set test.fail='yes';");
 await assert.rejects(manage('trash',['a-media'],['post']),/forced_failure/);assert.deepEqual(await ids('house_media_trash'),[]);assert.equal((await db.query("select count(*)::int n from public.media where id='a-media'")).rows[0].n,1,'later failure rolls back earlier archive and deletion');await db.exec("set test.fail='no'");
 await manage('trash',['a-media'],['post']);assert.deepEqual(await ids('house_media_trash'),['a-media']);assert.deepEqual(await ids('house_trash_records'),['a-media','post']);assert(!(await ids('house_records')).includes('post'));
 await assert.rejects(save('post','휴지통 글 덮어쓰기'));await as(b);assert.deepEqual(await ids('house_trash_records'),[]);assert(!(await ids('house_records')).includes('a-media'));assert(!(await ids('house_posts')).includes('post'));await assert.rejects(manage('restore',['a-media'],['post']));
 await as(a);await db.exec(`insert into public.media(id,user_id,type,path) values('a-media','${a}','image','${a}/conflict.jpg')`);await assert.rejects(manage('restore',['a-media'],['post']));assert.deepEqual(await ids('house_trash_records'),['a-media','post'],'restore collision retains every trashed record');await db.exec("delete from public.media where id='a-media'");
 await db.query('select public.house_delete_media_folder($1)',[fa]);await manage('restore',['a-media'],['post']);assert.deepEqual(await ids('house_trash_records'),[]);
 const back=(await db.query("select * from public.media where id='a-media'")).rows[0];assert.equal(back.path,original.path);assert.equal(back.thumb_path,original.thumb_path);assert.equal(back.created_at.getTime(),original.created_at.getTime());assert.equal(back.folder_id,null);assert.equal(back.visibility,'me');
 const post=(await db.query("select * from public.house_posts where id='post'")).rows[0];assert.equal(post.body,'수정한 글');assert.equal(post.deleted_at,null);assert.equal(post.folder_id,null);assert.equal(post.visibility,'me');
 await manage('move',['a-media'],['post'],null);await db.exec("set test.banned='yes'");await assert.rejects(save('blocked','차단됨'));await assert.rejects(manage('trash',['a-media'],[]));await db.exec("set test.banned='no';set request.jwt.claim.sub=''");await assert.rejects(save('guest','비로그인'));await assert.rejects(manage('restore',['a-media'],[]));
 await as(c);await db.exec("set test.door='closed'");assert.deepEqual(await ids('house_posts'),[]);
 await db.exec('set role anon');await assert.rejects(db.query('select * from public.house_records'));await assert.rejects(db.query('select * from public.house_trash_records'));
 console.log('PASS: multi-post save/retry/edit, folder/friend/door RLS, private trash, atomic rollback, restore conflict preservation, original file/time retention, guest/ban/foreign denial');
 }finally{await db.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
