const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
const {chromium}=require('playwright'),makeFixture=require('./fixtures/house-album.cjs'),root=path.resolve(__dirname,'..');
const fixture=`<!doctype html><meta charset="utf-8"><button id="open">우리집</button><script type="module">
import {openHouseTest} from '/house-test/host.js';import{createWorldRecords}from'/house-test/world-records.js';
const make=${makeFixture.toString()};window.fixture=make();window.owner=fixture.owner;
document.querySelector('#open').onclick=()=>{const account=owner;const authorized=()=>owner===account;const records=createWorldRecords({client:fixture.client,owner:account,authorized,getFriends:()=>[{id:'friend-a',nick:'오랜 친구'},{id:'friend-b',nick:'여행 친구'}],prepareMedia:async file=>({body:file,thumb:file,kind:file.type.startsWith('video/')?'video':'image',mime:file.type})});openHouseTest({owner:account,authorized,records});};</script>`;
(async()=>{
 const browser=await chromium.launch({headless:true,executablePath:process.env.PLAYWRIGHT_CHROMIUM_EXECUTABLE_PATH||undefined,args:['--no-sandbox']});
 try{
  const context=await browser.newContext({viewport:{width:390,height:844}});await context.route('**/*',route=>{const u=new URL(route.request().url());if(u.hostname!=='fixture.test')return route.abort();if(u.pathname==='/fixture')return route.fulfill({contentType:'text/html',body:fixture});if(u.pathname==='/proof.ttf'&&process.env.HOUSE_RECORDS_PROOF_FONT)return route.fulfill({path:process.env.HOUSE_RECORDS_PROOF_FONT});const file=path.resolve(root,'.'+u.pathname);return file.startsWith(root+path.sep)&&fs.existsSync(file)?route.fulfill({path:file}):route.abort();});
  if(process.env.HOUSE_RECORDS_PROOF_FONT)await context.addInitScript(()=>document.addEventListener('DOMContentLoaded',()=>{const s=document.createElement('style');s.textContent='@font-face{font-family:PostProof;src:url(/proof.ttf)}html,body,button,input,textarea,select{font-family:PostProof,sans-serif!important}';document.head.append(s);},{once:true}));
  const page=await context.newPage(),errors=[];page.on('pageerror',e=>errors.push(e.message));await page.goto('https://fixture.test/fixture');await page.locator('#open').click();await page.frameLocator('iframe').getByRole('tab',{name:'전체',exact:true}).waitFor();let f=page.frames().find(x=>x.url().includes('/house-test/index.html'));await f.locator('[data-cloud-record-id="old-video"]').waitFor();let cloud=f.locator('.cloud-records');
  const status=text=>cloud.getByRole('status').filter({hasText:text}).waitFor(),gear=()=>f.getByRole('button',{name:'우리집 설정',exact:true}).click();
  await gear();await f.getByRole('button',{name:'+ 새 그룹',exact:true}).click();await cloud.getByLabel('그룹 이름',{exact:true}).fill('가족');await cloud.getByLabel('오랜 친구',{exact:true}).check();
  await page.evaluate(()=>fixture.state.fail='rpc');await cloud.getByRole('button',{name:'그룹 만들기',exact:true}).click();await status('연결을 확인');assert.equal(await cloud.getByLabel('그룹 이름',{exact:true}).inputValue(),'가족');assert.equal(await cloud.getByLabel('오랜 친구',{exact:true}).isChecked(),true);
  await page.evaluate(()=>fixture.state.fail=null);await cloud.getByRole('button',{name:'그룹 만들기',exact:true}).click();await status('친구 그룹을 저장');const ga=await page.evaluate(()=>fixture.db.house_friend_groups[0].id);assert.deepEqual(await page.evaluate(()=>fixture.db.house_friend_groups[0].members),['friend-a']);
  await gear();await f.getByRole('button',{name:'+ 새 그룹',exact:true}).click();await cloud.getByLabel('그룹 이름',{exact:true}).fill('여행');await cloud.getByLabel('여행 친구',{exact:true}).check();await cloud.getByRole('button',{name:'그룹 만들기',exact:true}).click();await status('친구 그룹을 저장');const gb=await page.evaluate(()=>fixture.db.house_friend_groups[1].id);
  await f.getByRole('button',{name:'+ 새폴더',exact:true}).click();await cloud.getByLabel('폴더 이름',{exact:true}).fill('함께 보는 기록');await cloud.getByRole('combobox',{name:'폴더 공개범위'}).selectOption('chosen');await cloud.getByLabel('가족 · 1명',{exact:true}).check();await cloud.getByLabel('여행 · 1명',{exact:true}).check();await cloud.getByLabel('오랜 친구',{exact:true}).check();
  for(const width of [320,390,1280]){await page.setViewportSize({width,height:844});assert.equal(await f.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);assert.equal(await cloud.locator('form').evaluate(el=>el.scrollWidth<=el.clientWidth),true);}
  await page.setViewportSize({width:390,height:844});if(process.env.HOUSE_GROUPS_PROOF_DIR){fs.mkdirSync(process.env.HOUSE_GROUPS_PROOF_DIR,{recursive:true});await f.evaluate(()=>document.fonts.ready);await page.screenshot({path:path.join(process.env.HOUSE_GROUPS_PROOF_DIR,'folder-groups.png')});}
  await cloud.getByRole('button',{name:'폴더 만들기',exact:true}).click();await status('폴더를 저장');const folder=await page.evaluate(()=>fixture.db.media_folders.at(-1));assert.deepEqual(folder.allowed_groups,[ga,gb]);assert.deepEqual(folder.allowed,['friend-a']);
  await gear();await f.getByRole('button',{name:'가족 그룹 수정',exact:true}).click();await cloud.getByLabel('오랜 친구',{exact:true}).uncheck();await cloud.getByLabel('여행 친구',{exact:true}).check();await cloud.getByLabel('그룹 이름',{exact:true}).fill('가족 모임');await cloud.getByRole('button',{name:'그룹 저장',exact:true}).click();await status('친구 그룹을 저장');assert.deepEqual(await page.evaluate(()=>fixture.db.house_friend_groups[0].members),['friend-b']);
  await gear();await f.getByRole('button',{name:'함께 보는 기록 폴더 수정',exact:true}).click();assert.equal(await cloud.getByLabel('가족 모임 · 1명',{exact:true}).isChecked(),true);assert.equal(await cloud.getByLabel('여행 · 1명',{exact:true}).isChecked(),true);await cloud.getByLabel('오랜 친구',{exact:true}).uncheck();await cloud.getByRole('button',{name:'폴더 저장',exact:true}).click();await status('폴더를 저장');
  await gear();if(process.env.HOUSE_GROUPS_PROOF_DIR)await page.screenshot({path:path.join(process.env.HOUSE_GROUPS_PROOF_DIR,'settings-groups.png')});await f.getByRole('button',{name:'가족 모임 그룹 삭제',exact:true}).click();await cloud.getByRole('button',{name:'취소',exact:true}).click();assert.equal(await page.evaluate(()=>fixture.db.house_friend_groups.length),2);
  await gear();await f.getByRole('button',{name:'가족 모임 그룹 삭제',exact:true}).click();await page.evaluate(()=>fixture.state.fail='rpc');await cloud.getByRole('button',{name:'그룹만 삭제',exact:true}).click();await status('연결을 확인');assert.equal(await page.evaluate(()=>fixture.db.house_friend_groups.length),2);await page.evaluate(()=>fixture.state.fail=null);await cloud.getByRole('button',{name:'그룹만 삭제',exact:true}).click();await status('친구 그룹을 삭제');assert.deepEqual(await page.evaluate(()=>fixture.db.media_folders.at(-1).allowed_groups),[gb]);
  await gear();await f.getByRole('button',{name:'여행 그룹 삭제',exact:true}).click();await cloud.getByRole('button',{name:'그룹만 삭제',exact:true}).click();await status('친구 그룹을 삭제');assert.deepEqual(await page.evaluate(()=>fixture.db.media_folders.at(-1).allowed_groups),[]);assert.equal(await page.evaluate(()=>fixture.db.media_folders.at(-1).visibility),'chosen');assert.equal(await page.evaluate(()=>fixture.db.media.length),4);assert.equal(await page.evaluate(()=>fixture.calls.some(x=>x.remove)),false);
  await gear();await f.getByRole('button',{name:'함께 보는 기록 폴더 수정',exact:true}).click();assert.match(await cloud.locator('form').textContent(),/아무도 선택하지 않으면 나만/);await cloud.getByRole('button',{name:'폴더 저장',exact:true}).click();await status('폴더를 저장');
  await gear();await f.getByRole('button',{name:'+ 새 그룹',exact:true}).click();await cloud.getByLabel('그룹 이름',{exact:true}).fill('빈 그룹');await cloud.getByRole('button',{name:'그룹 만들기',exact:true}).click();await status('친구 그룹을 저장');
  await page.evaluate(()=>{owner='member-b';fixture.state.owner=owner;});await page.locator('iframe').waitFor({state:'detached'});await page.locator('#open').click();await page.frameLocator('iframe').getByRole('tab',{name:'전체',exact:true}).waitFor();f=page.frames().find(x=>x.url().includes('/house-test/index.html'));cloud=f.locator('.cloud-records');await cloud.locator('[data-cloud-record-id="other-photo"]').waitFor();await gear();assert.equal(await f.getByRole('button',{name:'빈 그룹 그룹 수정',exact:true}).count(),0);await page.keyboard.press('Escape');assert.equal(await page.locator('iframe').count(),1);assert.deepEqual(errors,[]);
  console.log('PASS: friend group create/retry/edit, multiple folder groups plus friends, empty scope, delete cancel/failure/retry, record retention, mobile widths and account isolation');
 }finally{await browser.close();}
})().catch(e=>{console.error(e);process.exitCode=1;});
