const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
const {chromium}=require('playwright'),root=path.resolve(__dirname,'..'),makeFixture=require('./fixtures/house-album.cjs');
const proof=process.env.HOUSE_ROOM_PROOF_DIR;
const fixture=`<!doctype html><meta charset="utf-8"><button id="open">우리집</button><script type="module">
import{openHouseTest}from'/house-test/host.js';import{createWorldRecords}from'/house-test/world-records.js';
const make=${makeFixture.toString()};window.fixture=make();window.owner='member-a';window.readOnly=false;window.calls=[];window.failure=null;window.found=true;window.photoCalls=0;
const room=(x,y)=>({x,y,curtains:false,shelf:null,furniture:{}});window.cloud={version:13,rooms:[room(0,0),room(1,0),room(0,1)]};window.rev='v1';window.local={version:13,rooms:[room(0,0)],diary:'숨겨도 남아야 하는 글'};localStorage.setItem('ojjuda-house-playtest-v1:member-a',JSON.stringify(local));
window.inline=false;window.mount=document.createElement('main');document.body.append(mount);window.closeHouse=null;document.querySelector('#open').onclick=()=>{const account=owner;closeHouse=openHouseTest({owner:account,readOnly,mountTarget:inline?mount:null,authorized:()=>owner===account,profile:{nick:'포근한 하루',bio:'소소한 일상 기록'},onProfilePhoto:async()=>{photoCalls++;return {avatar_url:'/house-test/assets/entry-house-v1.webp'};},records:readOnly?null:createWorldRecords({client:fixture.client,owner:account,authorized:()=>owner===account}),room:async(action,args)=>{calls.push({action,args:structuredClone(args)});if(action==='load'){if(failure==='load')throw new Error('방 연결 실패');return {ok:true,found,snapshot:structuredClone(cloud),revision:rev};}if(window.pauseNextSave){pauseNextSave=false;await new Promise(resolve=>window.releaseSave=resolve);}if(failure==='save')throw new Error('방 저장 실패');if(failure==='conflict')return {ok:false,reason:'conflict'};cloud=structuredClone(args.snapshot);rev+='x';return {ok:true,revision:rev};}});};</script>`;
(async()=>{const browser=await chromium.launch({headless:true,executablePath:process.env.PLAYWRIGHT_CHROMIUM_EXECUTABLE_PATH||undefined,args:['--no-sandbox']});try{
 const context=await browser.newContext({viewport:{width:390,height:844}});await context.route('**/*',route=>{const u=new URL(route.request().url());if(u.hostname!=='fixture.test')return route.abort();if(u.pathname==='/fixture')return route.fulfill({contentType:'text/html',body:fixture});if(u.pathname==='/proof.ttf'&&process.env.HOUSE_RECORDS_PROOF_FONT)return route.fulfill({path:process.env.HOUSE_RECORDS_PROOF_FONT});const file=path.resolve(root,'.'+u.pathname);return file.startsWith(root+path.sep)&&fs.existsSync(file)&&fs.statSync(file).isFile()?route.fulfill({path:file}):route.abort();});
 if(process.env.HOUSE_RECORDS_PROOF_FONT)await context.addInitScript(()=>document.addEventListener('DOMContentLoaded',()=>{const style=document.createElement('style');style.textContent='@font-face{font-family:RoomProof;src:url(/proof.ttf)}html,body,button,input,textarea,select{font-family:RoomProof,sans-serif!important}';document.head.append(style);},{once:true}));
 const page=await context.newPage(),errors=[];page.on('pageerror',error=>errors.push(error.message));await page.goto('https://fixture.test/fixture');
 const open=async()=>{await page.locator('#open').click();await page.locator('[aria-busy="false"]').waitFor();const frame=page.frames().find(f=>f.url().includes('/house-test/index.html'));await frame.locator('#home-profile-nick').waitFor();return frame;};
 let f=await open();assert.equal(await f.locator('.room').count(),3,'cloud layout replaces the one-room preview');
 assert.equal(await page.evaluate(()=>Object.keys(localStorage).filter(key=>key.startsWith('ojjuda-house-playtest-v1:member-a:before-cloud:')).some(key=>JSON.parse(localStorage[key]).diary===local.diary&&JSON.parse(localStorage[key]).rooms.length===1)),true,'original device save is backed up before cloud use');
 await f.getByRole('tab',{name:'앨범',exact:true}).click();await f.locator('[data-cloud-record-id="old-photo"]').waitFor();await f.locator('[data-folder-id="old-folder"]').click();await f.locator('[data-cloud-record-id="old-photo"]').waitFor();
 await page.evaluate(()=>{cloud.rooms[0].curtains=true;rev='refresh-v2';fixture.db.media.find(x=>x.id==='old-photo').caption='새로 불러온 사진';});
 assert.equal(await page.evaluate(()=>closeHouse.refresh()),true);assert.equal(await f.getByRole('tab',{name:'앨범',exact:true}).getAttribute('aria-selected'),'true');assert.equal(await f.locator('[data-folder-id="old-folder"]').getAttribute('aria-pressed'),'true');await f.getByText('새로 불러온 사진',{exact:true}).waitFor();assert.equal(await f.locator('.room[data-room="0:0"] .curtains').count(),1,'refresh reads new room data while retaining the record category and folder');
 await page.evaluate(()=>{cloud.rooms[0].curtains=false;rev='refresh-v3';});assert.equal(await page.evaluate(()=>closeHouse.refresh()),true);await f.getByRole('tab',{name:'전체',exact:true}).click();
 for(const [width,height]of [[320,568],[390,844],[1280,900]]){await page.setViewportSize({width,height});await f.evaluate(()=>new Promise(resolve=>requestAnimationFrame(()=>requestAnimationFrame(resolve))));const fit=await f.evaluate(()=>{const area=document.querySelector('#viewport').getBoundingClientRect(),boxes=[...document.querySelectorAll('.room')].map(el=>{const box=el.getBoundingClientRect(),scale=box.width/1507;return {left:box.left+38*scale,right:box.left+1468*scale,top:box.top+58*scale,bottom:box.top+910*scale};});return area.width<=420.5&&area.height<=220.5&&boxes.every(box=>box.left>=area.left-.5&&box.right<=area.right+.5&&box.top>=area.top-.5&&box.bottom<=area.bottom+.5)&&Math.abs(Math.max(...boxes.map(box=>box.right))-area.right)<1&&Math.abs(Math.min(...boxes.map(box=>box.left))-area.left)<1&&Math.abs(Math.min(...boxes.map(box=>box.top))-area.top)<1&&Math.abs(Math.max(...boxes.map(box=>box.bottom))-area.bottom)<1;});assert.equal(fit,true,'all owned room interiors fill the compact preview without outer margins');if(proof){fs.mkdirSync(proof,{recursive:true});await f.evaluate(()=>document.fonts.ready);await page.screenshot({path:path.join(proof,`multi-room-${width}.png`)});}}
 await page.setViewportSize({width:390,height:844});await f.locator('#home-profile-photo').click();await f.locator('#home-profile-photo img').waitFor();assert.equal(await page.evaluate(()=>photoCalls),1);
 await f.getByRole('button',{name:'＋ 글쓰기',exact:true}).click();await f.getByLabel('노트 글',{exact:true}).fill('키보드가 올라와도 기록 종류와 폴더를 가리지 않아요');assert.equal(await page.evaluate(()=>closeHouse.refresh()),false,'refresh never discards an open editor');await page.setViewportSize({width:390,height:330});await f.getByRole('tab',{name:'전체',exact:true}).scrollIntoViewIfNeeded();const navigation=await f.evaluate(()=>{const panel=document.querySelector('#panel-tabs').getBoundingClientRect(),tabs=document.querySelector('.record-tabs').getBoundingClientRect(),folders=document.querySelector('.record-folders').getBoundingClientRect();return {tabs:tabs.top-panel.bottom,folders:document.querySelector('.record-folders').hidden?0:folders.top-tabs.bottom,app:getComputedStyle(document.querySelector('#app')).overflowY,inner:getComputedStyle(document.querySelector('#panel-body')).overflowY,sticky:getComputedStyle(document.querySelector('.record-tabs')).position};});assert(navigation.tabs>=0&&navigation.folders>=0,'menu, category and folder rows do not overlap');assert.equal(navigation.app,'auto');assert.equal(navigation.inner,'visible');assert.equal(navigation.sticky,'static');if(proof)await page.screenshot({path:path.join(proof,'keyboard-390.png')});
 await page.setViewportSize({width:390,height:844});await f.locator('[data-tab="room"]').click();await f.locator('[data-category="settings"]').click();await page.evaluate(()=>failure='save');await f.getByRole('button',{name:'커튼 달기',exact:true}).click();await page.getByText('방 저장 실패',{exact:true}).waitFor();assert.equal(await page.evaluate(()=>JSON.parse(localStorage['ojjuda-house-playtest-v1:member-a']).rooms[0].curtains),true,'failed remote write stays saved on device');await page.evaluate(()=>failure=null);await page.getByRole('button',{name:'다시 시도',exact:true}).click();await page.waitForFunction(()=>cloud.rooms[0].curtains===true);assert.equal(await page.evaluate(()=>JSON.parse(localStorage['ojjuda-house-playtest-v1:member-a']).diary), '숨겨도 남아야 하는 글');
 await page.evaluate(()=>failure='conflict');await f.getByRole('button',{name:'커튼 걷기',exact:true}).click();await page.getByText(/다른 곳에서 방이 바뀌었어요/).waitFor();assert.equal(await page.evaluate(()=>cloud.rooms[0].curtains),true,'conflict never overwrites newer remote state');assert.equal(await page.evaluate(()=>JSON.parse(localStorage['ojjuda-house-playtest-v1:member-a']).rooms[0].curtains),false,'conflicting local edit remains available');

 // Closing while one write is in flight must recover the later device edit.
 await page.evaluate(()=>{closeHouse();failure=null;});f=await open();await page.waitForFunction(()=>cloud.rooms[0].curtains===false);
 await f.locator('[data-tab="room"]').click();await f.locator('[data-category="settings"]').click();await page.evaluate(()=>pauseNextSave=true);await f.getByRole('button',{name:'커튼 달기',exact:true}).click();await page.waitForFunction(()=>typeof releaseSave==='function');await f.getByRole('button',{name:'커튼 걷기',exact:true}).click();await page.evaluate(()=>{closeHouse();releaseSave();});await page.waitForFunction(()=>cloud.rooms[0].curtains===true);
 f=await open();assert.equal(await f.locator('.room[data-room="0:0"] .curtains').count(),0,'reopening displays the latest local edit, not the earlier in-flight cloud snapshot');await page.getByText(/이 기기의 최근 배치를 복구했어요/).waitFor();await page.getByRole('button',{name:'이 배치 저장',exact:true}).click();await page.waitForFunction(()=>cloud.rooms[0].curtains===false);assert.equal(await page.evaluate(()=>localStorage.getItem('ojjuda-house-playtest-v1:member-a:pending-cloud')),null);
 // Unknown custom artwork keeps the original cloud and device placements intact.
 await page.evaluate(()=>{closeHouse();cloud.rooms[0].furniture['made-other-device']={direction:'left',x:2,y:2};window.customBefore=JSON.stringify(cloud);window.deviceBefore=localStorage['ojjuda-house-playtest-v1:member-a'];});f=await open();assert.equal(await f.locator('[data-tab="room"]').isDisabled(),true);await f.getByText('이 기기에 없는 제작 가구는 표시할 수 없어요.',{exact:true}).waitFor();await page.evaluate(()=>closeHouse());assert.equal(await page.evaluate(()=>JSON.stringify(cloud)),await page.evaluate(()=>customBefore));assert.equal(await page.evaluate(()=>localStorage['ojjuda-house-playtest-v1:member-a']),await page.evaluate(()=>deviceBefore));await page.evaluate(()=>delete cloud.rooms[0].furniture['made-other-device']);
 // Enlarging another member's room exposes only viewing and camera controls.
 await page.evaluate(()=>{closeHouse();failure=null;readOnly=true;inline=true;owner='visitor-owner';cloud.rooms[0].furniture.sofa={direction:'left',x:0,y:3};window.before=JSON.stringify({...localStorage});window.visitorCloudBefore=JSON.stringify(cloud);window.visitorSavesBefore=calls.filter(call=>call.action==='save').length;});
 f=await open();assert.equal(await page.locator('iframe').getAttribute('title'),'포근한 하루님의 집');
 await f.evaluate(()=>new Promise(resolve=>requestAnimationFrame(()=>requestAnimationFrame(resolve))));
 assert.equal(await f.evaluate(()=>document.querySelector('#viewport').getBoundingClientRect().bottom<=innerHeight+1),true,'inline visitor frame fits its compact multi-room summary');
 assert.equal(await f.locator('#panel').isVisible(),false);assert.equal(await f.locator('#home-profile-photo').isDisabled(),true);
 assert.equal(await f.locator('#home-room-open').isVisible(),true,'a visitor can open the room preview');
 assert.equal(await f.locator('#home-room-open').getAttribute('aria-label'),'방 크게 보기');
 const summaryHeight=await page.locator('iframe').evaluate(frame=>frame.clientHeight),summaryWidth=await f.locator('#viewport').evaluate(view=>view.clientWidth);
 const cameraScale=()=>f.locator('#world').evaluate(world=>new DOMMatrix(getComputedStyle(world).transform).a);
 const assertReadOnly=async()=>{
  assert.equal(await f.locator('#world').evaluate(world=>world.inert),true,'room contents remain inert while camera controls work');
  assert.equal(await f.locator('#panel').isVisible(),false,'no furniture authoring panel appears');
  assert.equal(await f.locator('#expand').isVisible(),false,'a visitor cannot add rooms');
  assert.equal(await f.locator('#empty-room-toggle').isVisible(),false,'a visitor cannot remove furniture from view');
  assert.equal(await f.locator('#viewport').evaluate(view=>view.classList.contains('empty-room-preview')),false,'hidden authoring controls cannot change the displayed room');
  assert.equal(await f.locator('#placement-actions').isVisible(),false,'no placement buttons appear');
  assert.equal(await f.locator('.furniture').count()>0,true,'read-only checks cover a real saved furniture item');
  assert.equal(await f.locator('.furniture').evaluateAll(items=>items.every(item=>item.disabled)),true,'saved furniture never becomes editable');
 };
 await f.locator('#home-room-open').click();await f.locator('.camera').waitFor({state:'visible'});
 await page.waitForFunction(height=>document.querySelector('iframe').clientHeight>height+100,summaryHeight);
 assert.equal(await f.locator('#viewport').evaluate(view=>view.clientWidth)>summaryWidth,true,'the enlarged room uses the available width');
 assert.equal(await f.locator('#home-profile').isVisible(),false,'the expanded view focuses on the room');
 await assertReadOnly();
 if(proof){for(const [width,height]of [[320,568],[390,844],[844,390]]){
  await page.setViewportSize({width,height});await f.evaluate(()=>new Promise(resolve=>requestAnimationFrame(()=>requestAnimationFrame(resolve))));await f.evaluate(()=>document.fonts.ready);
  assert.equal(await f.evaluate(()=>{const view=document.querySelector('#viewport').getBoundingClientRect(),camera=document.querySelector('.camera').getBoundingClientRect();return document.documentElement.scrollWidth<=innerWidth&&view.height>0&&camera.bottom<=innerHeight+1;}),true,'visitor camera controls fit '+width+'x'+height);
  await page.screenshot({path:path.join(proof,`visitor-expanded-${width}x${height}.png`)});
 }await page.setViewportSize({width:390,height:844});await f.evaluate(()=>new Promise(resolve=>requestAnimationFrame(()=>requestAnimationFrame(resolve))));}
 const initialScale=await cameraScale();await f.locator('#zoom-in').click();assert.equal(await cameraScale()>initialScale,true,'the visitor can zoom into the saved room');
 const zoomedScale=await cameraScale();await f.locator('#zoom-out').click();assert.equal(await cameraScale()<zoomedScale,true,'the visitor can zoom back out');
 await f.locator('#overview').click();const wholeScale=await cameraScale();await f.locator('#home-view').click();assert.equal(await cameraScale()>wholeScale,true,'current-room and whole-home views use the saved multi-room geometry');
 await f.locator('#zoom-in').click();
 const panBefore=await f.locator('#world').evaluate(world=>world.style.transform),area=await f.locator('#viewport').boundingBox();
 await page.mouse.move(area.x+area.width*.55,area.y+area.height*.55);await page.mouse.down();await page.mouse.move(area.x+area.width*.72,area.y+area.height*.65,{steps:5});await page.mouse.up();
 assert.notEqual(await f.locator('#world').evaluate(world=>world.style.transform),panBefore,'dragging pans the enlarged room without editing furniture');
 // Even explicitly invoking hidden authoring controls cannot start a visitor edit.
 await f.evaluate(()=>{document.querySelector('#expand').click();document.querySelector('#empty-room-toggle').click();document.querySelector('#home-profile-photo').click();document.querySelector('.furniture').click();});
 await assertReadOnly();
 await f.locator('#viewport').focus();await page.keyboard.press('Escape');
 await f.locator('#home-room-open').waitFor({state:'visible'});await page.waitForFunction(height=>document.querySelector('iframe').clientHeight<=height+1,summaryHeight);
 assert.equal(await page.locator('iframe').count(),1,'Escape returns to the same visited home without closing it');
 assert.equal(await f.locator('.camera').isVisible(),false);
 if(proof){for(const [width,height]of [[320,568],[390,844]]){
  await page.setViewportSize({width,height});await f.evaluate(()=>new Promise(resolve=>requestAnimationFrame(()=>requestAnimationFrame(resolve))));await page.screenshot({path:path.join(proof,`visitor-summary-${width}.png`)});
 }await page.setViewportSize({width:390,height:844});await f.evaluate(()=>new Promise(resolve=>requestAnimationFrame(()=>requestAnimationFrame(resolve))));}
 await f.locator('#home-room-open').click();await f.locator('.camera').waitFor({state:'visible'});await f.locator('#exit').click();
 await f.locator('#home-room-open').waitFor({state:'visible'});assert.equal(await page.locator('iframe').count(),1,'the enlarged-room close button returns to the summary');
 await f.locator('#home-room-open').click();await f.locator('.camera').waitFor({state:'visible'});
 await page.evaluate(()=>window.dispatchEvent(new KeyboardEvent('keydown',{key:'Escape',bubbles:true,cancelable:true})));
 await f.locator('#home-room-open').waitFor({state:'visible'});assert.equal(await page.locator('iframe').count(),1,'parent-window Escape also collapses the view instead of leaving the visited home');
 assert.equal(await page.evaluate(()=>JSON.stringify(cloud)===visitorCloudBefore),true,'viewing never changes the saved remote layout');
 assert.equal(await page.evaluate(()=>calls.filter(call=>call.action==='save').length===visitorSavesBefore),true,'camera actions never request a server save');
 await page.evaluate(()=>closeHouse());assert.equal(await page.evaluate(()=>JSON.stringify({...localStorage})===before),true,'viewing and closing never write visitor device data');assert.equal(await page.evaluate(()=>photoCalls),1);


 // An immediate first-sync error remains visible when the room paint completes.
 await page.evaluate(()=>{readOnly=false;inline=false;owner='first-cloud';found=false;failure='save';});f=await open();await page.getByText('방 저장 실패',{exact:true}).waitFor();assert.equal(await f.locator('#app').isVisible(),true);assert.equal(await page.getByRole('button',{name:'다시 시도',exact:true}).isVisible(),true);await page.evaluate(()=>{closeHouse();found=true;});
 await page.evaluate(()=>{readOnly=false;owner='member-a';failure='load';});await page.locator('#open').click();await page.getByText('방 연결 실패',{exact:true}).waitFor();await page.evaluate(()=>failure=null);await page.getByRole('button',{name:'다시 시도',exact:true}).click();await page.locator('[aria-busy="false"]').waitFor();await page.frameLocator('iframe').locator('#home-profile-nick').waitFor();
 // If another window saves during cloud artwork loading, its latest rooms win.
 await page.evaluate(()=>{closeHouse();owner='cloud-race';cloud.rooms[0].furniture.carpet={direction:'center',x:1,y:3};localStorage.setItem('ojjuda-house-playtest-v1:cloud-race',JSON.stringify({version:13,rooms:[{x:0,y:0,curtains:false,shelf:null,furniture:{}}],diary:'처음 글'}));});
 let releaseArt,started;const startedArt=new Promise(resolve=>started=resolve),artGate=new Promise(resolve=>releaseArt=resolve);await context.route('**/carpet-v1.runtime.json*',async route=>{started();await artGate;await route.fallback();});await page.locator('#open').click();await startedArt;
 await page.evaluate(()=>{const latest=structuredClone(cloud);latest.rooms.push({x:1,y:1,curtains:false,shelf:null,furniture:{}});latest.diary='다른 창에서 저장한 최신 글';localStorage.setItem('ojjuda-house-playtest-v1:cloud-race',JSON.stringify(latest));});releaseArt();await page.frameLocator('iframe').locator('#home-profile-nick').waitFor();f=page.frames().find(frame=>frame.url().includes('/house-test/index.html'));assert.equal(await f.locator('.room').count(),4,'cloud loading never replaces a newer device save with its initial snapshot');await page.waitForFunction(()=>cloud.rooms.length===4);assert.equal(await page.evaluate(()=>JSON.parse(localStorage['ojjuda-house-playtest-v1:cloud-race']).diary),'다른 창에서 저장한 최신 글');await page.evaluate(()=>closeHouse());
 assert.deepEqual(errors,[]);console.log('PASS: unified multi-room fit, profile photo callback, keyboard scrolling, local backup, cloud save retry/conflict/latest-edit recovery, unavailable custom preservation, read-only visitor enlargement, camera controls and return navigation, and load retry');
}finally{await browser.close();}})().catch(error=>{console.error(error);process.exitCode=1;});
