const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
const {chromium}=require('playwright'),makeFixture=require('./fixtures/house-album.cjs'),root=path.resolve(__dirname,'..');
const fixture=`<!doctype html><meta charset="utf-8"><button id="open">우리집</button><script type="module">
import {openHouseTest} from '/house-test/host.js';import{createWorldRecords}from'/house-test/world-records.js';
const make=${makeFixture.toString()};window.fixture=make();window.owner=fixture.owner;
document.querySelector('#open').onclick=()=>{const account=owner;const authorized=()=>owner===account;const records=createWorldRecords({client:fixture.client,owner:account,authorized,getFriends:()=>[{id:'friend-a',nick:'오랜 친구'}],prepareMedia:async file=>({body:file,thumb:file,kind:file.type.startsWith('video/')?'video':'image',mime:file.type})});openHouseTest({owner:account,authorized,records});};</script>`;
(async()=>{
 const browser=await chromium.launch({headless:true,executablePath:process.env.PLAYWRIGHT_CHROMIUM_EXECUTABLE_PATH||undefined,args:['--no-sandbox']});
 try{
  const context=await browser.newContext({viewport:{width:390,height:844}});await context.route('**/*',route=>{const u=new URL(route.request().url());if(u.hostname!=='fixture.test')return route.abort();if(u.pathname==='/fixture')return route.fulfill({contentType:'text/html',body:fixture});if(u.pathname==='/proof.ttf'&&process.env.HOUSE_RECORDS_PROOF_FONT)return route.fulfill({path:process.env.HOUSE_RECORDS_PROOF_FONT});const file=path.resolve(root,'.'+u.pathname);return file.startsWith(root+path.sep)&&fs.existsSync(file)?route.fulfill({path:file}):route.abort();});
  if(process.env.HOUSE_RECORDS_PROOF_FONT)await context.addInitScript(()=>document.addEventListener('DOMContentLoaded',()=>{const s=document.createElement('style');s.textContent='@font-face{font-family:AlbumProof;src:url(/proof.ttf)}html,body,button,input,textarea,select{font-family:AlbumProof,sans-serif!important}';document.head.append(s);},{once:true}));
  const page=await context.newPage(),errors=[];page.on('pageerror',e=>errors.push(e.message));await page.goto('https://fixture.test/fixture');await page.locator('#open').click();await page.frameLocator('iframe').getByRole('tab',{name:'전체',exact:true}).waitFor();let f=page.frames().find(x=>x.url().includes('/house-test/index.html'));
  await f.locator('[data-cloud-record-id="old-video"]').waitFor();assert.equal(await f.locator('[data-cloud-record-id]').count(),3,'all includes existing photos and video');
  assert.deepEqual(await f.getByRole('tab').allTextContents(),['전체','노트','앨범','비디오']);
  for(const width of [320,390,1280]){
   await page.setViewportSize({width,height:844});
   const layout=await f.evaluate(()=>({rows:[...document.querySelectorAll('[data-cloud-record-id]')].map(el=>{const row=el.getBoundingClientRect(),text=el.querySelector('.record-copy').getBoundingClientRect(),thumb=el.querySelector('.record-preview').getBoundingClientRect();return {height:row.height,textRight:text.right,thumbLeft:thumb.left,thumbWidth:thumb.width};}),foldersVisible:[...document.querySelectorAll('[data-folder-id]')].some(el=>el.getClientRects().length),tabHeight:document.querySelector('[role=tab]').getBoundingClientRect().height,tabsFit:[...document.querySelectorAll('[role=tab]')].every(el=>el.scrollWidth<=el.clientWidth),overflow:document.documentElement.scrollWidth>innerWidth}));
   assert.equal(layout.overflow,false);assert(!layout.foldersVisible&&layout.tabHeight>=44&&layout.tabsFit);assert(layout.rows.every(row=>row.height===layout.rows[0].height&&row.height<=128&&row.textRight<row.thumbLeft&&row.thumbWidth===76),'equal rows, left text, small right thumbnails');
   if(process.env.HOUSE_ALBUM_PROOF_DIR){fs.mkdirSync(process.env.HOUSE_ALBUM_PROOF_DIR,{recursive:true});await f.evaluate(()=>document.fonts.ready);await page.screenshot({path:path.join(process.env.HOUSE_ALBUM_PROOF_DIR,`home-list-${width}.png`)});}
  }
  await page.setViewportSize({width:390,height:844});
  await f.getByRole('button',{name:'동영상 크게 보기',exact:true}).click();await f.locator('dialog video').waitFor();assert.equal(await f.locator('dialog img').count(),0,'mixed feed video opens as video');await f.locator('dialog button').click();
  assert.equal(await f.getByRole('button',{name:'+ 새폴더',exact:true}).count(),0,'all has no folder creation');
  await f.getByRole('tab',{name:'앨범',exact:true}).click();await f.locator('[data-folder-id="old-folder"]').click();await f.locator('[data-cloud-record-id="old-photo"]').waitFor();await f.getByRole('tab',{name:'비디오',exact:true}).click();await f.locator('[data-cloud-record-id="old-video"]').waitFor();assert.equal(await f.locator('[data-folder-id="old-folder"]').count(),0,'photo folders do not appear among video folders');
  await f.getByRole('tab',{name:'앨범',exact:true}).click();assert.equal(await f.locator('[data-folder-id="old-folder"]').getAttribute('aria-pressed'),'true','each category remembers its own folder');await f.locator('[data-folder-id="all"]').click();await f.getByRole('tab',{name:'전체',exact:true}).click();await f.locator('[data-cloud-record-id="old-video"]').waitFor();
  if(process.env.HOUSE_ALBUM_PROOF_DIR){fs.mkdirSync(process.env.HOUSE_ALBUM_PROOF_DIR,{recursive:true});await f.evaluate(()=>document.fonts.ready);await page.screenshot({path:path.join(process.env.HOUSE_ALBUM_PROOF_DIR,'home-list-all-mobile.png')});}
  await f.evaluate(async()=>{const store=await import('/house-test/record-media-store.js');await store.addRecordMedia('member-a','photo',[new File(['local'],'새 화면에 보관한 사진.jpg',{type:'image/jpeg'})]);});
  const cloud=f.locator('.cloud-records');await f.getByRole('tab',{name:'앨범',exact:true}).click();await cloud.locator('[data-cloud-record-id="old-photo"]').waitFor();assert.equal(await cloud.locator('.record-card').count(),2);assert.equal(await cloud.getByText('다른 계정 사진').count(),0);
  assert.equal(await f.locator('.local-records,.record-diary-editor').count(),0,'connected view has no legacy editors');assert.equal(await f.getByText('새 화면에 보관한 사진.jpg',{exact:true}).count(),0);assert.equal(await f.evaluate(async()=>{const store=await import('/house-test/record-media-store.js');return (await store.listRecordMedia('member-a','photo')).some(row=>row.name==='새 화면에 보관한 사진.jpg');}),true,'hidden device media remains stored');
  await cloud.getByRole('button',{name:'사진 크게 보기'}).first().click();await f.locator('dialog img').waitFor();await page.keyboard.press('Escape');await f.locator('dialog').waitFor({state:'detached'});assert.equal(await page.locator('iframe').count(),1,'viewer Escape leaves the house open');
  await f.locator('[data-folder-id="note-folder"]').click();await cloud.locator('[data-cloud-record-id="old-photo"]').waitFor({state:'detached'});await cloud.locator('[data-cloud-record-id="note-photo"]').waitFor();assert.equal(await cloud.locator('.record-card').count(),1);assert.match(await cloud.textContent(),/나만 보기/);
  await f.getByRole('button',{name:'+ 새폴더',exact:true}).click();await cloud.getByLabel('폴더 이름',{exact:true}).fill('여행');await cloud.getByRole('combobox',{name:'폴더 공개범위'}).selectOption('chosen');await cloud.getByLabel('오랜 친구',{exact:true}).check();await cloud.getByRole('button',{name:'폴더 만들기',exact:true}).click();await cloud.getByRole('status').filter({hasText:'폴더를 저장'}).waitFor();assert.deepEqual(await page.evaluate(()=>fixture.db.media_folders.at(-1).allowed),['friend-a']);
  await f.getByRole('button',{name:'우리집 설정',exact:true}).click();await f.getByRole('button',{name:'폴더 관리',exact:true}).click();await f.getByRole('button',{name:'앨범 폴더',exact:true}).click();await f.getByRole('button',{name:'여행 폴더 수정',exact:true}).click();await cloud.getByRole('combobox',{name:'폴더 공개범위'}).selectOption('me');await cloud.getByRole('button',{name:'폴더 저장',exact:true}).click();await cloud.getByRole('status').filter({hasText:'폴더를 저장'}).waitFor();
  await f.locator('[data-folder-id="all"]').click();await cloud.locator('[data-cloud-record-id="old-photo"]').waitFor();await cloud.locator('[data-cloud-record-id="old-photo"]').getByRole('button',{name:'설정',exact:true}).click();await cloud.getByRole('combobox',{name:'파일 폴더'}).selectOption('');await cloud.getByRole('combobox',{name:'파일 공개범위',exact:true}).selectOption('me');await cloud.getByRole('button',{name:'파일 설정 저장',exact:true}).click();await cloud.getByRole('status').filter({hasText:'설정을 저장'}).waitFor();assert.equal(await page.evaluate(()=>fixture.db.media.find(x=>x.id==='old-photo').visibility),'me');
  await f.locator('[data-folder-id="note-folder"]').click();await cloud.getByText('오쭈다노트에 올린 사진',{exact:true}).waitFor();
  await cloud.locator('input[type=file]').setInputFiles({name:'새사진.webp',mimeType:'image/webp',buffer:fs.readFileSync(path.join(root,'house-test/assets/entry-house-v1.webp'))});await cloud.getByRole('status').filter({hasText:'1개를 앨범에 저장'}).waitFor();assert.equal(await page.evaluate(()=>fixture.db.media.at(-1).folder_id),'note-folder');assert.equal(await page.evaluate(()=>fixture.db.media.at(-1).visibility),'me');
  await page.evaluate(()=>fixture.state.fail='media');await cloud.getByRole('button',{name:'새로고침',exact:true}).click();await cloud.getByRole('status').filter({hasText:'연결을 확인'}).waitFor();await page.evaluate(()=>fixture.state.fail=null);await cloud.getByRole('button',{name:'새로고침',exact:true}).click();await f.waitForFunction(()=>!document.querySelector('.cloud-records .record-status').textContent);
  await page.evaluate(()=>fixture.db.media.push({id:'new-note',user_id:'member-a',type:'image',path:'member-a/note-new.jpg',thumb_path:'member-a/note-new-thumb.jpg',caption:'노트에서 자동 저장한 사진',visibility:'me',folder_id:'note-folder',created_at:'2026-10-05'}));await cloud.getByRole('button',{name:'새로고침',exact:true}).click();await cloud.locator('[data-cloud-record-id="new-note"]').waitFor();
  for(const size of [{width:320,height:568},{width:1280,height:900}]){await page.setViewportSize(size);assert.equal(await f.evaluate(()=>document.documentElement.scrollWidth<=innerWidth&&document.querySelector('#panel-body').scrollWidth<=document.querySelector('#panel-body').clientWidth),true);}
  await page.setViewportSize({width:390,height:844});if(process.env.HOUSE_ALBUM_PROOF_DIR){fs.mkdirSync(process.env.HOUSE_ALBUM_PROOF_DIR,{recursive:true});await f.evaluate(()=>document.fonts.ready);await page.screenshot({path:path.join(process.env.HOUSE_ALBUM_PROOF_DIR,'restored-album-mobile.png')});}
  await f.locator('[data-folder-id="all"]').click();await f.getByRole('tab',{name:'비디오',exact:true}).click();await cloud.locator('[data-cloud-record-id="old-video"]').waitFor();assert.equal(await f.locator('video').count(),0,'videos do not download or play on gallery entry');
  await f.getByRole('tab',{name:'앨범',exact:true}).click();await f.getByRole('tab',{name:'노트',exact:true}).click();await cloud.locator('.record-gallery .record-empty').waitFor();assert.equal(await f.locator('#diary').count(),0,'legacy editor is absent from connected records');assert.equal(await cloud.getByRole('button',{name:'＋ 글쓰기',exact:true}).isVisible(),true);assert.equal(await f.locator('.cloud-records .record-gallery').isVisible(),true);
  await page.evaluate(()=>owner='member-b');await page.locator('iframe').waitFor({state:'detached'});assert.deepEqual(errors,[]);
  console.log('PASS: cloud records with legacy storage preserved, folder privacy editor, uploads, refreshed Note photos, viewer, account close, lazy media and responsive layout');
 }finally{await browser.close();}
})().catch(error=>{console.error(error);process.exitCode=1;});
