const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
const {chromium}=require('playwright'),root=path.resolve(__dirname,'..');
const proof=process.env.HOUSE_OPENING_PROOF_DIR||path.resolve(root,'../house-opening-proof'),proofFont=process.env.HOUSE_OPENING_PROOF_FONT;
const fixture=`<!doctype html><button id="open">우리집</button><script type="module">import{openHouseTest}from'/house-test/host.js';window.houseOwner='opening-default';document.querySelector('#open').onclick=()=>{const owner=houseOwner;openHouseTest({owner,authorized:()=>houseOwner===owner});};</script>`;
const cameraMetrics=()=>{const view=document.querySelector('#viewport').getBoundingClientRect(),room=document.querySelector('.room.selected').getBoundingClientRect(),scale=room.width/1507,left=room.left+12*scale,right=room.right-12*scale;return {width:view.width,height:view.height,roomWidth:right-left,leftGap:left-view.left,rightGap:view.right-right,centerOffset:(left+right-view.left-view.right)/2};};
(async()=>{
 const browser=await chromium.launch({headless:true,executablePath:process.env.PLAYWRIGHT_CHROMIUM_EXECUTABLE_PATH||undefined,args:['--no-sandbox']});
 try{
  fs.mkdirSync(proof,{recursive:true});const context=await browser.newContext({viewport:{width:390,height:844}}),requests=[],errors=[];let delayShelf=true,failCarpet=false;
  await context.route('**/*',async route=>{
   const u=new URL(route.request().url());if(u.hostname!=='fixture.test')return route.abort();requests.push(u.pathname);
   if(u.pathname==='/fixture')return route.fulfill({contentType:'text/html',body:fixture});
   if(proofFont&&u.pathname==='/_font.otf')return route.fulfill({contentType:'font/otf',path:proofFont});
   if(failCarpet&&u.pathname.endsWith('/carpet-v1.runtime.json'))return route.fulfill({status:503,contentType:'text/plain',body:'fixture unavailable'});
   if(delayShelf&&/\/bookshelf-(?:left|center|right)-v2\.webp$/.test(u.pathname))await new Promise(resolve=>setTimeout(resolve,180));
   const file=path.resolve(root,'.'+u.pathname);return file.startsWith(root+path.sep)&&fs.existsSync(file)&&fs.statSync(file).isFile()?route.fulfill({path:file}):route.abort();
  });
  if(proofFont)await context.addInitScript(()=>document.addEventListener('DOMContentLoaded',()=>{const style=document.createElement('style');style.textContent='@font-face{font-family:OpeningProof;src:url(/_font.otf)}html,body,button,input,textarea{font-family:OpeningProof,sans-serif!important}';document.head.append(style);},{once:true}));
  const page=await context.newPage();page.on('pageerror',e=>{errors.push(e.message);console.error('PAGE ERROR:',e.message);});await page.goto('https://fixture.test/fixture');
  const readSave=()=>page.evaluate(()=>localStorage.getItem('ojjuda-house-playtest-v1:'+houseOwner));
  const open=async()=>{await page.locator('#open').click();await page.frameLocator('iframe[title="우리집"]').locator('.room.selected').waitFor({state:'visible'});return page.frames().find(f=>/\/house-test\/index\.html/.test(f.url()));};
  const close=async f=>{await f.locator('#exit').click();await page.waitForFunction(()=>!document.querySelector('iframe'));};
  const settle=f=>f.evaluate(()=>new Promise(resolve=>requestAnimationFrame(()=>requestAnimationFrame(resolve))));
  const ready=async f=>{await f.waitForFunction(()=>[...document.querySelectorAll('.furniture')].every(n=>n.dataset.renderState==='ready'));await f.evaluate(()=>document.fonts.ready);await settle(f);};
  const assertWidth=async(f,label)=>{const m=await f.evaluate(cameraMetrics);assert(Math.abs(m.centerOffset)<.75,label+': room center aligns with viewport center');assert(m.leftGap>=-.5&&m.rightGap>=-.5,label+': neither side is cropped');assert(m.leftGap<=20.5&&m.rightGap<=20.5,label+': the room fills the available width with only a narrow border');return m;};
  const runtimeRequests=from=>requests.slice(from).filter(p=>p.endsWith('.runtime.json'));
  const measurements={};let start=requests.length,f=await open();measurements.initial=await assertWidth(f,'initial mobile frame');await ready(f);measurements.afterAsyncPaint=await assertWidth(f,'after asynchronous artwork and font loading');assert.equal(await f.locator('.furniture').count(),2);assert.deepEqual(await f.locator('nav [data-tab]').evaluateAll(nodes=>nodes.map(n=>n.dataset.tab)),['diary','room']);assert.equal(await f.locator('nav [data-tab="room"]').getAttribute('aria-pressed'),'true','room decorating remains selected initially');assert.deepEqual(runtimeRequests(start),[],'a default room does not download unused table, carpet or chair runtimes');
  await page.screenshot({path:path.join(proof,'opening-mobile.png')});delayShelf=false;
  for(const viewport of [{width:1280,height:960},{width:844,height:390}]){await page.setViewportSize(viewport);await settle(f);measurements[viewport.width+'x'+viewport.height]=await assertWidth(f,'layout resize '+viewport.width+'x'+viewport.height);await page.screenshot({path:path.join(proof,'opening-'+viewport.width+'x'+viewport.height+'.png')});}
  await f.locator('#zoom-in').click();await f.locator('#home-view').click();await assertWidth(f,'current-room reset');await close(f);const warmSaved=await readSave();start=requests.length;f=await open();await ready(f);await assertWidth(f,'warm reopen');assert.deepEqual(runtimeRequests(start),[]);assert.equal(await readSave(),warmSaved,'opening the saved default room does not rewrite it');
  // Selecting a previously unused object may fetch its artwork, but must not
  // fetch unrelated objects or write a placement before the user accepts it.
  start=requests.length;await f.getByRole('button',{name:'의자 놓기',exact:true}).click();await f.locator('[data-furniture="chair"][data-render-state="ready"]').waitFor();assert.deepEqual(runtimeRequests(start).map(p=>path.basename(p)),['chair-v1.runtime.json']);await f.getByRole('button',{name:'취소',exact:true}).click();assert.equal(await readSave(),warmSaved);
  start=requests.length;await f.getByRole('button',{name:'의자 놓기',exact:true}).click();await f.locator('[data-furniture="chair"][data-render-state="ready"]').waitFor();assert.deepEqual(runtimeRequests(start),[],'ready artwork is reused for the second selection');await f.getByRole('button',{name:'취소',exact:true}).click();await close(f);
  await page.evaluate(()=>{houseOwner='opening-removed';localStorage.setItem('ojjuda-house-playtest-v1:'+houseOwner,JSON.stringify({version:13,rooms:[{x:0,y:0,decor:false,curtains:false,shelf:null,furniture:{chair:null,carpet:null,'coffee-table':null}}],diary:'회수한 가구'}));});
  const removedSaved=await readSave();start=requests.length;f=await open();assert.deepEqual(runtimeRequests(start),[],'removed furniture does not trigger runtime downloads');assert.equal(await f.locator('.furniture').count(),0);assert.equal(await readSave(),removedSaved);await close(f);
  const runtime=JSON.parse(fs.readFileSync(path.join(root,'house-test/assets/chair-v1.runtime.json')));runtime.name='보존할 제작 의자';
  const customId=await page.evaluate(async runtime=>{window.houseOwner='opening-custom';const {saveMadeItem}=await import('/house-test/custom-store.js?v=20261003-lamp1');return (await saveMadeItem(houseOwner,runtime,{format:'ojjuda-furniture-set',complete:true})).id;},runtime);
  const saved={version:11,rooms:[{x:0,y:0,decor:true,curtains:true,shelf:{direction:'right',x:9,y:1.5},furniture:{desk:{direction:'right',x:9,y:3.5},[customId]:{direction:'left',x:7.5,y:4.5}}},{x:1,y:0,decor:false,curtains:false,shelf:null,furniture:{carpet:{direction:'center',x:1,y:3}}}],diary:'다른 방 카펫과 제작 의자와 기록 보존'};
  await page.evaluate(saved=>localStorage.setItem('ojjuda-house-playtest-v1:'+houseOwner,JSON.stringify(saved)),saved);let stored=await readSave();start=requests.length;f=await open();await ready(f);assert.equal(await f.locator(`[data-furniture="${customId}"]`).count(),1);assert.equal(await f.locator('.room[data-room="1:0"] [data-furniture="carpet"]').count(),1,'artwork used in another owned room is loaded before restoring that room');assert.deepEqual(runtimeRequests(start).map(p=>path.basename(p)),['carpet-v1.runtime.json']);assert.equal(await readSave(),stored);await close(f);assert.deepEqual(JSON.parse(await readSave()),{...saved,version:13},'closing may migrate the schema while preserving all custom IDs, room placements and diary');stored=await readSave();
  start=requests.length;f=await open();await ready(f);assert.equal(await f.locator(`[data-furniture="${customId}"]`).count(),1);assert.equal(await readSave(),stored);assert.deepEqual(runtimeRequests(start).map(p=>path.basename(p)),['carpet-v1.runtime.json']);await close(f);
  failCarpet=true;await page.locator('#open').click();await page.frameLocator('iframe[title="우리집"]').locator('#locked p').filter({hasText:'기존 배치는 보존'}).waitFor();assert.equal(await readSave(),stored,'a required saved runtime failing to load cannot erase saved custom furniture or rooms');await page.getByRole('button',{name:'우리집 닫기',exact:true}).click();await page.waitForFunction(()=>!document.querySelector('iframe'));assert.equal(await readSave(),stored);assert.deepEqual(errors,[]);
  fs.writeFileSync(path.join(proof,'house-opening-verification.json'),JSON.stringify({measurements,defaultColdAndWarmSkipUnusedRuntimes:true,selectedRuntimeOnlyAndReused:true,savedCustomAndOtherRoomsPreserved:true,requiredArtworkFailurePreservesSave:true,errors},null,2));
  console.log('HOUSE OPENING PASS: centered width fit after paint/resize, default cold/warm load, on-demand art, preserved custom rooms and safe load failure');
 }finally{await browser.close();}
})().catch(error=>{console.error(error);process.exitCode=1;});
