const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
const {chromium}=require('playwright'),makeFixture=require('./fixtures/house-album.cjs'),root=path.resolve(__dirname,'..');
const fixture=`<!doctype html><meta charset="utf-8"><button id="open">우리집</button><script type="module">
import {openHouseTest} from '/house-test/host.js';import{createWorldRecords}from'/house-test/world-records.js';
const make=${makeFixture.toString()};window.fixture=make();window.owner=fixture.owner;
document.querySelector('#open').onclick=()=>{const account=owner;const authorized=()=>owner===account;const records=createWorldRecords({client:fixture.client,owner:account,authorized,getFriends:()=>[{id:'friend-a',nick:'오랜 친구'}],prepareMedia:async file=>({body:file,thumb:file,kind:file.type.startsWith('video/')?'video':'image',mime:file.type})});openHouseTest({owner:account,authorized,records});};</script>`;
(async()=>{
 const browser=await chromium.launch({headless:true,executablePath:process.env.PLAYWRIGHT_CHROMIUM_EXECUTABLE_PATH||undefined,args:['--no-sandbox']});
 try{
  const context=await browser.newContext({viewport:{width:390,height:844}});await context.route('**/*',route=>{const u=new URL(route.request().url());if(u.hostname!=='fixture.test')return route.abort();if(u.pathname==='/fixture')return route.fulfill({contentType:'text/html',body:fixture});if(u.pathname==='/proof.ttf'&&process.env.HOUSE_RECORDS_PROOF_FONT)return route.fulfill({path:process.env.HOUSE_RECORDS_PROOF_FONT});const file=path.resolve(root,'.'+u.pathname);return file.startsWith(root+path.sep)&&fs.existsSync(file)?route.fulfill({path:file}):route.abort();});
  if(process.env.HOUSE_RECORDS_PROOF_FONT)await context.addInitScript(()=>document.addEventListener('DOMContentLoaded',()=>{const s=document.createElement('style');s.textContent='@font-face{font-family:PostProof;src:url(/proof.ttf)}html,body,button,input,textarea,select{font-family:PostProof,sans-serif!important}';document.head.append(s);},{once:true}));
  const page=await context.newPage(),errors=[];page.on('pageerror',e=>errors.push(e.message));await page.goto('https://fixture.test/fixture');await page.locator('#open').click();await page.frameLocator('iframe').getByRole('tab',{name:'전체',exact:true}).waitFor();let f=page.frames().find(x=>x.url().includes('/house-test/index.html'));await f.locator('[data-cloud-record-id="old-video"]').waitFor();let cloud=f.locator('.cloud-records');
  const status=text=>cloud.getByRole('status').filter({hasText:text}).waitFor(),write=()=>cloud.getByRole('button',{name:'＋ 글쓰기',exact:true}).click();
  await write();await cloud.getByLabel('게시판 글',{exact:true}).fill('산책하고 돌아와 남기는 첫 기록\n차 한 잔으로 마무리.');assert.equal(await cloud.getByRole('combobox',{name:'글 공개범위',exact:true}).inputValue(),'me');
  await f.getByRole('tab',{name:'사진',exact:true}).click();await f.locator('[data-cloud-record-id="old-photo"]').waitFor();await f.getByRole('tab',{name:'게시판',exact:true}).click();await cloud.locator('.record-empty').waitFor();await write();assert.match(await cloud.getByLabel('게시판 글',{exact:true}).inputValue(),/산책하고/,'draft survives category switches');
  await page.evaluate(()=>fixture.state.fail='rpc');await cloud.getByRole('button',{name:'게시판에 저장',exact:true}).click();await status('연결을 확인');assert.match(await cloud.getByLabel('게시판 글',{exact:true}).inputValue(),/첫 기록/);assert.equal(await page.evaluate(()=>fixture.db.house_posts.length),0);
  await page.evaluate(()=>fixture.state.fail=null);await cloud.getByRole('button',{name:'게시판에 저장',exact:true}).click();await status('글을 계정에 저장');const first=await page.evaluate(()=>fixture.db.house_posts[0].id);assert.equal(await cloud.locator('[data-record-type="text"]').count(),1);
  await write();await cloud.getByLabel('게시판 글',{exact:true}).fill('두 번째 글 — 친구와 함께한 하루');await cloud.getByRole('combobox',{name:'글 폴더',exact:true}).selectOption('old-folder');assert.equal(await cloud.getByRole('combobox',{name:'글 공개범위',exact:true}).isVisible(),false);await cloud.getByRole('button',{name:'게시판에 저장',exact:true}).click();await status('글을 계정에 저장');const second=await page.evaluate(()=>fixture.db.house_posts[1].id);assert.equal(await page.evaluate(()=>fixture.db.house_posts.length),2);
  await f.locator('[data-folder-id="all"]').click();await f.waitForFunction(()=>document.querySelectorAll('[data-record-type="text"]').length===2);await cloud.locator(`[data-cloud-record-id="${first}"]`).getByRole('button',{name:/글 보기:/}).click();const viewer=f.getByRole('dialog',{name:'게시판 글 보기'});await viewer.waitFor();assert.match(await viewer.textContent(),/차 한 잔으로 마무리/);await page.keyboard.press('Escape');await viewer.waitFor({state:'detached'});assert.equal(await page.locator('iframe').count(),1);
  await cloud.locator(`[data-cloud-record-id="${first}"]`).getByRole('button',{name:'설정',exact:true}).click();await cloud.getByLabel('게시판 글',{exact:true}).fill('수정한 첫 기록');await cloud.getByRole('button',{name:'글 수정 저장',exact:true}).click();await status('글을 계정에 저장');assert.equal(await page.evaluate(id=>fixture.db.house_posts.find(x=>x.id===id).body,first),'수정한 첫 기록');
  await f.locator('[data-folder-id="all"]').click();await f.getByRole('tab',{name:'전체',exact:true}).click();await f.locator('[data-cloud-record-id="old-video"]').waitFor();assert.equal(await cloud.locator('[data-cloud-record-id]').count(),5);
  for(const width of [320,390,1280]){await page.setViewportSize({width,height:844});assert.equal(await f.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);assert.equal(await cloud.locator('[data-cloud-record-id]').evaluateAll(els=>els.every(el=>el.getBoundingClientRect().height===112)),true);}
  await page.setViewportSize({width:390,height:844});if(process.env.HOUSE_POSTS_PROOF_DIR){fs.mkdirSync(process.env.HOUSE_POSTS_PROOF_DIR,{recursive:true});await f.evaluate(()=>document.fonts.ready);await page.screenshot({path:path.join(process.env.HOUSE_POSTS_PROOF_DIR,'posts-feed.png')});}
  const gear=()=>f.getByRole('button',{name:'우리집 설정',exact:true}).click();await gear();await f.getByRole('button',{name:'게시물 선택·이동',exact:true}).click();await cloud.locator(`[data-cloud-record-id="${second}"]`).getByRole('checkbox').check();await cloud.locator('[data-cloud-record-id="old-video"]').getByRole('checkbox').check();await cloud.getByRole('combobox',{name:'선택한 게시물을 옮길 폴더'}).selectOption('note-folder');await cloud.getByRole('button',{name:'선택한 게시물 이동',exact:true}).click();await cloud.getByRole('button',{name:'이동하기',exact:true}).click();await status('2개 게시물을 옮겼어요');assert.equal(await page.evaluate(id=>fixture.db.house_posts.find(x=>x.id===id).folder_id,second),'note-folder');
  await cloud.locator(`[data-cloud-record-id="${second}"]`).getByRole('checkbox').check();await cloud.locator('[data-cloud-record-id="old-video"]').getByRole('checkbox').check();await cloud.getByRole('button',{name:'선택한 게시물 휴지통으로',exact:true}).click();await cloud.getByRole('button',{name:'취소',exact:true}).click();assert.equal(await page.evaluate(()=>fixture.db.house_media_trash.length),0);
  await cloud.getByRole('button',{name:'선택한 게시물 휴지통으로',exact:true}).click();await page.evaluate(()=>fixture.state.fail='rpc');await cloud.getByRole('button',{name:'휴지통으로 보내기',exact:true}).click();await status('연결을 확인');assert.equal(await cloud.locator('.record-selection-count').textContent(),'2개 선택');assert.equal(await page.evaluate(()=>fixture.db.house_media_trash.length),0);
  await page.evaluate(()=>fixture.state.fail=null);await cloud.getByRole('button',{name:'휴지통으로 보내기',exact:true}).click();await status('휴지통으로 옮겼어요');assert.equal(await cloud.locator(`[data-cloud-record-id="${second}"]`).count(),0);assert.equal(await page.evaluate(()=>fixture.db.house_media_trash.length),1);
  await gear();await f.getByRole('button',{name:'휴지통',exact:true}).click();await cloud.locator('[data-cloud-record-id="old-video"]').waitFor();assert.equal(await cloud.locator('[data-cloud-record-id]').count(),2);assert.equal(await f.locator('.record-folders').isVisible(),false);assert.equal(await f.locator('.local-records').isVisible(),false);assert.equal(await cloud.getByRole('button',{name:'＋ 글쓰기',exact:true}).isVisible(),false);
  if(process.env.HOUSE_POSTS_PROOF_DIR)await page.screenshot({path:path.join(process.env.HOUSE_POSTS_PROOF_DIR,'posts-trash.png')});
  await cloud.locator('[data-cloud-record-id="old-video"]').getByRole('button',{name:'동영상 크게 보기',exact:true}).click();await f.locator('dialog video').waitFor();await page.keyboard.press('Escape');
  await cloud.locator('[data-cloud-record-id="old-video"]').getByRole('button',{name:'복원',exact:true}).click();await cloud.getByRole('button',{name:'취소',exact:true}).click();assert.equal(await page.evaluate(()=>fixture.db.house_media_trash.length),1);
  await cloud.locator('[data-cloud-record-id="old-video"]').getByRole('button',{name:'복원',exact:true}).click();await page.evaluate(()=>fixture.state.fail='rpc');await cloud.getByRole('button',{name:'복원하기',exact:true}).click();await status('연결을 확인');assert.equal(await page.evaluate(()=>fixture.db.house_media_trash.length),1);await page.evaluate(()=>fixture.state.fail=null);await cloud.getByRole('button',{name:'복원하기',exact:true}).click();await status('미분류·나만 보기로 복원');assert.deepEqual(await page.evaluate(()=>{const x=fixture.db.media.find(x=>x.id==='old-video');return [x.path,x.folder_id,x.visibility];}),['member-a/movie.mp4',null,'me']);
  await cloud.locator(`[data-cloud-record-id="${second}"]`).getByRole('button',{name:'복원',exact:true}).click();await cloud.getByRole('button',{name:'복원하기',exact:true}).click();await status('미분류·나만 보기로 복원');assert.equal(await cloud.locator('[data-cloud-record-id]').count(),0);assert.equal(await page.evaluate(()=>fixture.calls.some(x=>x.remove)),false,'trash and restore never remove a stored file');
  await cloud.getByRole('button',{name:'기록으로 돌아가기',exact:true}).click();await cloud.locator('[data-cloud-record-id="note-photo"]').waitFor();await f.locator('[data-folder-id="all"]').click();await f.waitForFunction(()=>document.querySelectorAll('[data-cloud-record-id]').length===5);
  await page.evaluate(()=>{owner='member-b';fixture.state.owner=owner;});await page.locator('iframe').waitFor({state:'detached'});await page.locator('#open').click();await page.frameLocator('iframe').getByRole('tab',{name:'전체',exact:true}).waitFor();f=page.frames().find(x=>x.url().includes('/house-test/index.html'));cloud=f.locator('.cloud-records');await cloud.locator('[data-cloud-record-id="other-photo"]').waitFor();assert.equal(await cloud.locator('[data-record-type="text"]').count(),0,'another account cannot load saved posts');
  await page.evaluate(()=>{owner='member-a';fixture.state.owner=owner;});await page.locator('iframe').waitFor({state:'detached'});await page.locator('#open').click();await page.frameLocator('iframe').getByRole('tab',{name:'전체',exact:true}).waitFor();f=page.frames().find(x=>x.url().includes('/house-test/index.html'));await f.locator(`[data-cloud-record-id="${second}"]`).waitFor();assert.equal(await f.locator('[data-record-type="text"]').count(),2,'saved posts survive house closure and account switching');await f.getByRole('tab',{name:'게시판',exact:true}).click();await f.locator('.record-diary-editor summary').click();await f.locator('#diary').fill('예전에 이 기기에 보관한 글');await f.getByRole('button',{name:'기록 저장',exact:true}).click();await f.getByRole('tab',{name:'전체',exact:true}).click();await f.locator('[data-cloud-record-id]').first().waitFor();await f.getByRole('button',{name:'이 기기 글을 게시판에 복사',exact:true}).click();assert.equal(await f.getByLabel('게시판 글',{exact:true}).inputValue(),'예전에 이 기기에 보관한 글');await f.getByRole('button',{name:'게시판에 저장',exact:true}).click();await f.locator('.cloud-records').getByRole('status').filter({hasText:'글을 계정에 저장'}).waitFor();assert.equal(await f.locator('#diary').inputValue(),'예전에 이 기기에 보관한 글','copy never erases the legacy original');assert.equal(await page.evaluate(()=>fixture.db.house_posts.length),3);assert.deepEqual(errors,[]);
  console.log('PASS: multiple account posts, draft/error preservation, edit/full text, equal mobile rows, mixed moves/trash, cancel/retry/private restore, original files and account isolation');
 }finally{await browser.close();}
})().catch(e=>{console.error(e);process.exitCode=1;});
