const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),{randomUUID}=require('node:crypto'),{PGlite}=require('@electric-sql/pglite');
const root=path.join(__dirname,'..');
(async()=>{const db=new PGlite();const a=randomUUID(),b=randomUUID(),card=randomUUID();
const val=async(q,args=[])=> (await db.query(q,args)).rows[0].v;
const login=async u=>{await db.exec('reset role');await db.query("select set_config('request.jwt.claim.sub',$1,false)",[u||'']);await db.exec('set role '+(u?'authenticated':'anon'));};
try{
 await db.exec(`create role anon;create role authenticated;create schema auth;create schema ojjuda_note_internal;create schema ojjuda_note;
 create table auth.users(id uuid primary key);insert into auth.users values('${a}'),('${b}');
 create function auth.uid() returns uuid language sql stable as $$select nullif(current_setting('request.jwt.claim.sub',true),'')::uuid$$;
 create function public.is_banned(uuid) returns boolean language sql stable as $$select coalesce(current_setting('test.banned',true),'false')='true'$$;
 create table public.user_private(user_id uuid primary key,coins integer not null check(coins>=0));insert into public.user_private values('${a}',100),('${b}',0);
 create table ojjuda_note_internal.card_visuals(card_id uuid primary key,style jsonb,style_until timestamptz,photo_key text,photo_until timestamptz,updated_at timestamptz default now());
 create table ojjuda_note.cards(id uuid primary key,background_key text);insert into ojjuda_note.cards values('${card}','21');
 grant usage on schema public,auth to anon,authenticated;
 `);
 const sql=fs.readFileSync(path.join(root,'supabase/migrations/20261006032049_ju_shop_entitlements.sql'),'utf8');await db.exec(sql);
 await login(null);await assert.rejects(()=>val('select public.ju_shop_state() as v'),/permission denied/);
 await login(a);await assert.rejects(()=>db.exec('update public.user_private set coins=999'),/permission denied/);
 await assert.rejects(()=>db.exec('select * from ojjuda_shop_internal.entitlements'),/permission denied/);
 const id=randomUUID();let r=await val('select ju_shop_buy($1,$2) as v',['card_stickers',id]);assert.equal(r.spent,5);assert.equal(r.coins,95);
 r=await val('select ju_shop_buy($1,$2) as v',['card_stickers',id]);assert.equal(r.replayed,true);assert.equal(r.coins,95);
 r=await val('select ju_shop_buy($1,$2) as v',['card_stickers',randomUUID()]);assert.equal(r.spent,0);assert.equal(r.coins,95);
 assert.equal((await val('select ju_shop_buy($1,$2) as v',['card_fonts',id])).reason,'request_conflict');
 assert.equal((await val('select ju_shop_buy($1,$2) as v',['not-for-sale',randomUUID()])).reason,'unavailable');
 assert.equal((await val('select ju_shop_equip($1,$2) as v',['frame','profile_flower'])).reason,'not_owned');
 const month=randomUUID();r=await val('select ju_shop_buy($1,$2) as v',['profile_flower',month]);assert.equal(r.spent,5);const expiry=r.expires_at;
 r=await val('select ju_shop_buy($1,$2) as v',['profile_flower',randomUUID()]);assert.equal(r.spent,0);assert.equal(r.expires_at,expiry);
 assert.equal((await val('select ju_shop_equip($1,$2) as v',['frame','profile_flower'])).ok,true);
 assert.equal((await val('select ju_shop_state() as v')).selected.frame,'profile_flower');
 await login(b);assert.equal((await val('select ju_shop_buy($1,$2) as v',['profile_flower',month])).reason,'coins');
 assert.equal((await val('select ju_shop_state() as v')).owned.length,0);
 await db.exec('reset role');await db.query("update ojjuda_shop_internal.entitlements set expires_at=now()-interval '1 second' where user_id=$1 and product='profile_flower'",[a]);
 await login(a);assert.equal((await val('select ju_shop_state() as v')).selected.frame,undefined);
 r=await val('select ju_shop_buy($1,$2) as v',['profile_flower',randomUUID()]);assert.equal(r.spent,5);assert.notEqual(r.expires_at,expiry);
 await db.exec("reset role;select set_config('test.banned','true',false)");await login(a);assert.equal((await val('select ju_shop_buy($1,$2) as v',['card_fonts',randomUUID()])).reason,'banned');
 await db.exec("reset role;select set_config('test.banned','false',false)");
 assert.equal(await val("select ojjuda_note_internal.valid_card_style('{\"shopSticker\":\"heart\"}') as v"),true);
 assert.equal(await val("select ojjuda_note_internal.valid_card_style('{\"shopSticker\":\"<script>\"}') as v"),false);
 await db.query("select set_config('request.jwt.claim.sub',$1,false)",[a]);
 await db.query("select ojjuda_note_internal.upsert_card_style($1,'{\"shopSticker\":\"heart\"}')",[card]);
 await db.query("update ojjuda_note_internal.card_visuals set style_until=now()-interval '1 day' where card_id=$1",[card]);
 assert.equal((await val('select ojjuda_note_internal.card_visual_for($1) as v',[card])).style.shopSticker,'heart');
 await assert.rejects(()=>db.query("select ojjuda_note_internal.upsert_card_style($1,'{\"shopFont\":\"book\"}')",[card]),/Font not owned/);
 await login(a);await val('select ju_shop_buy($1,$2) as v',['card_fonts',randomUUID()]);await db.exec('reset role');
 await db.query("select ojjuda_note_internal.upsert_card_style($1,'{\"shopFont\":\"book\"}')",[card]);
 assert.equal(await val("select style->>'shopFont' as v from ojjuda_note_internal.card_visuals where card_id=$1",[card]),'book');
 assert.ok(await val("select style->>'shopFontUntil' as v from ojjuda_note_internal.card_visuals where card_id=$1",[card]));
 console.log('PASS: atomic balance/grant, duplicate requests, ownership, expiration/renewal, insufficient funds, bans, account isolation and card ownership');
}finally{await db.close();}})().catch(e=>{console.error(e);process.exitCode=1});
