const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const { PGlite } = require('@electric-sql/pglite');

(async () => {
  const db = new PGlite();
  await db.exec(`
    create role anon; create role authenticated;
    create schema auth; create schema ojjuda_note; create schema ojjuda_note_internal;
    create function auth.uid() returns uuid language sql stable as $$
      select nullif(current_setting('request.jwt.claim.sub',true),'')::uuid;
    $$;
    grant usage on schema auth,ojjuda_note to anon,authenticated;
    create table auth.users(id uuid primary key, email text, encrypted_password text,
      raw_user_meta_data jsonb, created_at timestamptz not null default now());
    create table ojjuda_note.cards(id uuid primary key,author_id uuid references auth.users(id));
    create table ojjuda_note_internal.member_gender(user_id uuid primary key references auth.users(id),gender text,updated_at timestamptz);
    create table ojjuda_note_internal.card_gender(card_id uuid primary key references ojjuda_note.cards(id),gender text);
    alter table ojjuda_note_internal.member_gender enable row level security;
    alter table ojjuda_note_internal.card_gender enable row level security;
    insert into auth.users(id,email) values ('00000000-0000-4000-8000-000000000003','existing@example.invalid');
  `);
  const sql = fs.readFileSync(path.join(__dirname,'../supabase/migrations/20260928151422_member_identity_and_card_gender.sql'),'utf8');
  await db.exec(sql);
  await db.exec(`create trigger record_gender after insert on ojjuda_note.cards for each row execute function ojjuda_note_internal.record_card_gender()`);
  const value = async (query,params=[]) => (await db.query(query,params)).rows[0]?.value;
  const parse = (birth,code) => value("select ojjuda_account_internal.parse_identity($1,$2,'01012345678','2026-09-29',true) as value",[birth,code]);
  assert.equal((await parse('110929','3')).age,15);
  assert.equal((await parse('560930','2')).age,69);
  assert.equal((await parse('000229','4')).gender,'female');
  for (const [birth,code] of [['110930','3'],['560929','1'],['990229','1'],['000230','3'],['270101','3'],['000229','5']]) await assert.rejects(()=>parse(birth,code));
  const male='00000000-0000-4000-8000-000000000001', female='00000000-0000-4000-8000-000000000002';
  const signup = (id,meta) => db.query('insert into auth.users(id,email,encrypted_password,raw_user_meta_data) values($1,$2,$3,$4)',[id,`${id}@example.invalid`,'synthetic-non-login-hash',meta]);
  const meta={birth_yymmdd:'000229',gender_code:'3',phone_number:'010-1234-5678',age_15_to_69:true,terms_version:'2026-09-29'};
  await assert.rejects(()=>signup(male,{}));
  const underage=await value("select to_char((now() at time zone 'Asia/Seoul')::date-interval '14 years','YYMMDD') as value");
  await assert.rejects(()=>signup(male,{...meta,birth_yymmdd:underage}));
  await signup(male,meta); await signup(female,{...meta,gender_code:'4'});
  const stored=await value('select raw_user_meta_data as value from auth.users where id=$1',[male]);
  for(const key of ['birth_yymmdd','gender_code','phone_number']) assert.equal(key in stored,false);
  await assert.rejects(()=>db.query("update ojjuda_account_internal.member_identity set gender='female' where user_id=$1",[male]));
  await assert.rejects(()=>db.query("update ojjuda_account_internal.member_identity set birth_date='2001-01-01' where user_id=$1",[male]));
  await db.query("select set_config('request.jwt.claim.sub',$1,false)",[male]);
  await db.exec('set role authenticated');
  let own=await value('select public.get_my_member_identity() as value');
  assert.equal(own.gender,'male'); assert.equal(own.birth_date,'2000-02-29');
  assert.equal(await value("select has_table_privilege('authenticated','ojjuda_account_internal.member_identity','select') as value"),false);
  await assert.rejects(()=>db.query('select * from ojjuda_account_internal.member_identity'));
  await assert.rejects(()=>value("select public.complete_my_member_identity('000229','4','01012345678',true) as value"));
  await assert.rejects(()=>value("select ojjuda_note.set_my_gender('female') as value"));
  assert.equal(await value("select ojjuda_note.set_my_gender('male') as value"),'male');
  assert.equal(await value("select ojjuda_note.set_my_gender('private') as value"),'private');
  await db.exec('reset role');
  await db.query('insert into ojjuda_note.cards values($1,$2)',['00000000-0000-4000-8000-000000000011',male]);
  assert.equal(await value("select gender as value from ojjuda_note_internal.card_gender where card_id='00000000-0000-4000-8000-000000000011'"),'private');
  await db.query("update auth.users set raw_user_meta_data = '{\"gender\":\"female\",\"birth_date\":\"2019-01-01\"}' where id=$1",[male]);
  assert.equal((await value('select public.get_my_member_identity() as value')).gender,'male');
  await db.query("select set_config('request.jwt.claim.sub',$1,false)",[female]);
  assert.equal((await value('select public.get_my_member_identity() as value')).gender,'female');
  await db.query('insert into ojjuda_note.cards values($1,$2)',['00000000-0000-4000-8000-000000000012',female]);
  assert.equal(await value("select gender as value from ojjuda_note_internal.card_gender where card_id='00000000-0000-4000-8000-000000000012'"),'female');
  await db.query("select set_config('request.jwt.claim.sub','00000000-0000-4000-8000-000000000003',false)");
  assert.equal(await value('select public.get_my_member_identity() as value'),null);
  await value("select public.complete_my_member_identity('000229','3','01012345678',true) as value");
  await assert.rejects(()=>value("select public.complete_my_member_identity('000229','4','01012345678',true) as value"));
  assert.equal(await value("select has_function_privilege('anon','public.get_my_member_identity()','execute') as value"),false);
  await db.close();
  console.log('PASS: PostgreSQL migration, server validation, immutable identity, own-only reads, metadata stripping, gender restrictions, existing-member enrollment');
})().catch(error=>{console.error(error);process.exitCode=1;});
