const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const { PGlite } = require('@electric-sql/pglite');

(async () => {
  const db = new PGlite();
  await db.exec(`
    create role anon; create role authenticated;
    create schema auth; create schema ojjuda_note; create schema ojjuda_note_internal;
    create function auth.uid() returns uuid language sql stable as $$
      select nullif(current_setting('request.jwt.claim.sub',true),'')::uuid;
    $$;
    grant usage on schema auth,ojjuda_note to anon,authenticated;
    create table auth.users(id uuid primary key, email text, encrypted_password text,
      raw_user_meta_data jsonb, created_at timestamptz not null default now());
    create table public.profiles(id uuid primary key references auth.users(id) on delete cascade,nickname text);
    create schema cron;
    create function cron.schedule(text,text,text) returns bigint language sql as $$ select 1::bigint $$;
    create table public.app_admins(user_id uuid primary key references auth.users(id));
    create table public.admin_log(admin_id uuid,action text,target_user uuid,target text,detail jsonb,created_at timestamptz default now());
    create function public.is_admin() returns boolean language sql stable security definer set search_path=pg_catalog as $$
      select exists(select 1 from public.app_admins where user_id=auth.uid());
    $$;
    create function public.admin_note(p_action text,p_user uuid,p_target text,p_detail jsonb)
    returns void language sql security definer set search_path=pg_catalog as $$
      insert into public.admin_log(admin_id,action,target_user,target,detail) values(auth.uid(),p_action,p_user,p_target,p_detail);
    $$;
    create table ojjuda_note.cards(id uuid primary key,author_id uuid references auth.users(id));
    create table ojjuda_note_internal.member_gender(user_id uuid primary key references auth.users(id),gender text,updated_at timestamptz);
    create table ojjuda_note_internal.card_gender(card_id uuid primary key references ojjuda_note.cards(id),gender text);
    alter table ojjuda_note_internal.member_gender enable row level security;
    alter table ojjuda_note_internal.card_gender enable row level security;
    insert into auth.users(id,email) values ('00000000-0000-4000-8000-000000000003','existing@example.invalid');
    insert into auth.users(id,email) values ('00000000-0000-4000-8000-000000000004','older@example.invalid');
  `);
  const sql = fs.readFileSync(path.join(__dirname,'../supabase/migrations/20260928151422_member_identity_and_card_gender.sql'),'utf8');
  await db.exec(sql);
  for (const name of ['20260928154555_member_phone_edit.sql','20260928154916_member_admin_identity_edit.sql']) {
    await db.exec(fs.readFileSync(path.join(__dirname,'../supabase/migrations',name),'utf8'));
  }
  await db.exec(fs.readFileSync(path.join(__dirname,'../supabase/migrations/20260928155858_retain_withdrawn_member_accounts_one_month.sql'),'utf8'));
  await db.exec(`create trigger record_gender after insert on ojjuda_note.cards for each row execute function ojjuda_note_internal.record_card_gender()`);
  const value = async (query,params=[]) => (await db.query(query,params)).rows[0]?.value;
  const parse = (birth,code) => value("select ojjuda_account_internal.parse_identity($1,$2,'01012345678','2026-09-29',true) as value",[birth,code]);
  assert.equal((await parse('110929','3')).age,15);
  assert.equal((await parse('560930','2')).age,69);
  assert.equal((await parse('000229','4')).gender,'female');
  for (const [birth,code] of [['110930','3'],['560929','1'],['990229','1'],['000230','3'],['270101','3'],['000229','5']]) await assert.rejects(()=>parse(birth,code));
  const male='00000000-0000-4000-8000-000000000001', female='00000000-0000-4000-8000-000000000002';
  const signup = (id,meta) => db.query('insert into auth.users(id,email,encrypted_password,raw_user_meta_data) values($1,$2,$3,$4)',[id,`${id}@example.invalid`,'synthetic-non-login-hash',meta]);
  const meta={birth_yymmdd:'000229',gender_code:'3',phone_number:'010-1234-5678',age_15_to_69:true,terms_version:'2026-09-29'};
  await assert.rejects(()=>signup(male,{}));
  const underage=await value("select to_char((now() at time zone 'Asia/Seoul')::date-interval '14 years','YYMMDD') as value");
  await assert.rejects(()=>signup(male,{...meta,birth_yymmdd:underage}));
  await signup(male,meta); await signup(female,{...meta,gender_code:'4'});
  const stored=await value('select raw_user_meta_data as value from auth.users where id=$1',[male]);
  for(const key of ['birth_yymmdd','gender_code','phone_number']) assert.equal(key in stored,false);
  await assert.rejects(()=>db.query("update ojjuda_account_internal.member_identity set gender='female' where user_id=$1",[male]));
  await assert.rejects(()=>db.query("update ojjuda_account_internal.member_identity set birth_date='2001-01-01' where user_id=$1",[male]));
  await db.query("select set_config('request.jwt.claim.sub',$1,false)",[male]);
  await db.exec('set role authenticated');
  let own=await value('select public.get_my_member_identity() as value');
  assert.equal(own.gender,'male'); assert.equal(own.birth_date,'2000-02-29');
  const changedPhone=await value("select public.update_my_phone_number('+82 10-2345-6789') as value");
  assert.equal(changedPhone.phone_number,'01023456789');
  assert.equal(changedPhone.birth_date,own.birth_date); assert.equal(changedPhone.gender,own.gender);
  assert.equal(changedPhone.age_at_signup,own.age_at_signup);
  for(const bad of [null,'','abc','010123','+1 01012345678']) await assert.rejects(()=>value('select public.update_my_phone_number($1) as value',[bad]));
  await assert.rejects(()=>value('select public.admin_get_member_identity($1) as value',[female]));
  await assert.rejects(()=>value("select public.admin_reveal_member_phone($1,'긴급 연락이 필요함') as value",[female]));
  await assert.rejects(()=>value("select public.admin_update_member_identity($1,'2001-01-01','male',null) as value",[female]));
  assert.equal(await value("select has_table_privilege('authenticated','ojjuda_account_internal.member_identity','select') as value"),false);
  await assert.rejects(()=>db.query('select * from ojjuda_account_internal.member_identity'));
  await assert.rejects(()=>value("select public.complete_my_member_identity('000229','4','01012345678',true) as value"));
  await assert.rejects(()=>value("select ojjuda_note.set_my_gender('female') as value"));
  assert.equal(await value("select ojjuda_note.set_my_gender('male') as value"),'male');
  assert.equal(await value("select ojjuda_note.set_my_gender('private') as value"),'private');
  await db.exec('reset role');
  await db.query('insert into ojjuda_note.cards values($1,$2)',['00000000-0000-4000-8000-000000000011',male]);
  assert.equal(await value("select gender as value from ojjuda_note_internal.card_gender where card_id='00000000-0000-4000-8000-000000000011'"),'private');
  await db.query("update auth.users set raw_user_meta_data = '{\"gender\":\"female\",\"birth_date\":\"2019-01-01\"}' where id=$1",[male]);
  assert.equal((await value('select public.get_my_member_identity() as value')).gender,'male');
  await db.query("select set_config('request.jwt.claim.sub',$1,false)",[female]);
  assert.equal((await value('select public.get_my_member_identity() as value')).gender,'female');
  await db.query('insert into ojjuda_note.cards values($1,$2)',['00000000-0000-4000-8000-000000000012',female]);
  assert.equal(await value("select gender as value from ojjuda_note_internal.card_gender where card_id='00000000-0000-4000-8000-000000000012'"),'female');
  await db.query("select set_config('request.jwt.claim.sub','00000000-0000-4000-8000-000000000003',false)");
  assert.equal(await value('select public.get_my_member_identity() as value'),null);
  await value("select public.complete_my_member_identity('000229','3','01012345678',true) as value");
  await assert.rejects(()=>value("select public.complete_my_member_identity('000229','4','01012345678',true) as value"));
  assert.equal(await value("select has_function_privilege('anon','public.get_my_member_identity()','execute') as value"),false);
  await db.exec('reset role');
  await db.query('insert into public.app_admins(user_id) values($1)',[male]);
  await db.query("select set_config('request.jwt.claim.sub',$1,false)",[male]);
  await db.exec('set role authenticated');
  let target=await value('select public.admin_get_member_identity($1) as value',[female]);
  assert.equal(target.phone_masked,'010-****-5678'); assert.equal('phone_number' in target,false);
  assert.equal(JSON.stringify(target).includes('01012345678'),false);
  target=await value("select public.admin_update_member_identity($1,'2001-01-01','male',null) as value",[female]);
  assert.equal(target.birth_date,'2001-01-01'); assert.equal(target.gender,'male');
  assert.equal(target.phone_masked,'010-****-5678'); assert.equal('phone_number' in target,false);
  for(const reason of ['', '긴급', null]) await assert.rejects(()=>value('select public.admin_reveal_member_phone($1,$2) as value',[female,reason]));
  const revealed=await value("select public.admin_reveal_member_phone($1,'긴급 연락이 필요한 테스트') as value",[female]);
  assert.equal(revealed.phone_number,'01012345678');
  target=await value("select public.admin_update_member_identity($1,'2001-01-01','male','010-3456-7890') as value",[female]);
  assert.equal(target.phone_masked,'010-****-7890'); assert.equal('phone_number' in target,false);
  await assert.rejects(()=>value("select public.admin_update_member_identity($1,'2099-01-01','male',null) as value",[female]));
  await value("select public.admin_update_member_identity('00000000-0000-4000-8000-000000000004','2000-01-01','female','01012345678') as value");
  for(const signature of ['public.update_my_phone_number(text)','public.admin_get_member_identity(uuid)','public.admin_update_member_identity(uuid,date,text,text)','public.admin_reveal_member_phone(uuid,text)']) {
    assert.equal(await value("select has_function_privilege('anon',$1,'execute') as value",[signature]),false);
  }
  await db.exec('reset role');
  const audit=await db.query("select * from public.admin_log where action='member_phone_emergency'");
  assert.equal(audit.rows.length,1); assert.equal(audit.rows[0].admin_id,male); assert.equal(audit.rows[0].target_user,female);
  assert.equal(audit.rows[0].detail.reason,'긴급 연락이 필요한 테스트');
  assert.equal(JSON.stringify(audit.rows).includes('01012345678'),false);
  assert.equal(await value('select phone_number as value from ojjuda_account_internal.member_identity where user_id=$1',[male]),'01023456789');
  await db.query('delete from public.app_admins where user_id=$1',[male]);
  await assert.rejects(()=>db.query("update ojjuda_account_internal.member_identity set birth_date='2001-01-01' where user_id=$1",[male]));
  await db.exec('set role authenticated');
  await assert.rejects(()=>value('select public.admin_get_member_identity($1) as value',[female]));
  await assert.rejects(()=>value("select public.admin_reveal_member_phone($1,'긴급 연락이 필요한 테스트') as value",[female]));
  await assert.rejects(()=>db.query('select * from ojjuda_account_internal.withdrawn_member_accounts'));
  await db.exec('reset role');
  const leaving='00000000-0000-4000-8000-000000000005', rejoining='00000000-0000-4000-8000-000000000006';
  const leavePhone='01045678901';
  await signup(leaving,{...meta,phone_number:leavePhone});
  await db.query('insert into public.profiles(id,nickname) values($1,$2)',[leaving,'보관검사']);
  await db.query('delete from auth.users where id=$1',[leaving]);
  const archived=(await db.query('select * from ojjuda_account_internal.withdrawn_member_accounts where user_id=$1',[leaving])).rows[0];
  assert.equal(archived.phone_number,leavePhone); assert.equal(archived.nickname,'보관검사');
  assert.equal(new Date(archived.birth_date).toISOString().slice(0,10),'2000-02-29'); assert.equal('encrypted_password' in archived,false);
  assert.equal(await value("select expires_at=(((withdrawn_at at time zone 'Asia/Seoul')+interval '1 month') at time zone 'Asia/Seoul') as value from ojjuda_account_internal.withdrawn_member_accounts where user_id=$1",[leaving]),true);
  assert.equal(await value('select count(*)::int as value from ojjuda_account_internal.member_identity where user_id=$1',[leaving]),0);
  await assert.rejects(()=>signup(rejoining,{...meta,phone_number:leavePhone}),/rejoin_wait_3_days/);
  await assert.rejects(()=>db.query('insert into auth.users(id,email,encrypted_password,raw_user_meta_data) values($1,$2,$3,$4)',[rejoining,`${leaving}@example.invalid`,'synthetic-non-login-hash',meta]),/rejoin_wait_3_days/);
  await db.query("update ojjuda_account_internal.withdrawn_member_accounts set withdrawn_at=clock_timestamp()-interval '71 hours 59 minutes' where user_id=$1",[leaving]);
  await assert.rejects(()=>signup(rejoining,{...meta,phone_number:leavePhone}),/rejoin_wait_3_days/);
  await db.query("update ojjuda_account_internal.withdrawn_member_accounts set withdrawn_at=clock_timestamp()-interval '72 hours 1 second' where user_id=$1",[leaving]);
  await signup(rejoining,{...meta,phone_number:leavePhone});
  await db.query("update ojjuda_account_internal.withdrawn_member_accounts set withdrawn_at=clock_timestamp()-interval '2 months',expires_at=clock_timestamp()-interval '1 second' where user_id=$1",[leaving]);
  assert.equal(Number(await value('select ojjuda_account_internal.purge_withdrawn_member_accounts() as value')),1);
  assert.equal(await value('select count(*)::int as value from ojjuda_account_internal.withdrawn_member_accounts where user_id=$1',[leaving]),0);
  await db.close();
  console.log('PASS: signup validation, member/admin permissions, masked and audited emergency phone access, one-month private withdrawal archive, 72-hour rejoin block and expiry purge');
})().catch(error=>{console.error(error);process.exitCode=1;});
