const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
const {PGlite}=require('@electric-sql/pglite');
(async()=>{const db=new PGlite();try{
 const a='00000000-0000-4000-8000-000000000001',b='00000000-0000-4000-8000-000000000002',file='10000000-0000-4000-8000-000000000001.jpg';
 await db.exec(`create role anon;create role authenticated;create schema auth;create schema storage;
  create function auth.uid() returns uuid language sql stable as $$select nullif(current_setting('request.jwt.claim.sub',true),'')::uuid$$;
  create function public.is_admin() returns boolean language sql stable as $$select current_setting('test.admin',true)='true'$$;
  grant usage on schema auth,storage to anon,authenticated;
  create table public.profiles(id uuid primary key,nickname text,avatar jsonb default '{}');
  alter table public.profiles enable row level security;
  grant select on public.profiles to authenticated;
  grant update(nickname,avatar) on public.profiles to authenticated;
  create policy profiles_select on public.profiles for select to authenticated using(true);
  create policy profiles_update on public.profiles for update to authenticated using(id=auth.uid()) with check(id=auth.uid());
  create table storage.objects(bucket_id text,name text);
  alter table storage.objects enable row level security;grant select on storage.objects to authenticated;
  create policy existing_owner_read on storage.objects for select to authenticated using(bucket_id='media' and split_part(name,'/',1)=auth.uid()::text);
  create table public.media(user_id uuid,path text);grant select,insert on public.media to authenticated;
  alter table public.media enable row level security;
  create policy own_media_read on public.media for select to authenticated using(user_id=auth.uid());
  create policy own_media_insert on public.media for insert to authenticated with check(user_id=auth.uid());
  create policy legacy_album_read on storage.objects for select to authenticated using(bucket_id='media' and exists(select 1 from public.media m where m.path=objects.name));
  insert into public.profiles(id,nickname) values('${a}','회원A'),('${b}','회원B');
  insert into storage.objects values('media','${a}/profile/${file}'),('media','${a}/profile-source/${file}'),('media','${a}/other/${file}'),('other','${a}/profile/${file}');`);
 await db.exec(fs.readFileSync(path.join(__dirname,'../supabase/migrations/20261004090523_profile_photo_storage.sql'),'utf8'));
 await db.exec(fs.readFileSync(path.join(__dirname,'../supabase/migrations/20261004091534_profile_photo_source_guard.sql'),'utf8'));
 const set=async values=>db.query('update public.profiles set profile_photo_path=$1,profile_photo_source_path=$2,profile_photo_crop=$3 where id=$4 returning id',[...values,a]);
 const valid=[a+'/profile/'+file,a+'/profile-source/'+file,{v:1,zoom:2,cx:.4,cy:.6}];
 await db.query("select set_config('request.jwt.claim.sub',$1,false)",[a]);await db.exec('set role authenticated');
 await assert.rejects(()=>set(valid),/permission denied for table profiles/,'new photo columns must reproduce production column-level UPDATE permissions');
 await db.exec('reset role');
 await db.exec(fs.readFileSync(path.join(__dirname,'../supabase/migrations/20261004102858_profile_photo_update_grants.sql'),'utf8'));
 assert.deepEqual((await db.query("select has_table_privilege('authenticated','public.profiles','UPDATE') as table_update,has_column_privilege('authenticated','public.profiles','id','UPDATE') as id_update,has_column_privilege('anon','public.profiles','profile_photo_path','UPDATE') as anon_update")).rows,[{table_update:false,id_update:false,anon_update:false}],'repair grants only authenticated photo metadata updates, not the full table or protected columns');
 await db.exec('set role authenticated');
 assert.equal((await set(valid)).rows.length,1);
 assert.equal((await db.query('select name from storage.objects')).rows.length,3,'owner can read cropped image, original and own legacy media');
 for(const bad of [[b+'/profile/'+file,valid[1],valid[2]],[valid[0],b+'/profile-source/'+file,valid[2]],[valid[0],null,valid[2]],[valid[0],valid[1],{v:1,zoom:5,cx:.5,cy:.5}],[valid[0],valid[1],{v:1,zoom:1,cx:-1,cy:.5}],[valid[0],valid[1],{v:1,zoom:1,cx:.5}],[valid[0],valid[1],{...valid[2],raw:'not allowed'}]])await assert.rejects(()=>set(bad));
 await db.query("select set_config('request.jwt.claim.sub',$1,false)",[b]);
 assert.deepEqual((await db.query('select bucket_id,name from storage.objects')).rows,[{bucket_id:'media',name:valid[0]}],'other members can read only the referenced crop, never the original or unrelated files');
 await db.query('insert into public.media(user_id,path) values($1,$2)',[b,valid[1]]);
 assert.deepEqual((await db.query('select bucket_id,name from storage.objects')).rows,[{bucket_id:'media',name:valid[0]}],'a forged owned album row cannot bypass source privacy through a permissive legacy Storage policy');
 assert.equal((await set([null,null,null])).rows.length,0,'other members cannot edit the photo metadata');
 await db.exec('reset role;set role anon');await assert.rejects(()=>db.query('select * from storage.objects'),/permission denied/);
 await db.exec('reset role;set role authenticated');await db.query("select set_config('request.jwt.claim.sub',$1,false)",[a]);await set([null,null,null]);
 await db.query("select set_config('request.jwt.claim.sub',$1,false)",[b]);assert.equal((await db.query('select name from storage.objects')).rows.length,0,'removing the profile reference revokes member access to the former crop');
 console.log('PASS: production column grants reproduced and repaired; profile photo ownership, strict metadata, member crop read, private source, bucket isolation and revoked reference access');
}finally{await db.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
