const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
const {chromium}=require('playwright'),root=path.resolve(__dirname,'..');
const proof=process.env.PROFILE_PHOTO_PROOF_DIR;
const fixture=`<!doctype html><meta charset="utf-8"><link rel="stylesheet" href="/world-profile-photo.css"><button id="trigger">사진 바꾸기</button><script src="/world-profile-photo.js"></script><script>
window.uid='00000000-0000-4000-8000-000000000001';window.files=new Map();window.calls=[];window.profile={};window.fail=null;window.saved=[];window.notices=[];
const client={storage:{from(bucket){return {async upload(path,blob){calls.push({type:'upload',path,size:blob.size,mime:blob.type});if(fail==='upload')return {error:new Error('upload failure')};files.set(path,blob);return {data:{path}}},async remove(paths){calls.push({type:'remove',paths});paths.forEach(p=>files.delete(p));return{}},async createSignedUrl(path){calls.push({type:'sign',path});if(fail==='sign-wait')return new Promise(resolve=>window.releaseSign=()=>resolve({error:true}));if(fail==='sign')return {error:true};const blob=files.get(path);return blob?{data:{signedUrl:URL.createObjectURL(blob)}}:{error:true}}}}},from(){let pending=null;return{update(value){pending=value;return this},eq(){return this},select(){return this},async single(){calls.push({type:'update',value:pending});if(fail==='update-wait')return new Promise(resolve=>window.releaseUpdate=()=>{profile={...pending};resolve({data:profile});});if(fail==='update')return{error:new Error('update failure')};profile={...pending};if(fail==='lost-response')return{error:new Error('lost response')};return{data:profile}},async maybeSingle(){calls.push({type:'probe'});if(fail==='probe')return{error:true};return{data:profile}}}}};
window.photo=OjjudaProfilePhoto.create({client,getUser:()=>uid?{id:uid}:null,onSaved:(...args)=>saved.push(args),notify:text=>notices.push(text)});
window.openPhoto=options=>{window.outcome='pending';window.pending=photo.open(options).then(value=>window.outcome=value)};document.querySelector('#trigger').onclick=()=>openPhoto({path:profile.profile_photo_path,sourcePath:profile.profile_photo_source_path,crop:profile.profile_photo_crop});
</script>`;
(async()=>{const browser=await chromium.launch({headless:true,executablePath:process.env.PLAYWRIGHT_CHROMIUM_EXECUTABLE_PATH||undefined,args:['--no-sandbox']});try{
 const context=await browser.newContext({viewport:{width:390,height:844},hasTouch:true});await context.route('**/*',route=>{const url=new URL(route.request().url());if(url.hostname!=='fixture.test')return route.abort();if(url.pathname==='/fixture')return route.fulfill({contentType:'text/html',body:fixture});const file=path.resolve(root,'.'+url.pathname);return file.startsWith(root+path.sep)&&fs.existsSync(file)?route.fulfill({path:file}):route.abort();});
 const page=await context.newPage(),errors=[];page.on('pageerror',e=>{errors.push(e.message);console.error('PAGEERROR',e.message);});await page.goto('https://fixture.test/fixture');
 const png=Buffer.from(await page.evaluate(async()=>{const c=document.createElement('canvas');c.width=2400;c.height=1200;const x=c.getContext('2d');for(const [i,color]of ['#e02020','#20c030','#2040e0'].entries()){x.fillStyle=color;x.fillRect(i*800,0,800,1200);}return Array.from(new Uint8Array(await(await new Promise(r=>c.toBlob(r,'image/png'))).arrayBuffer()));}));
 const file={name:'사용자 원본 이름.png',mimeType:'image/png',buffer:png},dialog=page.getByRole('dialog',{name:'프로필 사진 편집'}),status=dialog.getByRole('status'),save=dialog.getByRole('button',{name:'저장',exact:true});
 const choose=async()=>{await dialog.locator('input[type=file]').setInputFiles(file);await page.waitForFunction(()=>document.querySelector('.profile-photo-save')?.disabled===false&&document.querySelector('.profile-photo-stage')?.getAttribute('aria-disabled')==='false');};
 await page.locator('#trigger').click();await choose();await dialog.getByRole('button',{name:'취소',exact:true}).click();assert.equal(await page.evaluate(()=>outcome),null);assert.equal(await page.evaluate(()=>calls.filter(c=>c.type==='upload').length),0,'selection/cancel never uploads');
 await page.evaluate(()=>{fail='sign-wait';openPhoto({sourcePath:uid+'/profile-source/20000000-0000-4000-8000-000000000001.jpg'});});await dialog.waitFor();await page.waitForFunction(()=>!!window.releaseSign);await dialog.getByRole('button',{name:'취소',exact:true}).click();assert.equal(await page.evaluate(()=>outcome),null,'cancel resolves immediately while the initial source request is pending');await page.evaluate(()=>{releaseSign();fail=null;});
 await page.locator('#trigger').click();await dialog.locator('input[type=file]').evaluate(input=>{const files=new DataTransfer();files.items.add(new File([new Uint8Array(21*1024*1024)],'too-big.png',{type:'image/png'}));input.files=files.files;input.dispatchEvent(new Event('change'));});await status.filter({hasText:'20MB 이하'}).waitFor();assert.equal(await save.isEnabled(),false);await dialog.getByRole('button',{name:'취소',exact:true}).click();
 await page.locator('#trigger').click();await dialog.locator('input[type=file]').setInputFiles({name:'unsupported.heic',mimeType:'image/heic',buffer:Buffer.from('not a supported image')});await status.filter({hasText:'JPG·PNG·WEBP'}).waitFor();assert.equal(await save.isEnabled(),false);await choose();
 await dialog.getByRole('slider',{name:'사진 확대'}).fill('2');await dialog.getByRole('slider',{name:'사진 확대'}).dispatchEvent('input');assert.equal(await dialog.locator('output').textContent(),'200%');
 const canvas=dialog.locator('canvas'),bounds=await canvas.boundingBox();await page.mouse.move(bounds.x+bounds.width/2,bounds.y+bounds.height/2);await page.mouse.down();await page.mouse.move(bounds.x+bounds.width*1.4,bounds.y+bounds.height/2);await page.mouse.up();
 const cropPixels=await canvas.evaluate(c=>Array.from(c.getContext('2d').getImageData(256,256,1,1).data));assert.ok(cropPixels[0]>cropPixels[1],'drag changes the selected picture region');
 for(const width of [320,390,1280]){await page.setViewportSize({width,height:844});assert.equal(await dialog.evaluate(el=>el.scrollWidth<=el.clientWidth&&el.getBoundingClientRect().right<=innerWidth),true);}
 await page.evaluate(()=>{document.documentElement.style.setProperty('--surface','#1D2040');document.documentElement.style.setProperty('--ink','#ECEEFF');document.documentElement.style.setProperty('--ink-2','#A3A8D4');});assert.deepEqual(await dialog.evaluate(el=>({background:getComputedStyle(el).backgroundColor,color:getComputedStyle(el).color})),{background:'rgb(29, 32, 64)',color:'rgb(236, 238, 255)'},'dark World theme keeps light text on a dark dialog');await page.evaluate(()=>{for(const key of ['--surface','--ink','--ink-2'])document.documentElement.style.removeProperty(key);});
 await page.setViewportSize({width:390,height:844});if(proof){fs.mkdirSync(proof,{recursive:true});await page.screenshot({path:path.join(proof,'crop-mobile.png')});}
 await page.evaluate(()=>fail='update');await save.click();await status.filter({hasText:'저장하지 못했어요'}).waitFor();assert.deepEqual(await page.evaluate(()=>profile),{});assert.equal(await page.evaluate(()=>files.size),0,'failed profile update removes only its new uploads');assert.equal(await save.isEnabled(),true);
 await page.evaluate(()=>fail=null);await save.click();await dialog.waitFor({state:'detached'});await page.waitForFunction(()=>outcome!=='pending');const result=await page.evaluate(()=>outcome);assert.equal(result.crop.zoom,2);assert.ok(result.crop.cx<.5);assert.ok(result.path.includes('/profile/'));assert.ok(result.sourcePath.includes('/profile-source/'));assert.equal(await page.evaluate(()=>saved.length),1);
 const dimensions=await page.evaluate(async()=>{const answer={};for(const [path,blob]of files){const image=await createImageBitmap(blob);answer[path]={width:image.width,height:image.height,mime:blob.type};image.close();}return answer;});assert.deepEqual(dimensions[result.path],{width:512,height:512,mime:'image/jpeg'});assert.deepEqual(dimensions[result.sourcePath],{width:2048,height:1024,mime:'image/jpeg'});assert.equal(await page.evaluate(()=>[...files.keys()].some(p=>p.includes('사용자'))),false);
 await page.locator('#trigger').click();await page.waitForFunction(()=>document.querySelector('.profile-photo-save')?.disabled===false&&document.querySelector('.profile-photo-stage')?.getAttribute('aria-disabled')==='false');assert.equal(await dialog.getByRole('slider').inputValue(),'2');assert.deepEqual(await canvas.evaluate(c=>Array.from(c.getContext('2d').getImageData(256,256,1,1).data)),cropPixels,'reopen restores crop from the saved private source');
 const beforeReframe=await page.evaluate(()=>calls.filter(c=>c.type==='upload').length);await canvas.focus();await page.keyboard.press('ArrowLeft');await page.evaluate(()=>fail='lost-response');await save.click();await dialog.waitFor({state:'detached'});await page.waitForFunction(()=>outcome!=='pending');assert.equal(await page.evaluate(()=>calls.filter(c=>c.type==='upload').length),beforeReframe+1,'reframing reuses the saved source');assert.equal(await page.evaluate(()=>outcome.sourcePath),result.sourcePath);assert.ok(await page.evaluate(()=>calls.some(c=>c.type==='probe')),'a lost update response is verified before declaring failure');
 await page.evaluate(()=>fail=null);await page.locator('#trigger').click();await page.waitForFunction(()=>document.querySelector('.profile-photo-save')?.disabled===false&&document.querySelector('.profile-photo-stage')?.getAttribute('aria-disabled')==='false');const touchBounds=await canvas.boundingBox(),session=await context.newCDPSession(page);await session.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{x:touchBounds.x+80,y:touchBounds.y+140,id:1},{x:touchBounds.x+160,y:touchBounds.y+140,id:2}]});await session.send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:[{x:touchBounds.x+50,y:touchBounds.y+140,id:1},{x:touchBounds.x+200,y:touchBounds.y+140,id:2}]});await session.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});assert.ok(Number(await dialog.getByRole('slider').inputValue())>2,'two-finger pinch changes zoom');await page.keyboard.press('Escape');await dialog.waitFor({state:'detached'});assert.equal(await page.evaluate(()=>outcome),null);
 await page.locator('#trigger').click();await page.waitForFunction(()=>document.querySelector('.profile-photo-save')?.disabled===false&&document.querySelector('.profile-photo-stage')?.getAttribute('aria-disabled')==='false');await page.clock.install();await page.evaluate(()=>fail='update-wait');const filesBeforePending=await page.evaluate(()=>files.size);await save.click();await page.waitForFunction(()=>!!window.releaseUpdate);await page.clock.fastForward(10001);await status.filter({hasText:'저장 결과를 확인하지 못했어요'}).waitFor();assert.equal(await save.isEnabled(),false,'an unresolved write cannot be resubmitted from the same editor');assert.equal(await dialog.getByRole('button',{name:'취소',exact:true}).isEnabled(),true,'network timeout releases cancel');assert.equal(await page.evaluate(()=>files.size),filesBeforePending+1,'pending update keeps its uploaded crop even when an early probe sees the old profile');await page.evaluate(()=>{releaseUpdate();fail=null;});assert.equal(await page.evaluate(()=>files.has(profile.profile_photo_path)),true,'a late successful update never points to a deleted crop');await dialog.getByRole('button',{name:'취소',exact:true}).click();
 await page.locator('#trigger').click();await page.waitForFunction(()=>document.querySelector('.profile-photo-save')?.disabled===false&&document.querySelector('.profile-photo-stage')?.getAttribute('aria-disabled')==='false');const writes=await page.evaluate(()=>calls.filter(c=>c.type==='upload'||c.type==='update').length);await page.evaluate(()=>uid='00000000-0000-4000-8000-000000000002');await save.click();await dialog.waitFor({state:'detached'});assert.ok(await page.evaluate(()=>notices.some(text=>text.includes('계정이 바뀌'))));assert.equal(await page.evaluate(()=>calls.filter(c=>c.type==='upload'||c.type==='update').length),writes,'account switch prevents new mutations');await page.evaluate(()=>photo.destroy());await dialog.waitFor({state:'detached'});assert.deepEqual(errors,[]);
 console.log('PASS: crop drag/zoom/touch, cancel, decode rejection, responsive layout, 512px derivative, private 2048px source, failed/lost-save recovery, reopen/reframe and account changes');
}finally{await browser.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
