const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),{JSDOM}=require('jsdom');
const a='00000000-0000-4000-8000-000000000001',b='00000000-0000-4000-8000-000000000002',neighbour='00000000-0000-4000-8000-000000000003';
const dom=new JSDOM(`<div data-ju-user="${neighbour}"><i class="pc-av"></i><b class="pc-name"></b></div>`,{url:'https://shop.test/',runScripts:'outside-only'}),w=dom.window;
let owner=a,authChange,now=Date.now();const jobs=[],balances=[];
w.Date.now=()=>now;w.AbortSignal=AbortSignal;
w.eval(fs.readFileSync(path.join(__dirname,'../ju-shop.js'),'utf8'));
const tick=()=>new Promise(resolve=>setTimeout(resolve,0));
const client={auth:{onAuthStateChange(fn){authChange=fn;return{data:{subscription:{unsubscribe(){}}}};}},rpc(name,args){return{abortSignal(){return new Promise(resolve=>jobs.push({name,args,owner,resolve}));}};}};
const data=(coins=10)=>({ok:true,coins,products:[],selected:{},owned:[{key:'profile_flower',expires_at:new Date(now+120000).toISOString()}]});
const respond=(job,value,error=null)=>job.resolve({data:value,error});
const decor=(key,expiry=now+120000)=>({[neighbour]:{frame:{key,expires_at:new Date(expiry).toISOString()}}});
const count=name=>jobs.filter(j=>j.name===name).length;
(async()=>{try{
 w.OjjudaShop.install({client,getUserId:()=>owner,onBalance:(coins,user)=>balances.push({coins,user})});await tick();
 const pending=Array.from({length:12},()=>w.OjjudaShop.refresh());
 assert.equal(count('ju_shop_state'),1,'concurrent state reads share one request');
 respond(jobs[0],data());await Promise.all(pending);await tick();
 for(let i=0;i<20;i++)w.OjjudaShop.decorateWorld();
 assert.equal(count('ju_shop_public_decor'),1,'repainting during a pending request does not start duplicates');
 respond(jobs.find(j=>j.name==='ju_shop_public_decor'),decor('profile_flower'));await tick();
 for(let i=0;i<20;i++)w.OjjudaShop.decorateWorld();await tick();
 assert.equal(count('ju_shop_public_decor'),1,'twenty repaints reuse the one successful public decoration read');
 assert.equal(w.document.querySelector('.pc-av').dataset.juFrame,'profile_flower');
 now+=60001;w.OjjudaShop.decorateWorld();
 const failed=jobs.at(-1);respond(failed,null,Error('offline'));await tick();
 w.OjjudaShop.decorateWorld();respond(jobs.at(-1),decor('profile_star',now+1000));await tick();
 assert.equal(w.document.querySelector('.pc-av').dataset.juFrame,'profile_star','failed reads can retry');
 now+=1001;w.OjjudaShop.decorateWorld();await tick();
 assert.equal(w.document.querySelector('.pc-av').dataset.juFrame,'','cached cosmetics expire without waiting for another request');
 const oldState=w.OjjudaShop.refresh(),oldJob=jobs.at(-1),newState=w.OjjudaShop.refresh({force:true}),newJob=jobs.at(-1);
 respond(newJob,data(25));await newState;respond(oldJob,data(3));await oldState;
 assert.equal(balances.at(-1).coins,25,'a pre-purchase/older refresh cannot roll back a forced latest balance');
 now+=60001;w.OjjudaShop.decorateWorld();const stale=jobs.at(-1);
 owner=b;authChange('SIGNED_IN');w.OjjudaShop.decorateWorld();const current=jobs.at(-1);
 assert.equal(w.OjjudaShop.owned('profile_flower'),undefined,'ownership is cleared across accounts');
 respond(current,decor('profile_new'));await tick();respond(stale,decor('profile_old'));await tick();
 assert.equal(w.document.querySelector('.pc-av').dataset.juFrame,'profile_new','a prior-account response cannot change current decorations');
 const accountB=jobs.filter(j=>j.name==='ju_shop_state'&&j.owner===b).at(-1);owner=null;authChange('SIGNED_OUT');respond(accountB,data(900));await tick();
 assert.ok(!balances.some(x=>x.user===b),'a response after sign-out cannot restore an account balance');
 console.log('PASS: state coalescing, 20 decoration repaints use 1 request, expiry, retry, forced refresh order and account/logout isolation');
}finally{w.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
