// Real house-test UI, painter and PNGs, with an isolated local owner fixture.
// No production data, authentication, generated artwork or deployment is mocked.
const {chromium}=require(process.env.CODEX_PRIMARY_RUNTIME_NODE_MODULES?process.env.CODEX_PRIMARY_RUNTIME_NODE_MODULES+'/playwright':'playwright');
const fs=require('fs'),path=require('path'),assert=require('assert/strict'),crypto=require('crypto');
const repo=path.resolve(process.env.ROOT_DIR||path.join(__dirname,'..')),workspace=process.env.QA_WORKSPACE||path.resolve(repo,'..');
const output=path.resolve(process.env.QA_OUTPUT_DIR||path.join(repo,'house-test/qa/sofa-accessories-v1'));
const fontRoot=path.join(workspace,'preview-tools/node_modules/@fontsource/noto-sans-kr');
const localChromium=path.join(workspace,'preview-tools/chromium');
const origin='https://fixture.test',version='20261002-sofa-accessories-v1',owner='local-sofa-accessories-review';
const ids=['cream-floral-cushion','sage-cushion','peach-cushion','pink-check-cushion','blanket-sofa'],directions=['left','center','right'];
const hash=s=>crypto.createHash('sha256').update(s).digest('hex');
async function main(){
 fs.mkdirSync(output,{recursive:true});
 const report={startedAt:new Date().toISOString(),version,scope:'Focused actual UI and raster verification; isolated local storage only, no deployment.',checks:[],paint:[],screenshots:[],errors:[],failedRequests:[],visualReview:'Screenshots for final human review; functional checks do not approve illustration design.'};
 const browser=await chromium.launch({headless:true,executablePath:process.env.PLAYWRIGHT_CHROMIUM_EXECUTABLE_PATH||process.env.CHROMIUM_PATH||(fs.existsSync(localChromium)?localChromium:undefined),args:['--no-sandbox','--disable-gpu','--disable-dev-shm-usage','--disable-software-rasterizer']});
 let context,page,frame;const requests=[];
 try{
  context=await browser.newContext({viewport:{width:1100,height:960},deviceScaleFactor:1,hasTouch:true});page=await context.newPage();
  page.on('pageerror',e=>report.errors.push(e.message));page.on('console',m=>{if(m.type()==='error')report.errors.push(m.text());});page.on('request',r=>requests.push(new URL(r.url()).pathname));page.on('requestfailed',r=>report.failedRequests.push({url:r.url(),error:r.failure()?.errorText}));
  await page.clock.install({time:new Date('2026-10-02T11:00:00+09:00')});
  await page.route('**/*',route=>{const u=new URL(route.request().url());if(u.origin!==origin)return route.abort();if(u.pathname==='/qa')return route.fulfill({contentType:'text/html',body:'<!doctype html><html lang="ko"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><button id="open">열기</button><script type="module">import {openHouseTest} from "/house-test/host.js";document.querySelector("#open").onclick=()=>openHouseTest({owner:"'+owner+'",authorized:()=>true});</script></html>'});if(u.pathname==='/favicon.ico')return route.fulfill({status:204});const font=u.pathname.startsWith('/qa-font/'),root=font?fontRoot:repo,file=path.resolve(root,'.'+decodeURIComponent(font?u.pathname.slice('/qa-font'.length):u.pathname));return file.startsWith(root+path.sep)&&fs.existsSync(file)&&fs.statSync(file).isFile()?route.fulfill({path:file}):route.abort();});
  await page.goto(origin+'/qa');
  const ready=async()=>{await frame.locator('#app').waitFor({state:'visible'});await frame.locator('body').evaluate(async()=>{await Promise.all([...document.querySelectorAll('.room-bg')].map(im=>im.decode()));});await frame.locator('body').evaluate(()=>new Promise(resolve=>{const check=()=>[...document.querySelectorAll('.furniture')].some(n=>n.dataset.renderState==='loading')?requestAnimationFrame(check):resolve();check();}));assert.equal(await frame.locator('.furniture[data-render-state="error"]').count(),0);};
  const open=async()=>{await page.locator('#open').click();frame=page.frameLocator('iframe[title="우리집"]');await ready();if(fs.existsSync(path.join(fontRoot,'400.css')))await frame.locator('body').evaluate(async()=>{const link=document.createElement('link');link.rel='stylesheet';link.href='/qa-font/400.css';const loaded=new Promise((r,j)=>{link.onload=r;link.onerror=j;});document.head.append(link);await loaded;const s=document.createElement('style');s.textContent='body,button,input,output{font-family:"Noto Sans KR",sans-serif!important}';document.head.append(s);await document.fonts.load('16px "Noto Sans KR"','소파 쿠션 담요 우리집');});};
  const reopen=async()=>{await page.getByRole('button',{name:'우리집 닫기',exact:true}).click();await open();};
  const click=async label=>{if(!await frame.getByRole('button',{name:label,exact:true}).count()&&await frame.locator('[data-category]').count())await frame.locator('[data-category="'+(label.startsWith('바닥 담요')?'accessories':'furniture')+'"]').click();await frame.getByRole('button',{name:label,exact:true}).click();await ready();};
  const node=id=>frame.locator('.room[data-room="0:0"] .furniture[data-furniture="'+id+'"]');
  const pose=id=>node(id).evaluate(n=>({direction:n.dataset.direction,x:Number(n.dataset.x),y:Number(n.dataset.y)}));
  const flags=()=>frame.locator('input[data-accessory]').evaluateAll(nodes=>Object.fromEntries(nodes.map(n=>[n.dataset.accessory,n.checked])));
  const stored=()=>frame.locator('body').evaluate((element,key)=>JSON.parse(localStorage.getItem(key)), 'ojjuda-house-playtest-v1:'+encodeURIComponent(owner));
  const pixelHash=async id=>hash(await node(id).locator('canvas').evaluate(c=>c.toDataURL()));
  const capture=async name=>{await ready();await page.clock.runFor(3000);await frame.locator('#notice:not(.show)').waitFor({state:'attached'});const file=name+'.png';await frame.locator('#app').screenshot({path:path.join(output,file)});report.screenshots.push(file);};
  const slider=async(id,value)=>{const c=frame.locator(id),difference=value-Number(await c.inputValue());assert.equal(Math.round(difference*2),difference*2);await c.focus();for(let i=0;i<Math.abs(difference)*2;i++)await c.press(difference>0?'ArrowRight':'ArrowLeft');await ready();assert.equal(Number(await c.inputValue()),value);};
  const direction=async d=>{await frame.locator('#panel-body button[data-direction="'+d+'"]').click();await ready();};
  const checkbox=async(id,value)=>{await frame.locator('input[data-accessory="'+id+'"]').setChecked(value);await ready();};
  const inspect=async(id,enabled=Object.fromEntries(ids.map(k=>[k,true])))=>{
   await ready();const result=await node(id).evaluate(async(n,{id,enabled,version})=>{
    const {furnitureGeometry}=await import('./furniture.js?v='+version),{roomPoint}=await import('./model.js?v='+version),{SOFA_V1}=await import('./sofa-v1-registration.js?v='+version);
    const placement={direction:n.dataset.direction,x:Number(n.dataset.x),y:Number(n.dataset.y),...(id==='sofa'?{accessories:enabled}:{})},g=furnitureGeometry(id,placement),canvas=n.querySelector('canvas'),pixels=canvas.getContext('2d').getImageData(0,0,canvas.width,canvas.height).data;
    let painted=0;for(let i=3;i<pixels.length;i+=4)if(pixels[i]>24)painted++;
    const expected=id==='sofa'?SOFA_V1[placement.direction].mesh.anchors.filter(a=>a.kind==='physical'&&Math.abs(a.world.z)<1e-8).map(a=>roomPoint(placement.x+a.world.x,placement.y+a.world.y,a.world.z)):g.registration.worldCorners.map(p=>roomPoint(p.x,p.y,p.z));
    const anchorError=Math.max(0,...g.anchors.map((p,i)=>Math.hypot(p.x-expected[i].x,p.y-expected[i].y)));
    const layers=(g.art.layers||[]).map(l=>({id:l.id,image:l.image,source:JSON.stringify(l.triangles.map(t=>t.source)),center:l.triangles.flatMap(t=>t.target).reduce((a,p,_,list)=>({x:a.x+p.x/list.length,y:a.y+p.y/list.length}),{x:0,y:0})}));
    const svg=[...document.querySelectorAll('.room.selected .floor-grid .bookshelf-anchor')].map(n=>({x:Number(n.getAttribute('cx')),y:Number(n.getAttribute('cy'))}));
    return {id,placement,sources:canvas.dataset.sources.split(' '),layerIds:(canvas.dataset.layers||'').split(' ').filter(Boolean),canvas:[canvas.width,canvas.height],painted,anchorError,anchors:g.anchors,svg,layers,zIndex:Number(n.style.zIndex)};
   },{id,enabled,version});
   assert.ok(result.painted>200,id+' canvas must paint actual pixels');assert.ok(result.anchorError<1e-5);if(result.svg.length){assert.equal(result.svg.length,result.anchors.length);result.svg.forEach((p,i)=>assert.ok(Math.hypot(p.x-result.anchors[i].x,p.y-result.anchors[i].y)<1e-5));}
   const d=result.placement.direction;
   if(id==='sofa'){const expected=[...['left-arm','body','right-arm'].map(p=>'assets/sofa-'+d+'-'+p+'-v1.png'),...ids.filter(k=>enabled[k]).map(k=>'assets/'+k+'-'+d+'-v1.png')];assert.deepEqual([...result.sources].sort(),expected.sort());assert.deepEqual(result.layerIds.filter(k=>ids.includes(k)).sort(),ids.filter(k=>enabled[k]).sort());}
   else assert.deepEqual(result.sources,['assets/blanket-floor-'+d+'.png']);
   report.paint.push({...result,layers:result.layers.map(({source,...l})=>({...l,sourceTriangleSha256:hash(source)}))});return result;
  };
  await open();assert.equal(await node('sofa').count(),0);assert.equal(await node('blanket-floor').count(),0);assert.equal(await frame.locator('.chair').count(),0);
  const original={bookshelf:await pose('bookshelf'),desk:await pose('desk'),bookshelfPixels:await pixelHash('bookshelf'),deskPixels:await pixelHash('desk')};
  const preserved=async()=>{assert.deepEqual(await pose('bookshelf'),original.bookshelf);assert.deepEqual(await pose('desk'),original.desk);assert.equal(await pixelHash('bookshelf'),original.bookshelfPixels);assert.equal(await pixelHash('desk'),original.deskPixels);};
  await click('소파 놓기');assert.deepEqual(await pose('sofa'),{direction:'left',x:0,y:3});assert.deepEqual(await flags(),Object.fromEntries(ids.map(k=>[k,true])));const all=await inspect('sofa'),allHash=await pixelHash('sofa');
  for(const id of ids){await checkbox(id,false);const enabled=await flags();await inspect('sofa',enabled);assert.notEqual(await pixelHash('sofa'),allHash,id+' toggle must change actual pixels');await checkbox(id,true);assert.equal(await pixelHash('sofa'),allHash,id+' restoration must restore original pixels');}
  await click('설치');await reopen();await preserved();await frame.locator('#overview').click();await capture('desktop-all-items');report.checks.push('New sofas are explicitly added; each of four cushions and the sofa blanket uses its real PNG, independently changes pixels and restores exactly');
  await click('소파 배치');await checkbox('sage-cushion',false);await checkbox('blanket-sofa',false);const savedFlags=await flags();await click('설치');await reopen();await click('소파 배치');assert.deepEqual(await flags(),savedFlags);const baselineHash=await pixelHash('sofa');await checkbox('cream-floral-cushion',false);await slider('#bookshelf-gap',.5);await click('취소');assert.equal(await pixelHash('sofa'),baselineHash);await reopen();await click('소파 배치');assert.deepEqual(await flags(),savedFlags);assert.deepEqual(await pose('sofa'),{direction:'left',x:0,y:3});
  for(const id of ids)await checkbox(id,true);const beforeMove=await inspect('sofa');await slider('#bookshelf-gap',.5);const afterMove=await inspect('sofa');for(const l of beforeMove.layers){const moved=afterMove.layers.find(v=>v.id===l.id);assert.equal(moved.source,l.source);assert.ok(Math.hypot(moved.center.x-l.center.x,moved.center.y-l.center.y)>1,l.id+' must move with its sofa');}await click('설치');await reopen();assert.deepEqual(await pose('sofa'),{direction:'left',x:.5,y:3});report.checks.push('Sofa accessory state and pose save/reopen together; cancel restores both. All rendered layers move with the parent while source coordinates remain unchanged');
  await click('소파 배치');await slider('#bookshelf-gap',0);await direction('right');assert.ok(await frame.locator('#placement-done').isDisabled());assert.ok(await frame.locator('#placement-warning').isVisible());await click('취소');await preserved();report.checks.push('Standing sofa overlap with the existing desk/bookshelf is blocked; cancelling keeps the existing furniture');
  await click('바닥 담요 놓기');await slider('#bookshelf-gap',0);await slider('#bookshelf-depth',3);assert.ok(await frame.locator('#placement-done').isEnabled());const floorUnder=await inspect('blanket-floor');assert.ok(floorUnder.zIndex<Number(await node('sofa').evaluate(n=>n.style.zIndex)));await click('설치');await reopen();assert.deepEqual(await pose('blanket-floor'),{direction:'center',x:0,y:3});const floorSaved=await pixelHash('blanket-floor');await click('바닥 담요 배치');await slider('#bookshelf-gap',.5);await click('취소');assert.equal(await pixelHash('blanket-floor'),floorSaved);assert.deepEqual(await pose('sofa'),{direction:'left',x:.5,y:3});await click('바닥 담요 배치');await slider('#bookshelf-gap',3.5);await slider('#bookshelf-depth',4.5);await click('설치');report.checks.push('Floor blanket registers actual cloth corners through roomPoint, permits intended overlap below standing furniture, and moves/cancels independently');
  const poses={left:{gap:0,y:3},center:{gap:3,y:0},right:{gap:1,y:3}};
  for(const d of directions){
   await click('소파 배치');await direction(d);await slider('#bookshelf-depth',poses[d].y);await slider('#bookshelf-gap',poses[d].gap);assert.ok(await frame.locator('#placement-done').isEnabled());assert.deepEqual(await flags(),Object.fromEntries(ids.map(k=>[k,true])));await inspect('sofa');await click('설치');
   await click('바닥 담요 배치');await direction(d);await slider('#bookshelf-depth',4.5);await slider('#bookshelf-gap',d==='right'?4.5:4);await inspect('blanket-floor');await click('설치');await frame.locator('#overview').click();await capture('desktop-'+d);await preserved();
  }
  const finalPose=await pose('sofa'),finalFloor=await pose('blanket-floor');await reopen();assert.deepEqual(await pose('sofa'),finalPose);assert.deepEqual(await pose('blanket-floor'),finalFloor);await click('소파 배치');assert.deepEqual(await flags(),Object.fromEntries(ids.map(k=>[k,true])));await click('취소');report.checks.push('Three independent directional PNG sets reach the actual room painter; rotating keeps all accessory states and the final sofa/floor poses survive reopening');
  await page.setViewportSize({width:375,height:812});await frame.locator('#overview').click();await capture('mobile-room');await click('소파 배치');await frame.locator('input[data-accessory="pink-check-cushion"]').tap();await ready();assert.equal((await flags())['pink-check-cushion'],false);await capture('mobile-accessory-controls');await click('취소');await click('소파 배치');assert.equal((await flags())['pink-check-cushion'],true);await click('취소');const mobile=await frame.locator('body').evaluate(()=>({width:innerWidth,scroll:document.documentElement.scrollWidth}));assert.equal(mobile.width,mobile.scroll);report.mobile=mobile;await preserved();
  await click('바닥 담요 배치');await click('회수');await reopen();assert.equal(await node('blanket-floor').count(),0);await click('바닥 담요 놓기');await click('취소');assert.equal(await node('blanket-floor').count(),0);await click('소파 배치');await click('회수');await reopen();assert.equal(await node('sofa').count(),0);await click('소파 놓기');await click('취소');assert.equal(await node('sofa').count(),0);await reopen();await preserved();report.checks.push('375px mobile checkbox interaction and cancel work without overflow; removing sofa/floor persists, and cancelling a new placement does not re-add either');
  const state=await stored();report.finalState={version:state.version,roomCount:state.rooms.length,shelf:state.rooms[0].shelf,furniture:state.rooms[0].furniture};report.originalFurniture=original;
  const expectedAssets=directions.flatMap(d=>[...['left-arm','body','right-arm'].map(p=>'/house-test/assets/sofa-'+d+'-'+p+'-v1.png'),...ids.map(id=>'/house-test/assets/'+id+'-'+d+'-v1.png'),'/house-test/assets/blanket-floor-'+d+'.png']).sort();
  report.requestedSources=[...new Set(requests.filter(p=>/\/assets\/(?:sofa-|cream-floral-cushion-|sage-cushion-|peach-cushion-|pink-check-cushion-|blanket-sofa-|blanket-floor-)/.test(p)))].sort();assert.deepEqual(report.requestedSources,expectedAssets);assert.deepEqual(report.errors,[]);assert.deepEqual(report.failedRequests,[]);report.status='passed';
 }catch(error){report.status='failed';report.failure=error.stack;try{await frame?.locator('#app').screenshot({path:path.join(output,'failure.png'),timeout:3000});}catch{}throw error;}
 finally{fs.writeFileSync(path.join(output,'report.json'),JSON.stringify(report,null,2)+'\n');await context?.close();await browser.close();console.log(JSON.stringify({status:report.status,checks:report.checks,errors:report.errors,failure:report.failure,screenshots:report.screenshots},null,2));}
}
main().catch(error=>{console.error(error);process.exitCode=1;});
