import assert from 'node:assert/strict';import fs from 'node:fs';import crypto from 'node:crypto';
import {projectMesh} from '../house-test/picture-mesh.js';import {checkShape} from '../house-test/picture-quality.js';import {validateSofaRegistration} from '../house-test/sofa-registration-data.js';
const read=p=>JSON.parse(fs.readFileSync(new URL(p,import.meta.url))),a=read('../house-test/assets/sofa-registration-v7.runtime.json'),b=read('../house-test/assets/sofa-registration-v9.runtime.json'),weights=read('../scripts/sofa-left-calibration-weights.json');validateSofaRegistration(b);
assert.deepEqual(a.views.center,b.views.center);assert.deepEqual(a.views.right,b.views.right);const old=a.views.left,v=b.views.left;assert(!v.partMeshes,'one continuous mapping for body and both arms');assert.deepEqual(old.mesh.indices,v.mesh.indices);assert.deepEqual(old.parts,v.parts);assert.deepEqual(old.placement,v.placement);old.mesh.anchors.forEach((p,i)=>{assert.deepEqual(p.source,v.mesh.anchors[i].source);assert.equal(p.kind,v.mesh.anchors[i].kind);if(p.kind==='physical')assert.equal(p.world.z,v.mesh.anchors[i].world.z);});
for(const [part,data] of Object.entries(weights.parts)){const bytes=fs.readFileSync(new URL('../house-test/'+v.parts[part],import.meta.url));assert.equal(crypto.createHash('sha256').update(bytes).digest('hex'),data.sha256,'alpha weights correspond to the original PNG');}
const cross=(a,b,p)=>(b.x-a.x)*(p.y-a.y)-(b.y-a.y)*(p.x-a.x);
function sample(p,pt){const t=p.triangles.find(t=>t.source.every((a,j)=>cross(a,t.source[(j+1)%3],pt)>=-1e-6));assert(t);const m=t.matrix;return {x:m[0]*pt.x+m[2]*pt.y+m[4],y:m[1]*pt.x+m[3]*pt.y+m[5]};}
const tops=[{x:85,y:952},{x:710,y:1040},{x:1307,y:630}];let retained=0,maxShaft=0;
for(let x=0;x<=8.5;x+=.5)for(let y=0;y<=3.5;y+=.5){const pose={...v.placement,x,y};try{for(const m of [old.mesh,...Object.values(old.partMeshes||{})])projectMesh(m,pose);}catch{continue;}const p=projectMesh(v.mesh,pose);retained++;for(const data of Object.values(weights.parts))assert(checkShape(p.triangles,data.weights).ok,`all parts retain shape at ${x},${y}`);
 for(let i=0;i<3;i++){const foot=p.points[i];assert.equal(foot.world.z,0);assert(foot.world.x>=0&&foot.world.x<=1.5&&foot.world.y>=0&&foot.world.y<=3.5);const pt=tops[i],t=p.triangles.find(t=>t.source.every((a,j)=>cross(a,t.source[(j+1)%3],pt)>=-1e-6));assert(t);const m=t.matrix,offset=Math.abs(m[0]*pt.x+m[2]*pt.y+m[4]-(i===0?sample(p,{x:84,y:1016}).x:foot.target.x));maxShaft=Math.max(maxShaft,offset);assert(offset<.25,'visible leg faces remain upright');}
 const line=Array.from({length:9},(_,i)=>sample(p,{x:170+i/8*450,y:972+i/8*62})),start=line[0],end=line[8],length=Math.hypot(end.x-start.x,end.y-start.y);for(const q of line.slice(1,-1))assert(Math.abs(cross(start,end,q))/length<.25,'wooden frame remains straight across mesh triangles');
 for(const [i,j] of [[6,8],[7,9]])assert(Math.abs(p.points[i].target.x-p.points[j].target.x)<1e-6,'arm edges remain upright');}
assert.equal(retained,42);console.log(`Whole left sofa PASS: ${retained} existing placements, all three parts; max shaft offset ${maxShaft.toFixed(3)}px`);
