// One blanket item switches between the approved floor and sofa drawings.
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),crypto=require('node:crypto');
const {chromium}=require('playwright'),root=path.resolve(__dirname,'..'),workspace=path.dirname(root);
const proof=process.env.BLANKET_PROOF_DIR||path.join(workspace,'house-opening-proof/blanket-placement');
const font=process.env.CHAIR_PROOF_FONT||path.join(workspace,'carpet-studio/NotoSansCJKkr-Regular.otf');
const version=fs.readFileSync(path.join(root,'house-test/app.js'),'utf8').match(/model\.js\?v=([^']+)/)[1];
const owner='local-blanket-placement',key='ojjuda-house-playtest-v1:'+owner,id='blanket-floor';
const manifest=JSON.parse(fs.readFileSync(path.join(root,'house-test/item-assets.json'))),sofaViews=JSON.parse(fs.readFileSync(path.join(root,'house-test/assets',manifest.assets.sofa.file))).views;
const sofas={left:{direction:'left',x:0,y:3},center:{direction:'center',x:3,y:0},right:{direction:'right',x:7.5,y:3}};
const expectedSofa=sofa=>{const offset={left:{x:.38,y:1.89},center:{x:.01,y:.38},right:{x:.02,y:.01}}[sofa.direction];return {direction:sofa.direction,x:Number((sofa.x+offset.x).toFixed(6)),y:Number((sofa.y+offset.y).toFixed(6)),elevation:.025,mode:'sofa'};};
const sha=value=>crypto.createHash('sha256').update(value).digest('hex');
(async()=>{
 fs.mkdirSync(proof,{recursive:true});const report={checks:[],views:[],errors:[],missing:[],screenshots:[]};
 const browser=await chromium.launch({headless:true,executablePath:process.env.PLAYWRIGHT_CHROMIUM_EXECUTABLE_PATH||undefined,args:['--no-sandbox','--disable-dev-shm-usage']});let page,f;
 try{
  const context=await browser.newContext({viewport:{width:1100,height:960},deviceScaleFactor:2});
  await context.route('**/*',route=>{const u=new URL(route.request().url());if(u.origin!=='https://fixture.test')return route.abort();if(u.pathname==='/fixture')return route.fulfill({contentType:'text/html',body:'<!doctype html><html lang="ko"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><button id="open">우리집</button><script type="module">import{openHouseTest}from"/house-test/host.js";document.querySelector("#open").onclick=()=>openHouseTest({owner:"'+owner+'",authorized:()=>true});</script></html>'});if(u.pathname==='/proof-font.otf'&&fs.existsSync(font))return route.fulfill({path:font,contentType:'font/otf'});if(u.pathname==='/favicon.ico')return route.fulfill({status:204});const file=path.resolve(root,'.'+decodeURIComponent(u.pathname));if(!file.startsWith(root+path.sep)||!fs.existsSync(file)||!fs.statSync(file).isFile()){report.missing.push(u.pathname);return route.abort();}return route.fulfill({path:file});});
  if(fs.existsSync(font))await context.addInitScript(()=>document.addEventListener('DOMContentLoaded',()=>{const style=document.createElement('style');style.textContent='@font-face{font-family:BlanketProof;src:url(/proof-font.otf)}body,button,input,output{font-family:BlanketProof,sans-serif!important}';document.head.append(style);},{once:true}));
  page=await context.newPage();page.on('pageerror',e=>report.errors.push(e.message));await page.goto('https://fixture.test/fixture');
  const node=target=>f.locator('[data-room="0:0"] [data-furniture="'+target+'"]');
  const pose=(target=id)=>node(target).evaluate(n=>{const result={direction:n.dataset.direction,x:Number(n.dataset.x),y:Number(n.dataset.y)};if(n.dataset.elevation!==undefined)result.elevation=Number(n.dataset.elevation);if(n.dataset.furniture.startsWith('blanket-'))result.mode=n.dataset.mode||(/(?:^|\s)assets\/blanket-floor-/.test(n.querySelector('canvas').dataset.sources)?'floor':'sofa');return result;});
  const read=()=>page.evaluate(key=>JSON.parse(localStorage.getItem(key)),key);
  const ready=async()=>{await f.waitForFunction(()=>[...document.querySelectorAll('.furniture')].every(n=>n.dataset.renderState==='ready'));await f.evaluate(()=>document.fonts.ready);};
  const open=async()=>{await page.locator('#open').click();await page.frameLocator('iframe').locator('#app').waitFor({state:'visible'});f=page.frames().find(frame=>frame.url().includes('/house-test/index.html'));await ready();await f.locator('[data-tab="room"]').click();};
  const close=async()=>{await f.locator('#exit').click();await page.waitForFunction(()=>!document.querySelector('iframe'));};
  const menu=async()=>{await f.locator('[data-category="accessories"]').click();const cards=f.locator('#panel-body button').filter({hasText:'담요'});assert.equal(await cards.count(),1,'the accessory menu exposes one blanket item');return cards;};
  const edit=async()=>{await(await menu()).click();await ready();await f.locator('#overview').click();};
  const capture=async name=>{await ready();const file=name+'.png';await page.screenshot({path:path.join(proof,file)});report.screenshots.push(file);};
  const inspect=async(target=id)=>{
   await ready();const p=await pose(target);
   const art=await node(target).evaluate(async(n,{p,target,version})=>{
    const {furnitureGeometry}=await import('/house-test/furniture.js?v='+version),{FURNITURE,itemSize,contactBounds}=await import('/house-test/furniture-catalog.js?v='+version),{blanketFloorArtwork}=await import('/house-test/accessory-art.js?v='+version),{sofaAccessoryArtwork}=await import('/house-test/sofa-accessory-art.js?v='+version);
    const g=furnitureGeometry(target,p),size=itemSize(target,p.direction,p),contact=contactBounds(target,p),expected=p.mode==='floor'?blanketFloorArtwork(FURNITURE[target],p,contact,size):sofaAccessoryArtwork({...FURNITURE[target],accessoryId:'blanket-sofa'},p,contact,size),canvas=n.querySelector('canvas.furniture-paint'),pixels=canvas.getContext('2d').getImageData(0,0,canvas.width,canvas.height).data;
    const signature=geometry=>JSON.stringify(geometry.art.layers?geometry.art.layers.map(layer=>({id:layer.id,image:layer.image,triangles:layer.triangles})):geometry.art.triangles);
    let painted=0;for(let i=3;i<pixels.length;i+=4)if(pixels[i]>24)painted++;
    return {kind:g.art.kind,size,sources:canvas.dataset.sources.split(' '),painted,zIndex:Number(n.style.zIndex),sofaZ:Number(document.querySelector('[data-furniture="sofa"]')?.style.zIndex),triangles:g.art.triangles?.length,layers:g.art.layers?.map(layer=>layer.id),registration:g.registration||null,geometryMatchesOriginal:signature(g)===signature(expected),signature:signature(g)};
   },{p,target,version});
   assert(art.painted>200,'approved blanket image paints visible pixels');assert(art.geometryMatchesOriginal,'mode uses the unchanged original source triangles and world projection');
   const isFloor=p.mode==='floor',expectedImage=isFloor?'assets/blanket-floor-'+p.direction+'.png':'assets/blanket-sofa-'+p.direction+'-v1.png';assert(art.sources.includes(expectedImage),'the selected mode and direction load their original PNG');assert(art.sources.every(source=>source===expectedImage||!isFloor&&(/^assets\/sofa-(left|center|right)-(left-arm|right-arm)-v1\.png$/.test(source)||source===sofaViews[p.direction].originalLayers?.side.image)),'source pixels are limited to this original blanket and permitted sofa masks');
   const [w,d]=isFloor?[2,1.5]:[1.6,1.1];assert.deepEqual(art.size,p.direction==='center'?{w,d}:{w:d,d:w});
   if(isFloor){assert.equal(art.kind,'floor-blanket');assert.equal(art.triangles,1152);assert.equal(art.registration.image,expectedImage);assert(art.registration.worldCorners.every(point=>point.z===0));assert.equal(art.zIndex,4);}
   else{assert.equal(art.kind,'sofa-accessory');assert.deepEqual(art.layers,['blanket-sofa','blanket-sofa-front']);assert(art.zIndex>art.sofaZ,'sofa drape paints over its supporting sofa');}
   return {...art,signature:undefined,geometrySha256:sha(art.signature),pose:p};
  };
  const dragTo=async(target,cancel=false)=>{
   const initial=await pose(),movement=await f.evaluate(async({initial,target,version,id})=>{const {floorPoint}=await import('/house-test/model.js?v='+version),{itemSize}=await import('/house-test/furniture-catalog.js?v='+version),size=itemSize(id,initial.direction,initial),from=floorPoint(initial.x+size.w/2,initial.y+size.d),to=floorPoint(target.x+size.w/2,target.y+size.d),scale=new DOMMatrixReadOnly(getComputedStyle(document.querySelector('#world')).transform).a;return {dx:(to.x-from.x)*scale,dy:(to.y-from.y)*scale};},{initial,target,version,id});
   const start=await node(id).evaluate(el=>{const b=el.getBoundingClientRect(),v=document.querySelector('#viewport').getBoundingClientRect();for(const fy of [.5,.25,.75,.1,.9])for(const fx of [.5,.25,.75,.1,.9]){const x=b.left+b.width*fx,y=b.top+b.height*fy,hit=document.elementFromPoint(x,y);if(x>v.left+2&&x<v.right-2&&y>v.top+2&&y<v.bottom-2&&(hit===el||el.contains(hit)))return {x,y};}throw new Error('Selected blanket has no pointer-accessible point');});
   const frameBox=await page.locator('iframe').boundingBox();await node(id).evaluate(el=>el.addEventListener('pointerdown',e=>el.dataset.testPointer=String(e.pointerId),{once:true}));await page.mouse.move(frameBox.x+start.x,frameBox.y+start.y);await page.mouse.down();assert(await node(id).evaluate(el=>el.hasPointerCapture(Number(el.dataset.testPointer))),'real mouse pointer is captured by the blanket');await page.mouse.move(frameBox.x+start.x+movement.dx,frameBox.y+start.y+movement.dy);await ready();
   if(cancel)await node(id).evaluate(el=>el.dispatchEvent(new PointerEvent('pointercancel',{pointerId:Number(el.dataset.testPointer),pointerType:'mouse',bubbles:true})));await page.mouse.up();await ready();return pose();
  };
  for(const [direction,sofa]of Object.entries(sofas)){
   const initial={direction:'center',x:3,y:4.5,elevation:0,mode:'floor'},baseline={version:13,rooms:[{x:0,y:0,decor:true,curtains:false,shelf:null,furniture:{sofa,[id]:initial}}],diary:'담요 모양 전환 뒤에도 보존할 기록'};
   await page.evaluate(({key,baseline})=>localStorage.setItem(key,JSON.stringify(baseline)),{key,baseline});await open();assert.deepEqual(await read(),baseline);await edit();const floorBefore=await inspect();
   const near={x:sofa.x+.5,y:sofa.y+.5},snapped=expectedSofa(sofa);assert.deepEqual(await dragTo(near),snapped,direction+' floor drag snaps to the authored sofa drape');const sofaDraft=await inspect();assert.notEqual(sofaDraft.geometrySha256,floorBefore.geometrySha256);assert.deepEqual(await read(),baseline);assert.deepEqual(await pose('sofa'),sofa);await f.getByRole('button',{name:'취소',exact:true}).click();assert.deepEqual(await pose(),initial);assert.deepEqual(await read(),baseline);await inspect();
   await edit();assert.deepEqual(await dragTo(near),snapped);await f.getByRole('button',{name:'설치',exact:true}).click();const sofaSaved=structuredClone(baseline);sofaSaved.rooms[0].furniture[id]=snapped;assert.deepEqual(await read(),sofaSaved);await close();await open();assert.deepEqual(await pose(),snapped);await inspect();await f.locator('#overview').click();await capture('sofa-'+direction);await menu();
   const away={x:4,y:4.5};await edit();assert.deepEqual(await dragTo(away,true),snapped,'pointer cancellation restores the installed drape and its mode');assert.deepEqual(await read(),sofaSaved);await f.getByRole('button',{name:'취소',exact:true}).click();await edit();const floorDraft=await dragTo(away);assert.equal(floorDraft.direction,direction);assert.equal(floorDraft.mode,'floor');assert.equal(floorDraft.elevation,0);assert(Math.hypot(floorDraft.x-away.x,floorDraft.y-away.y)<1e-5,'dragging away reaches the floor target');const floorArt=await inspect();assert.deepEqual(await read(),sofaSaved);await f.getByRole('button',{name:'취소',exact:true}).click();assert.deepEqual(await pose(),snapped);assert.deepEqual(await read(),sofaSaved);
   await edit();const installedFloor=await dragTo(away);await f.getByRole('button',{name:'설치',exact:true}).click();const floorSaved=structuredClone(sofaSaved);floorSaved.rooms[0].furniture[id]=installedFloor;assert.deepEqual(await read(),floorSaved);await close();await open();assert.deepEqual(await pose(),installedFloor);await inspect();await f.locator('#overview').click();await capture('floor-'+direction);await menu();assert.deepEqual(await pose('sofa'),sofa);assert.equal(await node('blanket-sofa').count(),0,'mode switching never creates a second blanket');
   report.views.push({direction,floor:floorArt,sofa:sofaDraft,cancel:true,pointerCancel:true,savedAndReopened:true});await close();console.log('BLANKET VIEW PASS:',direction);
  }
  // Moving the independent drape updates its foreground mask without moving a cushion.
  const maskedCushion={direction:'left',x:.33,y:5.45,elevation:.81},maskSave={version:13,rooms:[{x:0,y:0,decor:true,curtains:false,shelf:null,furniture:{sofa:sofas.left,[id]:expectedSofa(sofas.left),'cream-floral-cushion':maskedCushion}}],diary:'담요 이동은 쿠션 위치를 바꾸지 않아요.'};
  await page.evaluate(({key,maskSave})=>localStorage.setItem(key,JSON.stringify(maskSave)),{key,maskSave});await open();
  const maskSources=()=>node('cream-floral-cushion').locator('canvas').getAttribute('data-sources'),maskImage='assets/blanket-sofa-left-v1.png';
  const initialPixels=await node('cream-floral-cushion').locator('canvas').evaluate(c=>c.toDataURL());assert((await maskSources()).includes(maskImage));
  await edit();await dragTo({x:4,y:4.5});assert(!(await maskSources()).includes(maskImage),'moving the blanket away clears its old foreground mask during the drag');assert.deepEqual(await pose('cream-floral-cushion'),maskedCushion);assert.deepEqual(await read(),maskSave);
  await f.getByRole('button',{name:'취소',exact:true}).click();await ready();assert((await maskSources()).includes(maskImage));assert.equal(await node('cream-floral-cushion').locator('canvas').evaluate(c=>c.toDataURL()),initialPixels);await close();
  report.checks.push('Dragging the drape updates the cushion foreground mask live; cancellation restores exact pixels and the cushion position never changes');
  // Existing floor and sofa copies remain distinct, while the menu stays unified.
  const both={version:12,rooms:[{x:0,y:0,decor:true,curtains:false,shelf:null,furniture:{sofa:{...sofas.center,accessories:{'cream-floral-cushion':false,'sage-cushion':false,'peach-cushion':false,'pink-check-cushion':false,'blanket-sofa':true}},'blanket-floor':{direction:'center',x:3,y:4.5}}}],diary:'기존 담요 두 개는 그대로 보존해요.'};
  await page.evaluate(({key,both})=>localStorage.setItem(key,JSON.stringify(both)),{key,both});await open();assert.equal(await node('blanket-floor').count(),1);assert.equal(await node('blanket-sofa').count(),1);await menu();assert.equal((await pose('blanket-floor')).mode,'floor');assert.equal((await pose('blanket-sofa')).mode,'sofa');assert.deepEqual(await read(),both,'opening alone does not rewrite the original saved room');await inspect('blanket-floor');await inspect('blanket-sofa');await close();const migrated=await read();assert.equal(migrated.version,13);assert.equal(Object.keys(migrated.rooms[0].furniture).filter(id=>id.startsWith('blanket-')).length,2);await open();assert.deepEqual(await read(),migrated);await menu();await close();
  // Mobile controls and legacy duplicate removal use the same single menu.
  await page.setViewportSize({width:375,height:812});await open();await edit();
  assert.equal(await f.locator('#accessory-height').count(),0,'blanket height follows its mode automatically');
  const mobile=await f.evaluate(()=>({width:innerWidth,scroll:document.documentElement.scrollWidth}));assert.equal(mobile.width,mobile.scroll);
  await capture('mobile-blanket-controls');await f.getByRole('button',{name:'취소',exact:true}).click();assert.deepEqual(await read(),migrated);
  await edit();await f.getByRole('button',{name:'회수',exact:true}).click();await close();await open();assert.equal(await node('blanket-floor').count(),0);assert.equal(await node('blanket-sofa').count(),1);await menu();
  await node('blanket-sofa').dispatchEvent('click');await ready();await f.getByRole('button',{name:'회수',exact:true}).click();await close();await open();assert.equal(await node('blanket-sofa').count(),0);assert.equal(await node('blanket-floor').count(),0);await menu();
  await edit();await f.getByRole('button',{name:'취소',exact:true}).click();assert.equal(await node('blanket-floor').count(),0,'cancel does not recreate a removed blanket');
  await edit();const fresh=await pose();await f.getByRole('button',{name:'설치',exact:true}).click();await close();await open();assert.deepEqual(await pose(),fresh);assert.equal(await node('blanket-sofa').count(),0);await menu();await close();
  report.checks.push('375px controls fit; removing either old blanket preserves its peer, removing both stays removed, explicit re-add and cancel preserve a single menu');
  report.checks.push('All three original floor PNGs and sofa drape PNGs switch through real pointer movement without duplicating the menu item','Draft cancellation and pointer cancellation restore the exact previous mode; installation and reopening preserve both modes','Legacy rooms containing both blankets keep both scene items while exposing one menu entry');assert.deepEqual(report.errors,[]);assert.deepEqual(report.missing,[]);report.status='passed';
 }catch(error){report.status='failed';report.failure=error.stack;if(page)await page.screenshot({path:path.join(proof,'failure.png')}).catch(()=>{});throw error;}
 finally{fs.writeFileSync(path.join(proof,'report.json'),JSON.stringify(report,null,2)+'\n');await browser.close();console.log(JSON.stringify({status:report.status,checks:report.checks,failure:report.failure,proof},null,2));}
})().catch(error=>{console.error(error);process.exitCode=1;});
