const {chromium}=require('playwright'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
(async()=>{const browser=await chromium.launch({headless:true,executablePath:process.env.PLAYWRIGHT_CHROMIUM_EXECUTABLE_PATH,args:['--no-sandbox']});try{
const context=await browser.newContext({viewport:{width:390,height:844}}),errors=[];
await context.route('http://127.0.0.1:8875/**',r=>{const name=new URL(r.request().url()).pathname;const file=path.join(__dirname,'..',name);return fs.existsSync(file)?r.fulfill({contentType:name.endsWith('.js')?'application/javascript':'text/html',body:fs.readFileSync(file)}):r.fulfill({status:404,body:'Not found'});});
await context.route('https://fonts.googleapis.com/**',r=>r.fulfill({body:''}));
await context.route('http://127.0.0.1:8875/fixture',r=>r.fulfill({contentType:'text/html',body:'<meta charset="utf-8"><button id="open">땅따먹기</button><script src="/ttang-bridge.js"></script><script>window.allowed=true;window.scores=[];document.querySelector("button").onclick=()=>OjjudaTtangBridge.open({owner:"member-a",authorized:()=>allowed,onScore:async score=>{scores.push(score);return {ok:true}}});</script>'}));
const page=await context.newPage();page.on('pageerror',e=>{errors.push(e.message);console.error('PAGE',e.message)});await page.goto('http://127.0.0.1:8875/fixture');await page.click('#open');
const frame=await (await page.locator('iframe').elementHandle()).contentFrame();await frame.waitForSelector('#soloBtn');
if(process.env.TTANG_PROOF_FONT){const css='@font-face{font-family:QuotedProof;src:url(data:font/ttf;base64,'+fs.readFileSync(process.env.TTANG_PROOF_FONT).toString('base64')+')}body,button{font-family:QuotedProof,sans-serif!important}';await page.addStyleTag({content:css});await frame.addStyleTag({content:css.replaceAll('QuotedProof','Gowun Dodum')});await frame.evaluate(()=>document.fonts.ready);await page.evaluate(()=>document.fonts.ready);}
for(const [width,height] of [[320,568],[390,844],[844,390]]){await page.setViewportSize({width,height});assert.equal(await frame.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);assert.equal(await frame.locator('#soloBtn').isVisible(),true);await frame.locator('summary').click();assert.equal(await frame.locator('.how').isVisible(),true);await frame.locator('summary').click();}
await page.setViewportSize({width:390,height:844});await page.screenshot({path:'/tmp/ttang-menu.png'});
await frame.click('#soloBtn');await frame.waitForSelector('#hud',{state:'visible'});await page.waitForTimeout(600);await page.screenshot({path:'/tmp/ttang-play.png'});
await frame.click('#pause');assert.equal(await frame.getByText('잠깐 쉬는 중').isVisible(),true);await frame.click('#go');
await frame.evaluate(()=>{world.kill(me,0,'end');});await page.waitForFunction(()=>scores.length===1);assert.equal(await page.locator('#ttang-save-status').innerText(),(await page.evaluate(()=>scores[0]))+'점 · 기록했어요!');
await frame.evaluate(()=>sendResult({mode:'solo',score:123}));await page.waitForTimeout(100);assert.equal(await page.evaluate(()=>scores.length),1,'duplicate round ignored');
await frame.click('#again');await frame.waitForSelector('#hud',{state:'visible'});await frame.evaluate(()=>parent.postMessage({type:'ojjuda:ttang:result',mode:'solo',round:roundId,score:1001},location.origin));await page.waitForTimeout(100);assert.equal(await page.evaluate(()=>scores.length),1,'invalid score rejected');
await page.evaluate(()=>window.allowed=false);await page.waitForSelector('#ttang-overlay',{state:'detached'});assert.equal(await page.evaluate(()=>document.body.classList.contains('gaming')),false);
await page.evaluate(()=>window.allowed=true);await page.click('#open');await page.getByRole('button',{name:'땅따먹기 닫기'}).click();assert.equal(await page.locator('iframe').count(),0);
// Two isolated game frames exercise the bundled transport and synchronization.
const host=await context.newPage(),guest=await context.newPage();for(const p of [host,guest]){p.on('pageerror',e=>errors.push(e.message));await p.goto('http://127.0.0.1:8875/games/ttang.html');await p.click('#duoBtn');assert.equal(await p.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);}
await host.click('#mk');await host.waitForFunction(()=>Net.tr?.kind==='local');const code=await host.locator('.overlay:not(#menu) h2 span').innerText();await guest.fill('#code',code);await guest.click('#jn');await host.waitForFunction(()=>mode==='net'&&role==='host');await guest.waitForFunction(()=>mode==='net'&&role==='guest');await guest.waitForTimeout(400);assert.equal(await guest.evaluate(()=>world.players.length),await host.evaluate(()=>world.players.length));await host.evaluate(()=>OjjudaTtang.menu());await guest.getByText('친구가 나갔어요').waitFor();assert.deepEqual(errors,[]);
console.log('PASS: mobile/landscape layout, playable solo round, pause/resume, result save, duplicate and invalid results, account change cleanup, close');
}finally{await browser.close();}})().catch(e=>{console.error(e);process.exitCode=1});
