const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),{chromium}=require('playwright');
(async()=>{const browser=await chromium.launch({headless:true,executablePath:process.env.PLAYWRIGHT_CHROMIUM_EXECUTABLE_PATH,args:['--no-sandbox']});try{
 const page=await browser.newPage({viewport:{width:390,height:844}}),errors=[];page.on('pageerror',e=>errors.push(e.message));let requests=0,mode='ok',pending=[];
 const weather=temp=>({properties:{timeseries:Array.from({length:4},(_,i)=>({time:`2028-02-15T${String(12+i).padStart(2,'0')}:00:00Z`,data:{instant:{details:{air_temperature:temp+i}},next_1_hours:{summary:{symbol_code:'clearsky_day'}}}}))}});
 await page.route('https://api.met.no/**',async route=>{requests++;if(mode==='hold'){pending.push(route);return;}if(mode==='error')return route.fulfill({status:503,body:'offline'});return route.fulfill({contentType:'application/json',body:JSON.stringify(weather(21))});});
 await page.route('https://fixture.test/**',route=>route.fulfill({contentType:'text/html',body:'<html><meta charset="utf-8"><style>body{margin:0;padding:14px;background:#edeff9;font-family:sans-serif}</style><main data-life-root></main></html>'}));
 await page.goto('https://fixture.test/');if(process.env.WORLD_LIFE_PROOF_FONT)await page.addStyleTag({content:'@font-face{font-family:LifeProof;src:url(data:font/ttf;base64,'+fs.readFileSync(process.env.WORLD_LIFE_PROOF_FONT).toString('base64')+')}body,button,input,select{font-family:LifeProof,sans-serif!important}'});await page.clock.install({time:new Date('2028-02-15T12:00:00Z')});await page.addStyleTag({path:path.join(__dirname,'../world-life.css')});await page.addScriptTag({path:path.join(__dirname,'../world-life.js')});
 await page.evaluate(()=>{localStorage.setItem('ojjuda-life-v1:a','saved old contacts');window.permissionRequests=0;Object.defineProperty(navigator,'geolocation',{configurable:true,value:{getCurrentPosition(ok,fail){permissionRequests++;fail({code:1});}}});window.mount=owner=>OjjudaLife.mount(document.querySelector('main'),{owner});mount('a');});
 assert.equal(await page.locator('[data-life-tool=contacts]').count(),0);assert.equal(await page.evaluate(()=>localStorage.getItem('ojjuda-life-v1:a')),'saved old contacts');assert.equal(requests,0,'closed weather does not fetch');assert.equal(await page.evaluate(()=>permissionRequests),0,'no unsolicited geolocation');
 const cal=page.locator('[data-life-tool=calendar]');assert.equal(await cal.locator('[data-date]').count(),29,'leap February');await cal.getByRole('button',{name:'다음 달',exact:true}).click();assert.equal(await cal.locator('[data-date]').count(),31);await cal.getByRole('button',{name:'이전 달',exact:true}).click();await cal.locator('[data-date="2028-02-29"]').click();assert.equal(await cal.locator('[aria-pressed=true]').getAttribute('data-date'),'2028-02-29');await cal.getByRole('button',{name:'오늘',exact:true}).click();assert.equal(await cal.locator('[aria-current=date]').getAttribute('data-date'),'2028-02-15');
 const w=page.locator('[data-life-tool=weather]');await w.locator('summary').click();await w.locator('.life-weather-now').waitFor();assert.ok((await w.innerText()).includes('21°'),await w.innerText());assert.equal(await w.locator('.life-weather-days>div').count(),3);await w.getByRole('button',{name:'내 위치',exact:true}).click();assert.ok((await w.innerText()).includes('위치 권한'));assert.equal(await page.evaluate(()=>permissionRequests),1);
 mode='hold';await w.getByLabel('지역',{exact:true}).selectOption('1');await page.waitForFunction(()=>document.querySelector('.life-status').textContent.includes('부산'));await w.getByLabel('지역',{exact:true}).selectOption('2');await new Promise(r=>setTimeout(r,100));assert.equal(pending.length,2);await pending[1].fulfill({contentType:'application/json',body:JSON.stringify(weather(26))});await w.locator('.life-weather-now').waitFor();await pending[0].fulfill({contentType:'application/json',body:JSON.stringify(weather(9))}).catch(()=>{});assert.ok((await w.innerText()).includes('대구'));assert.ok((await w.innerText()).includes('26°'),'newest city wins');
 mode='error';await w.getByRole('button',{name:'새로고침',exact:true}).click();await page.waitForFunction(()=>document.querySelector('.life-status').textContent.includes('불러오지 못'));assert.equal(await w.locator('.life-weather-now').count(),0,'no fake weather on failure');mode='ok';await w.getByRole('button',{name:'새로고침',exact:true}).click();await w.locator('.life-weather-now').waitFor();
 await page.locator('[data-life-tool=news] summary').click();const links=await page.locator('.life-news-grid a').evaluateAll(as=>as.map(a=>({url:a.href,target:a.target,rel:a.rel})));assert.equal(links.length,8);assert.ok(links.every(a=>a.url.startsWith('https://')&&a.target==='_blank'&&a.rel.includes('noopener')));
 for(const width of [320,390,1280]){await page.setViewportSize({width,height:844});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);}
 await page.setViewportSize({width:390,height:844});await page.screenshot({path:'/tmp/life-daily-tools.png',fullPage:true});
 mode='hold';await w.getByRole('button',{name:'새로고침',exact:true}).click();await new Promise(r=>setTimeout(r,100));await page.evaluate(()=>mount('b'));assert.equal(await page.locator('.life-weather-now').count(),0,'account switch clears old weather');await pending.at(-1).fulfill({contentType:'application/json',body:JSON.stringify(weather(99))}).catch(()=>{});assert.equal(await page.locator('.life-weather-now').count(),0,'stale request cannot repaint new account');assert.deepEqual(errors,[]);
 console.log('PASS: leap-month calendar, today and selection, contacts removed without data deletion, lazy weather, location denial, out-of-order responses, retry, safe news links, responsive layout and account cleanup');
}finally{await browser.close();}})().catch(e=>{console.error(e);process.exitCode=1});
