const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),{chromium}=require('playwright');
const root=path.resolve(__dirname,'..'),fixture=require('./ledger-fixture.cjs').toString();
const html=`<!doctype html><html lang="ko"><meta charset="utf-8"><meta name="viewport" content="width=device-width"><style>${fs.readFileSync(path.join(root,'world-life.css'),'utf8')}</style><main data-life-root><details open class="life-tool"><summary>가계부</summary><div id="ledger" class="life-tool-body"></div></details></main><script>window.owner='10000000-0000-0000-0000-000000000001';window.client=(${fixture})(()=>owner);</script><script>${fs.readFileSync(path.join(root,'world-ledger.js'),'utf8')}</script><script>window.show=()=>{window.close?.();document.querySelector('#ledger').replaceChildren();const captured=owner;window.close=OjjudaLedger.mount(document.querySelector('#ledger'),{owner,client,authorized:()=>owner===captured});};show();</script>`;
(async()=>{const browser=await chromium.launch({headless:true,executablePath:process.env.PLAYWRIGHT_CHROMIUM_EXECUTABLE_PATH||undefined,args:['--no-sandbox']});try{
 const context=await browser.newContext({viewport:{width:390,height:844}});await context.route('**/*',r=>r.fulfill({contentType:'text/html',body:html}));const page=await context.newPage(),errors=[];page.on('pageerror',e=>errors.push(e.message));await page.goto('https://ledger.test/');
 const field=n=>page.getByLabel(n,{exact:true}),status=()=>page.locator('[role=status]');await page.waitForFunction(()=>document.querySelectorAll('.life-totals strong').length===3);
 await field('날짜').fill('2026-10-04');await field('내용').fill('점심');await field('금액').fill('9000');await field('분류').selectOption('식비');
 await page.evaluate(()=>client.control.fail=true);await page.getByRole('button',{name:'가계부 저장',exact:true}).click();await status().filter({hasText:'저장하지 못'}).waitFor();assert.equal(await field('내용').inputValue(),'점심');
 await page.getByRole('button',{name:'가계부 저장',exact:true}).click();await status().filter({hasText:'내 계정에 저장'}).waitFor();assert.deepEqual(await page.locator('.life-totals strong').allTextContents(),['0원','9,000원','-9,000원']);assert.equal(await page.locator('.ledger-category strong').textContent(),'9,000원');
 await page.getByRole('button',{name:'점심 내역 수정'}).click();await field('금액').fill('10000');await page.getByRole('button',{name:'수정 저장'}).click();await status().filter({hasText:'내 계정에 저장'}).waitFor();assert.equal(await page.locator('.life-row').count(),1);
 await page.getByRole('button',{name:'점심 내역 수정'}).click();await page.evaluate(()=>{const rows=JSON.parse(localStorage.getItem('fixture-cloud-ledger'));rows[0].revision=crypto.randomUUID();rows[0].amount=12000;localStorage.setItem('fixture-cloud-ledger',JSON.stringify(rows));});await field('금액').fill('11000');await page.getByRole('button',{name:'수정 저장'}).click();await status().filter({hasText:'다른 곳에서 바뀐'}).waitFor();assert.equal(await field('금액').inputValue(),'11000');await page.getByRole('button',{name:'수정 취소'}).click();await page.getByRole('button',{name:'새로고침'}).click();await page.waitForFunction(()=>document.querySelector('.life-row').textContent.includes('12,000원'));
 // Legacy imports are copies and re-imports cannot resurrect a deleted entry.
 await page.evaluate(()=>localStorage.setItem('ojjuda-life-v1:'+owner,JSON.stringify({contacts:[],entries:[{id:'20000000-0000-0000-0000-000000000001',date:'2026-10-04',memo:'예전 기록',type:'income',amount:50000}]})));await page.evaluate(()=>show());await page.getByRole('button',{name:'이 기기의 기존 기록 가져오기'}).click();await status().filter({hasText:'기존 기록을 가져왔'}).waitFor();assert.equal(await page.locator('.life-row').count(),2);await page.getByRole('button',{name:'예전 기록 내역 삭제'}).click();await page.getByRole('button',{name:'삭제하기',exact:true}).click();await status().filter({hasText:'삭제했'}).waitFor();await page.getByRole('button',{name:'이 기기의 기존 기록 가져오기'}).click();await status().filter({hasText:'기존 기록을 가져왔'}).waitFor();assert.equal(await page.locator('.life-row').count(),1);assert.equal(await page.evaluate(()=>JSON.parse(localStorage.getItem('ojjuda-life-v1:'+owner)).entries.length),1);
 // Every page shares the whole-month summary; fetching page 2 cannot double it.
 await page.evaluate(()=>{const rows=[];for(let i=0;i<70;i++)rows.push({id:crypto.randomUUID(),user_id:owner,date:'2026-10-04',type:'expense',memo:'기록 '+i,category:'교통',amount:100,revision:crypto.randomUUID(),deleted_at:null});localStorage.setItem('fixture-cloud-ledger',JSON.stringify(rows));});await page.getByRole('button',{name:'새로고침'}).click();await page.waitForFunction(()=>document.querySelectorAll('.life-row').length===30);assert.equal((await page.locator('.life-totals strong').allTextContents())[1],'7,000원');await page.getByRole('button',{name:'더보기',exact:true}).click();await page.waitForFunction(()=>document.querySelectorAll('.life-row').length===60);await page.getByRole('button',{name:'더보기',exact:true}).click();await page.waitForFunction(()=>document.querySelectorAll('.life-row').length===70);assert.equal((await page.locator('.life-totals strong').allTextContents())[1],'7,000원');
 for(const width of [320,390,760]){await page.setViewportSize({width,height:844});assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));}
 // Delayed old-account data is discarded after account change.
 await page.evaluate(()=>{client.control.delay=150;document.querySelector('.ledger-toolbar button').click();owner='10000000-0000-0000-0000-000000000002';show();});await page.waitForFunction(()=>document.querySelectorAll('.life-totals strong').length===3);assert.equal(await page.locator('.life-row').count(),0);assert.equal((await page.locator('.life-totals strong').allTextContents())[1],'0원');
 await page.evaluate(()=>{owner=null;show();});assert.equal(await page.locator('input').count(),0);assert.deepEqual(errors,[]);
 console.log('PASS: cloud save retry, edits and conflicts, category totals, copy/import idempotency, deleted imports, pagination, mobile widths and account-switch race');
}finally{await browser.close();}})().catch(e=>{console.error(e);process.exitCode=1});
