const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),{chromium}=require('playwright');
(async()=>{const browser=await chromium.launch({headless:true,executablePath:process.env.PLAYWRIGHT_CHROMIUM_EXECUTABLE_PATH,args:['--no-sandbox']});try{
 const page=await browser.newPage({viewport:{width:390,height:844}}),errors=[];page.on('pageerror',e=>errors.push(e.message));
 await page.route('https://fixture.test/**',route=>route.fulfill({contentType:'text/html',body:'<!doctype html><meta charset="utf-8"><style>body{margin:0;padding:14px;background:#edeff9;font-family:sans-serif}</style><main data-life-root></main>'}));await page.goto('https://fixture.test/');await page.clock.install({time:new Date('2028-02-15T12:00:00Z')});
 await page.addStyleTag({path:path.join(__dirname,'../world-life.css')});if(process.env.WORLD_LIFE_PROOF_FONT)await page.addStyleTag({content:'@font-face{font-family:LifeProof;src:url(data:font/ttf;base64,'+fs.readFileSync(process.env.WORLD_LIFE_PROOF_FONT).toString('base64')+')}body,button,input,select,textarea{font-family:LifeProof,sans-serif!important}'});
 await page.addScriptTag({content:'window.createScheduleFixture='+require('./schedule-fixture.cjs').toString()});await page.addScriptTag({path:path.join(__dirname,'../world-schedule.js')});await page.addScriptTag({path:path.join(__dirname,'../world-life.js')});
 await page.evaluate(()=>{window.owner='member-a';window.client=createScheduleFixture(()=>owner);window.mount=()=>OjjudaLife.mount(document.querySelector('main'),{owner,client,authorized:()=>true});mount();});
 const schedule=page.locator('.life-schedule'),form=schedule.locator('form'),status=schedule.locator('[role=status]');await schedule.getByText('이 날짜에 등록한 일정이 없어요.',{exact:true}).waitFor();
 const open=()=>schedule.getByRole('button',{name:'＋ 일정 추가',exact:true}).click();
 const fill=async(date,title,repeat='none',end='')=>{await form.getByLabel('일정 날짜',{exact:true}).fill(date);await form.getByLabel('일정 제목',{exact:true}).fill(title);await form.getByLabel('반복',{exact:true}).selectOption(repeat);if(repeat!=='none')await form.getByLabel('반복 종료일 (선택)',{exact:true}).fill(end);};
 const save=async()=>{await form.getByRole('button',{name:/^(일정 저장|수정 저장)$/}).click();await status.filter({hasText:'내 계정에 일정을 저장했어요.'}).waitFor();};
 await open();await fill('2028-02-15','치과 예약');await form.getByLabel('시간 (선택·한국 시간)',{exact:true}).fill('14:30');await form.getByLabel('메모',{exact:true}).fill('<img src=x onerror=alert(1)> 준비물');await save();assert.equal(await schedule.locator('.schedule-event').count(),1);assert.ok((await schedule.innerText()).includes('14:30'));assert.equal(await schedule.locator('img').count(),0);assert.equal(await page.locator('[data-date="2028-02-15"].has-schedule').count(),1);
 await schedule.getByRole('button',{name:'치과 예약 일정 수정',exact:true}).click();await form.getByLabel('일정 제목',{exact:true}).fill('치과 변경');await save();assert.equal(await schedule.getByRole('button',{name:'치과 변경 일정 수정',exact:true}).count(),1);
 await open();await fill('2028-02-15','주간 운동','weekly','2028-02-29');await save();assert.equal(await page.locator('[data-date="2028-02-22"].has-schedule').count(),1);await page.locator('[data-date="2028-02-22"]').click();assert.ok((await schedule.innerText()).includes('주간 운동'));assert.equal(await schedule.locator('.schedule-event').count(),1);
 await open();await fill('2028-01-31','월말 정리','monthly');await save();await page.getByRole('button',{name:'다음 달',exact:true}).click();assert.equal(await page.locator('.has-schedule[data-date^="2028-02"]').count(),3,'monthly 31st skips February; only weekly dates marked');await page.getByRole('button',{name:'다음 달',exact:true}).click();assert.equal(await page.locator('[data-date="2028-03-31"].has-schedule').count(),1);assert.equal(await page.locator('[data-date="2028-03-07"].has-schedule').count(),0,'weekly repeat stops at end date');await page.locator('[data-date="2028-03-31"]').click();
 await schedule.getByRole('button',{name:'월말 정리 일정 삭제',exact:true}).click();await schedule.getByText('이 반복 일정 전체를 삭제할까요?',{exact:true}).waitFor();await schedule.getByRole('button',{name:'삭제하기',exact:true}).click();await status.filter({hasText:'일정을 삭제했어요.'}).waitFor();assert.equal(await page.locator('[data-date="2028-03-31"].has-schedule').count(),0);
 await open();await fill('2028-03-20','연결 복구 후 저장');await page.evaluate(()=>client.control.lost=true);await form.getByRole('button',{name:'일정 저장',exact:true}).click();await status.filter({hasText:'저장하지 못했어요.'}).waitFor();assert.equal(await form.getByLabel('일정 제목',{exact:true}).inputValue(),'연결 복구 후 저장');await save();assert.equal(await page.evaluate(()=>JSON.parse(localStorage.getItem('fixture-cloud-schedule')).filter(r=>r.title==='연결 복구 후 저장').length),1,'lost response retry does not duplicate');
 await schedule.getByRole('button',{name:'연결 복구 후 저장 일정 수정',exact:true}).click();await form.getByLabel('일정 제목',{exact:true}).fill('늦은 변경');await page.evaluate(()=>{const rows=JSON.parse(localStorage.getItem('fixture-cloud-schedule'));const r=rows.find(r=>r.title==='연결 복구 후 저장');r.title='다른 기기에서 수정';r.revision=crypto.randomUUID();localStorage.setItem('fixture-cloud-schedule',JSON.stringify(rows));});await form.getByRole('button',{name:'수정 저장',exact:true}).click();await status.filter({hasText:'다른 기기에서 바뀐 일정'}).waitFor();assert.equal(await form.getByLabel('일정 제목',{exact:true}).inputValue(),'늦은 변경');await form.getByRole('button',{name:'취소',exact:true}).click();await schedule.getByRole('button',{name:'일정 새로고침',exact:true}).click();await schedule.getByText('다른 기기에서 수정',{exact:true}).waitFor();
 await open();await fill('2028-03-20','작성 중');await page.evaluate(()=>{OjjudaLife.mount(null);mount();});assert.equal(await form.getByLabel('일정 제목',{exact:true}).inputValue(),'작성 중','tab remount preserves draft');await form.getByRole('button',{name:'취소',exact:true}).click();
 await page.evaluate(()=>{const rows=JSON.parse(localStorage.getItem('fixture-cloud-schedule'));for(let i=0;i<205;i++)rows.push({id:crypto.randomUUID(),user_id:owner,date:'2028-03-20',time:null,title:'대량 '+i,memo:'',repeat:'none',repeat_until:null,revision:crypto.randomUUID(),deleted_at:null});localStorage.setItem('fixture-cloud-schedule',JSON.stringify(rows));});await schedule.getByRole('button',{name:'일정 새로고침',exact:true}).click();await page.waitForFunction(()=>document.querySelectorAll('.schedule-event').length===206);
 for(const width of [320,390,1280]){await page.setViewportSize({width,height:844});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);}
 await page.evaluate(()=>{let rows=JSON.parse(localStorage.getItem('fixture-cloud-schedule'));rows=rows.filter(r=>!r.title.startsWith('대량 '));localStorage.setItem('fixture-cloud-schedule',JSON.stringify(rows));});await schedule.getByRole('button',{name:'일정 새로고침',exact:true}).click();await page.waitForFunction(()=>document.querySelectorAll('.schedule-event').length===1);await page.setViewportSize({width:390,height:844});await page.screenshot({path:'/tmp/life-schedule.png',fullPage:true});
 await page.evaluate(()=>{client.control.delay=300;document.querySelector('.schedule-toolbar button:last-child').click();owner='member-b';mount();});await page.waitForTimeout(500);assert.equal(await schedule.locator('.schedule-event').count(),0,'account switch discards stale account response');assert.equal(await page.locator('.has-schedule').count(),0);await page.evaluate(()=>{owner=null;mount();});assert.equal(await schedule.locator('form').count(),0);assert.ok((await schedule.innerText()).includes('로그인하면'));assert.deepEqual(errors,[]);
 console.log('PASS: schedule CRUD, calendar dots, weekly end dates, monthly 31st skip, XSS-safe text, idempotent retry, conflict protection, draft persistence, pagination, mobile layout, stale-account and guest cleanup');
}finally{await browser.close();}})().catch(e=>{console.error(e);process.exitCode=1});
