const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
const {chromium}=require('playwright'),root=path.resolve(__dirname,'..');
const proof=process.env.HOUSE_PUBLIC_PROOF_DIR||path.resolve(root,'../house-public-proof'),proofFont=process.env.HOUSE_PUBLIC_PROOF_FONT;
let world=fs.readFileSync(path.join(root,'world.html'),'utf8').replace(/<script\b[^>]*\bsrc=[^>]*>\s*<\/script>/g,'').replace('import { screw3d as screwGame } from "./screw3d.js";','const screwGame={};');
world=world.replace('<script type="module">',`<script>${fs.readFileSync(path.join(root,'world-navigation.js'),'utf8')}\n${fs.readFileSync(path.join(root,'world-life.js'),'utf8')}</script><script type="module">`);
const boot=world.indexOf('j1(()=>H());gm(');assert(boot>0);
world=world.slice(0,boot)+`
window.houseWorldTest={state:g,auth:D,actions:sr,render:H};
U.cleanupMedia=async()=>({});U.overview=async()=>({});U.contentFeed=async()=>[];U.chatFeed=async()=>[];
S={auth:{signOut:async()=>{sessionStorage.setItem('fixture-logged-out','yes');D.user=null;D.online=false;D.isAdmin=false;H();}}};
gm(()=>{g.tab='friends';g.visiting=null;g.visitData=null;H();window.scrollTo(0,0)});
D.online=!sessionStorage.getItem('fixture-logged-out');D.user=D.online?{id:'world-member-a'}:null;D.isAdmin=false;g.tab='friends';H();
`+world.slice(world.indexOf('</script>',boot));
(async()=>{
 const browser=await chromium.launch({headless:true,executablePath:process.env.PLAYWRIGHT_CHROMIUM_EXECUTABLE_PATH||undefined,args:['--no-sandbox']});
 try{
  const context=await browser.newContext({viewport:{width:390,height:844},isMobile:true,hasTouch:true});
  await context.route('**/*',route=>{const u=new URL(route.request().url());if(u.hostname!=='fixture.test')return route.abort();if(u.pathname==='/life-proof.ttf'&&process.env.WORLD_LIFE_PROOF_FONT)return route.fulfill({path:process.env.WORLD_LIFE_PROOF_FONT});if(u.pathname==='/world.html')return route.fulfill({contentType:'text/html',body:world});const file=path.resolve(root,'.'+u.pathname);return file.startsWith(root+path.sep)&&fs.existsSync(file)&&fs.statSync(file).isFile()?route.fulfill({path:file}):route.abort();});
  if(process.env.WORLD_LIFE_PROOF_FONT)await context.addInitScript(()=>document.addEventListener('DOMContentLoaded',()=>{const s=document.createElement('style');s.textContent='@font-face{font-family:LifeProof;src:url(/life-proof.ttf)}html,body,button,input,textarea,select{font-family:LifeProof,sans-serif!important}';document.head.append(s);},{once:true}));
  const page=await context.newPage(),errors=[];page.on('pageerror',e=>errors.push(e.message));await page.goto('https://fixture.test/world.html');await page.waitForFunction(()=>window.houseWorldTest);
  const life=()=>page.evaluate(()=>houseWorldTest.actions.tab({tab:'life'})),status=text=>page.locator('[data-life-root] [role="status"]').filter({hasText:text}).waitFor();await life();
  assert.deepEqual(await page.locator('.bottomnav button > span:first-of-type').allTextContents(),['동네','우리집','생활','메뉴']);assert.deepEqual(await page.locator('[data-life-tool]').evaluateAll(els=>els.map(e=>e.dataset.lifeTool)),['contacts','ledger','calculator']);assert.equal(await page.locator('.bottomnav [data-tab="life"]').getAttribute('aria-current'),'page');
  for(const width of [320,390,1280]){await page.setViewportSize({width,height:844});assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));if(width<900)assert(await page.locator('.bottomnav button').evaluateAll(nodes=>new Set(nodes.map(n=>Math.round(n.getBoundingClientRect().top))).size===1));}
  await page.setViewportSize({width:390,height:844});if(process.env.WORLD_LIFE_PROOF_DIR){fs.mkdirSync(process.env.WORLD_LIFE_PROOF_DIR,{recursive:true});await page.evaluate(()=>document.fonts.ready);await page.screenshot({path:path.join(process.env.WORLD_LIFE_PROOF_DIR,'life-overview.png')});}const contacts=page.locator('[data-life-tool="contacts"]'),ledger=page.locator('[data-life-tool="ledger"]'),calc=page.locator('[data-life-tool="calculator"]');await contacts.locator('summary').click();await contacts.getByLabel('이름',{exact:true}).fill('민준');await contacts.getByLabel('전화번호',{exact:true}).fill('010-1234-5678');
  await page.evaluate(()=>{window.originalSave=Storage.prototype.setItem;Storage.prototype.setItem=function(k,v){if(k.startsWith('ojjuda-life-'))throw Error('quota');return originalSave.call(this,k,v);};});await contacts.getByRole('button',{name:'연락처 저장'}).click();await status('저장 공간');assert.equal(await contacts.getByLabel('이름',{exact:true}).inputValue(),'민준');await page.evaluate(()=>Storage.prototype.setItem=originalSave);await contacts.getByRole('button',{name:'연락처 저장'}).click();await status('이 기기에 저장');assert.equal(await contacts.getByRole('link',{name:'010-1234-5678'}).getAttribute('href'),'tel:01012345678');
  await contacts.getByLabel('이름',{exact:true}).fill('중복');await contacts.getByLabel('전화번호',{exact:true}).fill('01012345678');await contacts.getByRole('button',{name:'연락처 저장'}).click();await status('이미 저장');await contacts.getByLabel('연락처 검색').fill('없는 사람');assert.equal(await contacts.locator('.life-row').count(),0);await contacts.getByLabel('연락처 검색').fill('');await contacts.getByRole('button',{name:'민준 연락처 삭제'}).click();await contacts.getByRole('button',{name:'취소',exact:true}).click();assert.equal(await contacts.locator('.life-row').count(),1);
  await ledger.locator('summary').click();await ledger.getByLabel('내용',{exact:true}).fill('점심');await ledger.getByLabel('금액',{exact:true}).fill('9000');await ledger.getByLabel('날짜',{exact:true}).fill('2026-10-04');await ledger.getByRole('button',{name:'가계부 저장'}).click();await status('이 기기에 저장');await ledger.getByLabel('수입·지출').selectOption('income');await ledger.getByLabel('내용',{exact:true}).fill('용돈');await ledger.getByLabel('금액',{exact:true}).fill('20000');await ledger.getByRole('button',{name:'가계부 저장'}).click();assert.deepEqual(await ledger.locator('.life-totals strong').allTextContents(),['20,000원','9,000원','11,000원']);await ledger.getByLabel('조회할 월').fill('2026-09');assert.equal(await ledger.locator('.life-row').count(),0);await ledger.getByLabel('조회할 월').fill('2026-10');assert.equal(await ledger.locator('.life-row').count(),2);
  await ledger.getByLabel('내용',{exact:true}).fill('작성 중인 내역');await page.locator('.bottomnav [data-tab="my"]').click();await life();assert.equal(await ledger.getByLabel('내용',{exact:true}).inputValue(),'작성 중인 내역','unsaved entry survives tab switches');
  await calc.locator('summary').click();const key=k=>calc.getByRole('button',{name:k,exact:true}).click();for(const k of ['0','.','1','+','0','.','2','='])await key(k);assert.equal(await calc.locator('output').textContent(),'0.3');for(const k of ['C','9','÷','0','='])await key(k);assert.equal(await calc.locator('output').textContent(),'계산할 수 없어요');for(const k of ['C','2','+','3','×','4','='])await key(k);assert.equal(await calc.locator('output').textContent(),'20');
  await page.reload();await page.waitForFunction(()=>window.houseWorldTest);await life();await contacts.locator('summary').click();assert.equal(await contacts.locator('.life-row').count(),1,'contacts persist after reload');await ledger.locator('summary').click();assert.equal(await ledger.locator('.life-row').count(),2,'ledger persists after reload');
  await page.evaluate(()=>{houseWorldTest.auth.user={id:'world-member-b'};houseWorldTest.render();});assert.equal(await contacts.locator('.life-row').count(),0);await contacts.locator('summary').click();assert.equal(await contacts.locator('.life-row').count(),0,'new account has no previous account contacts');await page.evaluate(()=>{houseWorldTest.auth.user={id:'world-member-a'};houseWorldTest.render();});assert.equal(await contacts.locator('.life-row').count(),1);
  await page.evaluate(()=>houseWorldTest.actions.tab({tab:'home'}));await page.frameLocator('iframe').locator('#app.records-home').waitFor();let f=page.frames().find(x=>x.url().includes('/house-test/index.html'));await f.waitForFunction(()=>document.querySelector('#app').getClientRects().length);
  const cdp=await context.newCDPSession(page),touch=(type,points)=>cdp.send('Input.dispatchTouchEvent',{type,touchPoints:points.map(([x,y])=>({x,y,id:1}))});
  const swipe=async(locator,dx,dy=0)=>{await locator.scrollIntoViewIfNeeded();const b=await locator.boundingBox(),x=b.x+b.width*(dx<0?.8:.2),y=b.y+Math.min(25,b.height/2);await touch('touchStart',[[x,y]]);for(let i=1;i<=6;i++)await touch('touchMove',[[x+dx*i/6,y+dy*i/6]]);await touch('touchEnd',[]);};
  await swipe(f.locator('#home-profile'),-100);await page.waitForFunction(()=>houseWorldTest.state.tab==='life');assert.equal(await page.locator('iframe').count(),0,'house-record swipe enters the single life page');
  await swipe(page.locator('[data-life-root]>h2'),150);await page.frameLocator('iframe').locator('#app.records-home').waitFor();f=page.frames().find(x=>x.url().includes('/house-test/index.html'));await f.locator('[data-tab="room"]').click();await swipe(f.locator('#viewport'),-120);assert.equal(await page.evaluate(()=>houseWorldTest.state.tab),'home','room gestures never change World tabs');
  await life();await page.evaluate(()=>{houseWorldTest.auth.online=false;houseWorldTest.auth.user=null;houseWorldTest.render();});assert.equal(await contacts.locator('input').count(),0);assert.equal(await ledger.locator('input').count(),0);await calc.locator('summary').click();await key('7');assert.equal(await calc.locator('output').textContent(),'7','guest calculator works without storing personal data');assert.deepEqual(errors,[]);
  console.log('PASS: four menus, one ordered life page, responsive layout, contacts/ledger persistence and isolation, drafts and storage failures, calculator, iframe swipes and room gesture protection');
 }finally{await browser.close();}
})().catch(e=>{console.error(e);process.exitCode=1;});
