const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
const {chromium}=require('playwright'),root=path.resolve(__dirname,'..');
const proof=process.env.HOUSE_PUBLIC_PROOF_DIR||path.resolve(root,'../house-public-proof'),proofFont=process.env.HOUSE_PUBLIC_PROOF_FONT;
let world=fs.readFileSync(path.join(root,'world.html'),'utf8').replace(/<script\b[^>]*\bsrc=[^>]*>\s*<\/script>/g,'').replace('import { screw3d as screwGame } from "./screw3d.js";','const screwGame={};');
world=world.replace('<script type="module">',`<script>${fs.readFileSync(path.join(root,'world-navigation.js'),'utf8')}\n${fs.readFileSync(path.join(root,'world-life.js'),'utf8')}</script><script type="module">`);
const boot=world.indexOf('j1(()=>H());gm(');assert(boot>0);
const storageFixture=`<!doctype html><meta charset="utf-8"><main id="life"></main><script>${fs.readFileSync(path.join(root,'world-life.js'),'utf8')}</script><script>const options={owner:'life-storage-audit'};window.remountLife=()=>OjjudaLife.mount(document.querySelector('main'),options);remountLife();</script>`;
world=world.slice(0,boot)+`
const fixtureRooms=new Map(),fixtureRoomCalls=[],fixtureUnexpected=[];
window.houseWorldTest={state:g,auth:D,actions:sr,render:H,rooms:fixtureRooms,roomCalls:fixtureRoomCalls,unexpected:fixtureUnexpected};
U.cleanupMedia=async()=>({});U.overview=async()=>({});U.contentFeed=async()=>[];U.chatFeed=async()=>[];
// Keep the production World -> room service -> host -> iframe flow. Replace
// only transport, including compare-and-swap room saves and empty record lists.
S={auth:{signOut:async()=>{sessionStorage.setItem('fixture-logged-out','yes');D.user=null;D.online=false;D.isAdmin=false;H();}},
 from(table){const q={select(){return q;},eq(){return q;},in(){return q;},order(){return q;},range(){return q;},then(resolve,reject){if(!['house_records','media_folders','house_friend_groups'].includes(table)){fixtureUnexpected.push(table);return Promise.resolve({data:null,error:{message:'Unexpected fixture table: '+table}}).then(resolve,reject);}return Promise.resolve({data:[],error:null}).then(resolve,reject);}};return q;},
 async rpc(name,args){
  fixtureRoomCalls.push({name,args:structuredClone(args)});
  if(!['house_room_load','house_room_save'].includes(name)){fixtureUnexpected.push(name);return{error:{message:'Unexpected fixture RPC: '+name}};}
  if(args.p_owner!==D.user?.id)return{error:{message:'house_room_not_owner'}};
  const saved=fixtureRooms.get(args.p_owner);
  if(name==='house_room_load')return{data:saved?{ok:true,found:true,canEdit:true,...structuredClone(saved)}:{ok:true,found:false,canEdit:true}};
  if(saved&&JSON.stringify(saved.snapshot)===JSON.stringify(args.p_snapshot))return{data:{ok:true,revision:saved.revision,updatedAt:saved.updatedAt}};
  if((saved?.revision||null)!==args.p_revision)return{data:{ok:false,reason:'conflict'}};
  const next={snapshot:structuredClone(args.p_snapshot),revision:crypto.randomUUID(),updatedAt:new Date().toISOString()};fixtureRooms.set(args.p_owner,next);return{data:{ok:true,revision:next.revision,updatedAt:next.updatedAt}};
 }};
P.loaded=true;P.at=Date.now()+60000;
gm(()=>{g.tab='friends';g.visiting=null;g.visitData=null;H();window.scrollTo(0,0)});
D.online=!sessionStorage.getItem('fixture-logged-out');D.user=D.online?{id:'world-member-a'}:null;D.isAdmin=false;g.tab='friends';H();
`+world.slice(world.indexOf('</script>',boot));
(async()=>{
 const browser=await chromium.launch({headless:true,executablePath:process.env.PLAYWRIGHT_CHROMIUM_EXECUTABLE_PATH||undefined,args:['--no-sandbox']});
 try{
  const context=await browser.newContext({viewport:{width:390,height:844},isMobile:true,hasTouch:true});
  await context.route('**/*',route=>{const u=new URL(route.request().url());if(u.hostname!=='fixture.test')return route.abort();if(u.pathname==='/life-proof.ttf'&&process.env.WORLD_LIFE_PROOF_FONT)return route.fulfill({path:process.env.WORLD_LIFE_PROOF_FONT});if(u.pathname==='/life-storage-fixture.html')return route.fulfill({contentType:'text/html',body:storageFixture});if(u.pathname==='/world.html')return route.fulfill({contentType:'text/html',body:world});const file=path.resolve(root,'.'+u.pathname);return file.startsWith(root+path.sep)&&fs.existsSync(file)&&fs.statSync(file).isFile()?route.fulfill({path:file}):route.abort();});
  if(process.env.WORLD_LIFE_PROOF_FONT)await context.addInitScript(()=>document.addEventListener('DOMContentLoaded',()=>{const s=document.createElement('style');s.textContent='@font-face{font-family:LifeProof;src:url(/life-proof.ttf)}html,body,button,input,textarea,select{font-family:LifeProof,sans-serif!important}';document.head.append(s);},{once:true}));
  const page=await context.newPage(),errors=[];page.on('pageerror',e=>errors.push(e.message));await page.goto('https://fixture.test/world.html');await page.waitForFunction(()=>window.houseWorldTest);
  const life=()=>page.evaluate(()=>houseWorldTest.actions.tab({tab:'life'})),status=text=>page.locator('[data-life-root] [role="status"]').filter({hasText:text}).waitFor();await life();
  assert.deepEqual(await page.locator('.bottomnav button > span:first-of-type').allTextContents(),['동네','우리집','게시판','생활','메뉴']);assert.deepEqual(await page.locator('[data-life-tool]').evaluateAll(els=>els.map(e=>e.dataset.lifeTool)),['contacts','ledger','calculator']);assert.equal(await page.locator('.bottomnav [data-tab="life"]').getAttribute('aria-current'),'page');
  for(const width of [320,390,1280]){await page.setViewportSize({width,height:844});assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));if(width<900)assert(await page.locator('.bottomnav button').evaluateAll(nodes=>new Set(nodes.map(n=>Math.round(n.getBoundingClientRect().top))).size===1));}
  await page.setViewportSize({width:390,height:844});if(process.env.WORLD_LIFE_PROOF_DIR){fs.mkdirSync(process.env.WORLD_LIFE_PROOF_DIR,{recursive:true});await page.evaluate(()=>document.fonts.ready);await page.screenshot({path:path.join(process.env.WORLD_LIFE_PROOF_DIR,'life-overview.png')});}const contacts=page.locator('[data-life-tool="contacts"]'),ledger=page.locator('[data-life-tool="ledger"]'),calc=page.locator('[data-life-tool="calculator"]');await contacts.locator('summary').click();await contacts.getByLabel('이름',{exact:true}).fill('민준');await contacts.getByLabel('전화번호',{exact:true}).fill('010-1234-5678');
  await page.evaluate(()=>{window.originalSave=Storage.prototype.setItem;Storage.prototype.setItem=function(k,v){if(k.startsWith('ojjuda-life-'))throw Error('quota');return originalSave.call(this,k,v);};});await contacts.getByRole('button',{name:'연락처 저장'}).click();await status('저장 공간');assert.equal(await contacts.getByLabel('이름',{exact:true}).inputValue(),'민준');await page.evaluate(()=>Storage.prototype.setItem=originalSave);await contacts.getByRole('button',{name:'연락처 저장'}).click();await status('이 기기에 저장');assert.equal(await contacts.getByRole('link',{name:'010-1234-5678'}).getAttribute('href'),'tel:01012345678');
  await contacts.getByLabel('이름',{exact:true}).fill('중복');await contacts.getByLabel('전화번호',{exact:true}).fill('01012345678');await contacts.getByRole('button',{name:'연락처 저장'}).click();await status('이미 저장');await contacts.getByLabel('연락처 검색').fill('없는 사람');assert.equal(await contacts.locator('.life-row').count(),0);await contacts.getByLabel('연락처 검색').fill('');await contacts.getByRole('button',{name:'민준 연락처 삭제'}).click();await contacts.getByRole('button',{name:'취소',exact:true}).click();assert.equal(await contacts.locator('.life-row').count(),1);
  await ledger.locator('summary').click();await ledger.getByLabel('내용',{exact:true}).fill('점심');await ledger.getByLabel('금액',{exact:true}).fill('9000');await ledger.getByLabel('날짜',{exact:true}).fill('2026-10-04');await ledger.getByRole('button',{name:'가계부 저장'}).click();await status('이 기기에 저장');await ledger.getByLabel('수입·지출').selectOption('income');await ledger.getByLabel('내용',{exact:true}).fill('용돈');await ledger.getByLabel('금액',{exact:true}).fill('20000');await ledger.getByRole('button',{name:'가계부 저장'}).click();await page.waitForFunction(()=>document.querySelector('[data-life-tool="ledger"] .life-totals strong').textContent==='20,000원');assert.deepEqual(await ledger.locator('.life-totals strong').allTextContents(),['20,000원','9,000원','11,000원']);await ledger.getByLabel('조회할 월').fill('2026-09');assert.equal(await ledger.locator('.life-row').count(),0);await ledger.getByLabel('조회할 월').fill('2026-10');assert.equal(await ledger.locator('.life-row').count(),2);
  await ledger.getByLabel('내용',{exact:true}).fill('작성 중인 내역');await page.locator('.bottomnav [data-tab="my"]').click();await life();assert.equal(await ledger.getByLabel('내용',{exact:true}).inputValue(),'작성 중인 내역','unsaved entry survives tab switches');
  await calc.locator('summary').click();const key=k=>calc.getByRole('button',{name:k,exact:true}).click();for(const k of ['0','.','1','+','0','.','2','='])await key(k);assert.equal(await calc.locator('output').textContent(),'0.3');for(const k of ['C','9','÷','0','='])await key(k);assert.equal(await calc.locator('output').textContent(),'계산할 수 없어요');for(const k of ['C','2','+','3','×','4','='])await key(k);assert.equal(await calc.locator('output').textContent(),'20');
  for(const [keys,expected] of [
   [[...'1234567890123','+','1','='],'1234567890124'],
   [[...'9007199254740990','+','1','='],'9007199254740991'],
   [[...'9007199254740991','−','1','='],'9007199254740990'],
   [[...'0.1','+','0','.','2','='],'0.3'],
   [[...'0.1','×','0','.','2','='],'0.02']
  ]){await key('C');for(const k of keys)await key(k);assert.equal(await calc.locator('output').textContent(),expected,`calculator preserves ${keys.join(' ')} precision`);}
  await page.reload();await page.waitForFunction(()=>window.houseWorldTest);await life();await contacts.locator('summary').click();assert.equal(await contacts.locator('.life-row').count(),1,'contacts persist after reload');await ledger.locator('summary').click();assert.equal(await ledger.locator('.life-row').count(),2,'ledger persists after reload');
  await page.evaluate(()=>{houseWorldTest.auth.user={id:'world-member-b'};houseWorldTest.render();});assert.equal(await contacts.locator('.life-row').count(),0);await contacts.locator('summary').click();assert.equal(await contacts.locator('.life-row').count(),0,'new account has no previous account contacts');await page.evaluate(()=>{houseWorldTest.auth.user={id:'world-member-a'};houseWorldTest.render();});assert.equal(await contacts.locator('.life-row').count(),1);
  await page.evaluate(()=>houseWorldTest.actions.tab({tab:'home'}));await page.frameLocator('iframe').locator('#app.records-home').waitFor();let f=page.frames().find(x=>x.url().includes('/house-test/index.html'));await f.waitForFunction(()=>document.querySelector('#app').getClientRects().length);
  await page.waitForFunction(()=>houseWorldTest.rooms.has('world-member-a'));assert.deepEqual(await page.evaluate(()=>houseWorldTest.roomCalls.slice(0,2).map(call=>call.name)),['house_room_load','house_room_save'],'house entry uses the real cloud load and initial save bridge');assert.equal(await page.evaluate(()=>Object.hasOwn(houseWorldTest.rooms.get('world-member-a').snapshot,'diary')),false,'personal local writing is not sent with room geometry');
  const cdp=await context.newCDPSession(page),touch=(type,points)=>cdp.send('Input.dispatchTouchEvent',{type,touchPoints:points.map(([x,y])=>({x,y,id:1}))});
  const swipe=async(locator,dx,dy=0)=>{await locator.scrollIntoViewIfNeeded();const b=await locator.boundingBox(),x=b.x+b.width*(dx<0?.8:.2),y=b.y+Math.min(25,b.height/2);await touch('touchStart',[[x,y]]);for(let i=1;i<=6;i++)await touch('touchMove',[[x+dx*i/6,y+dy*i/6]]);await touch('touchEnd',[]);};
  await swipe(f.locator('#home-profile'),-100);await page.waitForFunction(()=>houseWorldTest.state.tab==='board');assert.equal(await page.locator('iframe').count(),0,'house-record swipe enters the adjacent board');await life();
  await swipe(page.locator('[data-life-root]>h2'),150);await page.waitForFunction(()=>houseWorldTest.state.tab==='board');await page.evaluate(()=>houseWorldTest.actions.tab({tab:'home'}));await page.frameLocator('iframe').locator('#app.records-home').waitFor();assert.equal(await page.evaluate(()=>houseWorldTest.roomCalls.filter(call=>call.name==='house_room_load').length),2,'returning from life reloads the saved account room');f=page.frames().find(x=>x.url().includes('/house-test/index.html'));await f.locator('[data-tab="room"]').click();await swipe(f.locator('#viewport'),-120);assert.equal(await page.evaluate(()=>houseWorldTest.state.tab),'home','room gestures never change World tabs');assert.deepEqual(await page.evaluate(()=>houseWorldTest.unexpected),[]);
  await life();await page.evaluate(()=>{houseWorldTest.auth.online=false;houseWorldTest.auth.user=null;houseWorldTest.render();});assert.equal(await contacts.locator('input').count(),0);assert.equal(await ledger.locator('input').count(),0);await calc.locator('summary').click();await key('7');assert.equal(await calc.locator('output').textContent(),'7','guest calculator works without storing personal data');assert.deepEqual(errors,[]);
  const first=await context.newPage(),second=await context.newPage();for(const p of [first,second]){p.on('pageerror',e=>errors.push(e.message));await p.goto('https://fixture.test/life-storage-fixture.html');await p.locator('[data-life-tool="contacts"] summary').click();}
  const tool=(p,name)=>p.locator(`[data-life-tool="${name}"]`),contactDraft=async(p,name,phone)=>{await tool(p,'contacts').getByLabel('이름',{exact:true}).fill(name);await tool(p,'contacts').getByLabel('전화번호',{exact:true}).fill(phone);},contactSave=async(p,wait=true)=>{await tool(p,'contacts').getByRole('button',{name:'연락처 저장'}).click();if(wait)await p.evaluate(async()=>{if(navigator.locks)await navigator.locks.request('ojjuda-life-v1:life-storage-audit',()=>{});});};
  await contactDraft(first,'작성 중인 연락처','010-9999-9999');await tool(first,'ledger').locator('summary').click();await tool(first,'ledger').getByLabel('내용',{exact:true}).fill('작성 중인 가계부');await tool(first,'calculator').locator('summary').click();for(const name of ['1','2','+','3'])await tool(first,'calculator').getByRole('button',{name,exact:true}).click();
  await contactDraft(second,'다른 창 연락처','010-1234-5678');await contactSave(second);await tool(first,'contacts').getByRole('link',{name:'010-1234-5678'}).waitFor();
  assert.equal(await tool(first,'contacts').getByLabel('이름',{exact:true}).inputValue(),'작성 중인 연락처','other-window saves preserve the in-progress contact');assert.equal(await tool(first,'ledger').getByLabel('내용',{exact:true}).inputValue(),'작성 중인 가계부','other-window saves preserve the in-progress ledger entry');await tool(first,'calculator').getByRole('button',{name:'=',exact:true}).click();assert.equal(await tool(first,'calculator').locator('output').textContent(),'15','other-window saves preserve the running calculation');
  await tool(first,'contacts').getByLabel('연락처 검색').fill('0101234');assert.equal(await tool(first,'contacts').locator('.life-row').count(),1,'digit-only searches match formatted phone numbers');await tool(first,'contacts').getByLabel('연락처 검색').fill('');
  await first.evaluate(()=>OjjudaLife.mount(null));await contactDraft(second,'닫혀 있을 때 추가','010-2222-2222');await contactSave(second);await first.evaluate(()=>remountLife());assert.equal(await tool(first,'contacts').locator('.life-row').count(),2,'remount reads writes made while the life page was closed');
  await contactDraft(first,'첫째 창 추가','010-3333-3333');await contactDraft(second,'둘째 창 추가','010-4444-4444');await Promise.all([contactSave(first),contactSave(second)]);await first.waitForFunction(()=>JSON.parse(localStorage.getItem('ojjuda-life-v1:life-storage-audit')).contacts.length===4);await tool(first,'contacts').getByRole('link',{name:'010-4444-4444'}).waitFor();await tool(second,'contacts').getByRole('link',{name:'010-3333-3333'}).waitFor();
  await contactDraft(first,'중복 첫째','010-5555-5555');await contactDraft(second,'중복 둘째','01055555555');await Promise.all([contactSave(first),contactSave(second)]);assert.equal(await first.evaluate(()=>JSON.parse(localStorage.getItem('ojjuda-life-v1:life-storage-audit')).contacts.length),5,'concurrent saves do not create duplicate phone contacts');
  await first.evaluate(()=>document.querySelector('[data-life-tool="contacts"] input[name="name"]').value='삭제 중에도 남을 초안');await second.evaluate(()=>localStorage.clear());await first.waitForFunction(()=>document.querySelectorAll('[data-life-tool="contacts"] .life-row').length===0);assert.equal(await tool(first,'contacts').getByLabel('이름',{exact:true}).inputValue(),'삭제 중에도 남을 초안','clearing storage refreshes lists without replacing inputs');
  await second.evaluate(()=>{navigator.locks.request('ojjuda-life-v1:life-storage-audit',()=>new Promise(resolve=>{window.releaseLifeLock=resolve;}));});await second.waitForFunction(()=>window.releaseLifeLock);await contactDraft(first,'계정 전환 직전','010-7777-7777');await contactSave(first,false);await first.waitForFunction(async()=>(await navigator.locks.query()).pending.length===1);await first.evaluate(()=>OjjudaLife.mount(document.querySelector('main'),{owner:'life-another-account'}));await second.evaluate(()=>releaseLifeLock());await first.waitForFunction(async()=>(await navigator.locks.query()).pending.length===0);assert.equal(await first.evaluate(()=>localStorage.getItem('ojjuda-life-v1:life-storage-audit')),null,'an account switch cancels a queued save');assert.equal(await tool(first,'contacts').locator('.life-row').count(),0,'reusing the same host with another owner does not expose the previous account');await first.evaluate(()=>remountLife());
  await first.evaluate(()=>{Object.defineProperty(navigator,'locks',{value:undefined,configurable:true});localStorage.setItem('ojjuda-life-v1:life-storage-audit',JSON.stringify({contacts:[{id:'fresh-record',name:'최신 자료',phone:'010-8888-8888'}],entries:[]}));});await contactDraft(first,'잠금 미지원 저장','010-0000-0000');await contactSave(first);assert.equal(await first.evaluate(()=>JSON.parse(localStorage.getItem('ojjuda-life-v1:life-storage-audit')).contacts.length),2,'browsers without Web Locks still merge against the latest stored records');assert.equal(await tool(first,'contacts').getByLabel('이름',{exact:true}).inputValue(),'','saving a restored draft clears the saved contact fields');
  await second.evaluate(()=>localStorage.setItem('ojjuda-life-v1:life-storage-audit','broken-data'));await first.locator('[role="status"]').filter({hasText:'기존 자료를 보호'}).waitFor();await contactDraft(first,'보호 확인','010-6666-6666');await contactSave(first);assert.equal(await first.evaluate(()=>localStorage.getItem('ojjuda-life-v1:life-storage-audit')),'broken-data','unreadable stored data is never overwritten');assert.deepEqual(errors,[]);
  console.log('PASS: five menus, one ordered life page, responsive layout, contacts/ledger persistence and isolation, drafts and storage failures, concurrent windows and phone search, calculator, iframe swipes and room gesture protection');
 }finally{await browser.close();}
})().catch(e=>{console.error(e);process.exitCode=1;});
