import {icon} from './icons.js?v=20261001-2';
import {normalize,roomKey,canAdd,normalizeShelf,shelfSize,floorPoint,floorCell,roomPeriod} from './model.js?v=20261001-2';
const $=s=>document.querySelector(s),view=$('#viewport'),world=$('#world');
const stepX=1294,stepY=1210,reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;
let state,port,key,initialized=false,selected='0:0',tab='room',expanding=false,scale=1,pan={x:0,y:0},actorX=420,dogX=700,follow=false,raf=0,motion=null,timer,saveFailed=false;
let editing=false,draft=null,period=roomPeriod(),periodTimer;
const timers=new Set();const later=(fn,ms)=>{const id=setTimeout(()=>{timers.delete(id);fn();},ms);timers.add(id);return id;};
const bounds=r=>({x:(r.x+2)*stepX,y:(3-r.y)*stepY});
function toast(message){$('#notice').textContent=message;$('#notice').classList.add('show');clearTimeout(timer);timer=setTimeout(()=>$('#notice').classList.remove('show'),2400);}
function persist(){try{localStorage.setItem(key,JSON.stringify(state));if(saveFailed){saveFailed=false;$('#save-warning').hidden=true;}}catch{saveFailed=true;$('#save-warning').hidden=false;}}
function save(){persist();}
function current(){return state.rooms.find(r=>roomKey(r)===selected)||state.rooms[0];}
function title(r){if(!r.x&&!r.y)return '거실';return `${r.y>0?'위 '+r.y+'층':r.y<0?'아래 '+(-r.y)+'층':'시작 층'} · ${r.x<0?'왼쪽 '+(-r.x):r.x>0?'오른쪽 '+r.x:'가운데'}`;}
function applyCamera(){const w=view.clientWidth,h=view.clientHeight;pan.x=Math.max(-6470*scale+w*.1,Math.min(w*.9,pan.x));pan.y=Math.max(-8470*scale+h*.1,Math.min(h*.9,pan.y));world.style.transform=`translate(${pan.x}px,${pan.y}px) scale(${scale})`;}
function focusRoom(all=false){const r=current(),b=bounds(r),w=view.clientWidth,h=view.clientHeight;if(all){const a=expanding?[{x:-2,y:-3},{x:2,y:3}]:state.rooms;const minX=Math.min(...a.map(x=>bounds(x).x)),maxX=Math.max(...a.map(x=>bounds(x).x))+1254,minY=Math.min(...a.map(x=>bounds(x).y)),maxY=Math.max(...a.map(x=>bounds(x).y))+1180;scale=Math.max(.045,Math.min(w/(maxX-minX+110),(h-80)/(maxY-minY+90),1));pan={x:(w-(maxX-minX)*scale)/2-minX*scale,y:(h-(maxY-minY)*scale)/2-minY*scale-10};}else{scale=Math.max(.08,Math.min(w/1280,(h-75)/1120,1));pan={x:w/2-(b.x+627)*scale,y:(h-75-1120*scale)/2+15-(b.y+65)*scale};}applyCamera();}
function zoom(factor,point={x:view.clientWidth/2,y:view.clientHeight/2}){const next=Math.min(1.6,Math.max(.045,scale*factor)),ratio=next/scale;pan.x=point.x-(point.x-pan.x)*ratio;pan.y=point.y-(point.y-pan.y)*ratio;scale=next;applyCamera();}
function element(tag,classes,text){const n=document.createElement(tag);if(classes)n.className=classes;if(text)n.textContent=text;return n;}
function stopMotion(){cancelAnimationFrame(raf);raf=0;motion=null;timers.forEach(clearTimeout);timers.clear();world.querySelectorAll('.walking,.playing,.loved').forEach(n=>n.classList.remove('walking','playing','loved'));world.querySelectorAll('.heart').forEach(n=>n.remove());world.querySelectorAll('.ball').forEach(n=>n.hidden=true);}
function updateActors(){const room=world.querySelector(`[data-room="${selected}"]`);if(!room)return;const a=room.querySelector('.actor'),d=room.querySelector('.dog');if(a)a.style.left=actorX+'px';if(d)d.style.left=dogX+'px';}
function move(kind,to,done){stopMotion();const from=kind==='actor'?actorX:dogX,duration=reduced?0:Math.max(450,Math.abs(to-from)*3);motion={kind,from,to,duration,start:performance.now(),done};const n=world.querySelector(`[data-room="${selected}"] .${kind==='actor'?'actor':'dog'}`);n?.classList.add(kind==='actor'?'walking':'playing');if(kind==='dog'&&n)n.style.scale=to<from?'-1 1':'1 1';function tick(now){if(!motion)return;const m=motion,t=m.duration?Math.min(1,(now-m.start)/m.duration):1,value=m.from+(m.to-m.from)*t;if(m.kind==='actor'){actorX=value;if(follow)dogX=Math.max(30,Math.min(1020,value+145));}else dogX=value;updateActors();if(t<1)raf=requestAnimationFrame(tick);else{motion=null;raf=0;n?.classList.remove('walking','playing');m.done?.();}}raf=requestAnimationFrame(tick);}
function renderWorld(){stopMotion();world.replaceChildren();for(const r of state.rooms){const b=bounds(r),active=roomKey(r)===selected,room=element('div','room'+(active?' selected':''));room.dataset.room=roomKey(r);room.style.left=b.x+'px';room.style.top=b.y+'px';
 const image=element('img','room-bg');image.src=`assets/room-${period}.webp`;image.alt='파스텔 아파트 빈방';image.draggable=false;room.append(image);
 if(r.curtains!==false){const curtain=element('img','curtains');curtain.src='assets/curtains.webp';curtain.alt='아이보리 커튼';curtain.draggable=false;room.append(curtain);}
 const shelf=active&&editing?draft:r.shelf;if(active&&editing)room.append(makeGrid(shelf));if(shelf)room.append(makeShelf(shelf,active));
 if(active&&tab==='pet'&&!expanding){const a=element('img','actor');a.src='assets/avatar.webp';a.alt='테스트 캐릭터';a.draggable=false;const d=element('button','actor dog');d.type='button';d.setAttribute('aria-label','두부와 놀기');const im=element('img');im.src='assets/dog.webp';im.alt='';im.draggable=false;d.append(im);d.onclick=()=>setTab('pet');room.append(a,d);const ball=element('div','ball');ball.hidden=true;room.append(ball);}world.append(room);}

 if(expanding)for(let y=-3;y<=3;y++)for(let x=-2;x<=2;x++){if(state.rooms.some(r=>r.x===x&&r.y===y))continue;const cell={x,y},b=bounds(cell),button=element('button','expansion');button.type='button';button.dataset.cell=roomKey(cell);button.disabled=!canAdd(state.rooms,cell);button.append(element('strong','',button.disabled?'·':'＋'),element('span','',title(cell)));button.setAttribute('aria-label',title(cell)+(button.disabled?' · 먼저 옆방을 연결해 주세요':' 확장'));button.style.left=b.x+'px';button.style.top=b.y+'px';button.onclick=()=>addRoom(cell);world.append(button);}
 $('#room-name').textContent=title(current());$('#room-count').textContent=state.rooms.length+' / 35개 방';updateActors();}
function addRoom(cell){if(!canAdd(state.rooms,cell)){toast('열린 방 옆으로만 확장할 수 있어요.');return;}state.rooms.push({...cell,decor:false,curtains:false,shelf:null});selected=roomKey(cell);actorX=460;dogX=630;save();renderWorld();renderPanel();toast('새 방이 연결됐어요.');}
function selectRoom(id){if(!state.rooms.some(r=>roomKey(r)===id))return;editing=false;draft=null;selected=id;actorX=420;dogX=700;renderWorld();renderPanel();if(!expanding)focusRoom();}
function actionButton(label,fn,symbol){const b=element('button');b.type='button';b.setAttribute('aria-label',label);if(symbol){const mark=element('span','symbol');mark.innerHTML=icon({'◉':'ball','♡':'heart','↝':'follow','▧':'room','□':'room','＋':'room'}[symbol]||'room');b.append(mark);}b.append(document.createTextNode(label));b.onclick=fn;return b;}
function renderPanel(){const body=$('#panel-body');body.replaceChildren();$('#panel-title').textContent=expanding?'집 확장':{pet:'두부와 놀기',room:'방 꾸미기',closet:'나의 아바타',diary:'오늘의 기록'}[tab];if(expanding){const row=element('div','row'),select=element('select');select.setAttribute('aria-label','확장 기준 방');for(const r of state.rooms){const option=element('option','',title(r));option.value=roomKey(r);option.selected=option.value===selected;select.append(option);}select.onchange=()=>selectRoom(select.value);row.append(select);body.append(row);const controls=element('div','actions expansion-actions');for(const [dx,dy,label]of [[-1,0,'← 왼쪽'],[1,0,'오른쪽 →'],[0,1,'↑ 위층'],[0,-1,'↓ 아래층']]){const r=current(),cell={x:r.x+dx,y:r.y+dy},existing=state.rooms.find(x=>x.x===cell.x&&x.y===cell.y),b=actionButton(label+ (existing?' 보기':' 확장'),()=>existing?selectRoom(roomKey(cell)):addRoom(cell));b.disabled=!existing&&!canAdd(state.rooms,cell);controls.append(b);}body.append(controls,element('p','panel-note','가운데에서 좌우 2칸 · 위아래 3층, 최대 35개 방'));return;}
 if(tab==='pet'){const row=element('div','actions');row.append(actionButton('공 던지기',throwBall,'◉'),actionButton('쓰다듬기',petDog,'♡'),actionButton(follow?'따라오기 멈춤':'따라오기',()=>{follow=!follow;renderPanel();toast(follow?'이제 두부가 따라와요.':'두부가 여기서 쉬어요.');},'↝'));body.append(row,element('p','panel-note','바닥을 누르면 캐릭터가 이동해요. 두부를 눌러도 이 메뉴가 열려요.'));}
 if(tab==='room'){
  if(editing){const directions=element('div','directions');for(const [id,label]of [['left','왼쪽 벽'],['center','가운데'],['right','오른쪽 벽']]){const button=actionButton(label,()=>{draft=normalizeShelf({direction:id,x:id==='left'?0:id==='right'?7:3,y:id==='center'?0:draft.y});renderWorld();renderPanel();});button.dataset.direction=id;button.setAttribute('aria-pressed',String(draft.direction===id));directions.append(button);}body.append(directions);
  const arrows=element('div','move-controls');for(const [dx,dy,label]of [[-.5,0,'←'],[0,-.5,'↑'],[0,.5,'↓'],[.5,0,'→']]){const b=actionButton(label,()=>moveShelf(dx,dy));b.setAttribute('aria-label',`책장 ${label} 0.5칸`);arrows.append(b);}const status=element('span','position');status.id='shelf-position';status.textContent=`가로 ${draft.x} · 깊이 ${draft.y}칸`;arrows.append(status);body.append(arrows);
  const row=element('div','directions');row.append(actionButton('취소',()=>finishPlacement(false)),actionButton('배치 완료',()=>finishPlacement(true)));body.append(row,element('p','panel-note','책장을 끌거나 화살표로 0.5칸씩 이동해요.'));
  }else{const row=element('div','actions');row.append(actionButton(current().shelf?'책장 배치':'책장 놓기',startPlacement,'▧'),actionButton(current().curtains?'커튼 걷기':'커튼 달기',()=>{current().curtains=!current().curtains;save();renderWorld();renderPanel();},'□'),actionButton('빈방 보기',()=>{current().shelf=null;current().curtains=false;save();renderWorld();renderPanel();},'□'));body.append(row,element('p','panel-note','확정한 빈방 · 커튼 · 책장부터 하나씩 꾸며요.'));}
 }

 if(tab==='closet'){const box=element('div','closet-preview'),im=element('img');im.src='assets/avatar.webp';im.alt='크림 가디건과 연두 바지를 입은 기본 아바타';box.append(im,element('p','','이번 테스트의 기본 아바타예요.\n얼굴·머리·의상 선택은 다음 단계에서 하나씩 만들어요.'));body.append(box);}
 if(tab==='diary'){const label=element('label','','오늘은 어떤 하루였나요?'),field=element('textarea');field.id='diary';field.maxLength=4000;field.value=state.diary;label.htmlFor='diary';field.oninput=()=>{state.diary=field.value;save();};body.append(label,field,actionButton('기록 저장',()=>{state.diary=field.value;persist();toast(saveFailed?'저장할 수 없어요. 내용을 복사해 주세요.':'이 기기에 기록을 저장했어요.');}),element('p','panel-note','테스트 기록은 이 기기에 저장돼요.'));}}
function setTab(next){if(!['room','closet','pet','diary'].includes(next))return;editing=false;draft=null;tab=next;if(expanding){expanding=false;$('#expand').setAttribute('aria-pressed','false');renderWorld();focusRoom();}document.querySelectorAll('[data-tab]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.tab===tab)));renderWorld();renderPanel();}
function toggleExpansion(next=!expanding){editing=false;draft=null;expanding=next;$('#expand').setAttribute('aria-pressed',String(next));$('#hint').textContent=next?'연결된 방 옆의 ＋로 확장하세요':'방을 끌어 둘러보세요';renderWorld();renderPanel();focusRoom(next);}
function throwBall(){const node=world.querySelector(`[data-room="${selected}"] .ball`),destination=dogX>600?170:1000,back=dogX;if(!node)return;node.style.left=destination+'px';move('dog',destination,()=>{node.hidden=true;later(()=>move('dog',back,()=>{toast('두부가 공을 가져왔어요!');}),200);});node.hidden=false;toast('두부야, 공 가져와!');}
function petDog(){stopMotion();const dog=world.querySelector(`[data-room="${selected}"] .dog`),heart=element('span','heart','♡');heart.style.left=(dogX+50)+'px';dog?.parentElement.append(heart);dog?.classList.add('loved');later(()=>{heart.remove();dog?.classList.remove('loved');},1800);toast('두부가 기분 좋게 꼬리를 흔들어요.');}
const pointers=new Map();let gesture=null;
function point(e){const b=view.getBoundingClientRect();return {x:e.clientX-b.left,y:e.clientY-b.top};}
view.addEventListener('pointerdown',e=>{if(e.target.closest('button,select')||e.button>0)return;const p=point(e);pointers.set(e.pointerId,p);view.setPointerCapture(e.pointerId);if(pointers.size===1)gesture={start:p,last:p,moved:false,multi:false};else if(pointers.size===2){const [a,b]=[...pointers.values()];gesture={multi:true,moved:true,distance:Math.hypot(a.x-b.x,a.y-b.y),center:{x:(a.x+b.x)/2,y:(a.y+b.y)/2}};}});
view.addEventListener('pointermove',e=>{if(!pointers.has(e.pointerId)||!gesture)return;const p=point(e);pointers.set(e.pointerId,p);if(pointers.size>=2){const [a,b]=[...pointers.values()],center={x:(a.x+b.x)/2,y:(a.y+b.y)/2},distance=Math.hypot(a.x-b.x,a.y-b.y);if(gesture.distance>0){zoom(distance/gesture.distance,gesture.center);pan.x+=center.x-gesture.center.x;pan.y+=center.y-gesture.center.y;applyCamera();}gesture.distance=distance;gesture.center=center;gesture.multi=true;}else if(!gesture.multi){if(Math.hypot(p.x-gesture.start.x,p.y-gesture.start.y)>7)gesture.moved=true;if(gesture.moved){pan.x+=p.x-gesture.last.x;pan.y+=p.y-gesture.last.y;applyCamera();}gesture.last=p;}});
function end(e,canceled=false){if(!pointers.has(e.pointerId))return;const p=point(e),tap=!canceled&&gesture&&!gesture.moved&&!gesture.multi;pointers.delete(e.pointerId);if(view.hasPointerCapture(e.pointerId))view.releasePointerCapture(e.pointerId);if(tap){const wx=(p.x-pan.x)/scale,wy=(p.y-pan.y)/scale,r=state.rooms.find(r=>{const b=bounds(r);return wx>=b.x&&wx<=b.x+1254&&wy>=b.y+704&&wy<=b.y+1114;});if(r){if(roomKey(r)!==selected)selectRoom(roomKey(r));else if(!expanding&&tab==='pet'){const b=bounds(r);move('actor',Math.max(35,Math.min(1040,wx-b.x-55)));}}}if(!pointers.size)gesture=null;}
view.addEventListener('pointerup',e=>end(e));view.addEventListener('pointercancel',e=>end(e,true));view.addEventListener('wheel',e=>{e.preventDefault();zoom(Math.exp(-e.deltaY*.001),point(e));},{passive:false});view.addEventListener('keydown',e=>{if(e.key==='+'||e.key==='='){e.preventDefault();zoom(1.2);}else if(e.key==='-'){e.preventDefault();zoom(1/1.2);}else if(['ArrowLeft','ArrowRight','ArrowUp','ArrowDown'].includes(e.key)){e.preventDefault();pan.x+=e.key==='ArrowLeft'?65:e.key==='ArrowRight'?-65:0;pan.y+=e.key==='ArrowUp'?65:e.key==='ArrowDown'?-65:0;applyCamera();}});
$('#zoom-in').onclick=()=>zoom(1.25);$('#zoom-out').onclick=()=>zoom(.8);$('#overview').onclick=()=>focusRoom(true);$('#home-view').onclick=()=>focusRoom();$('#expand').onclick=()=>toggleExpansion();$('#exit').onclick=()=>{if(initialized)persist();port?.postMessage({type:'close'});};document.addEventListener('keydown',e=>{if(e.key==='Escape')$('#exit').click();});document.querySelectorAll('[data-tab]').forEach(b=>{b.querySelector('span').innerHTML=icon(b.dataset.tab);b.onclick=()=>setTab(b.dataset.tab);});
new ResizeObserver(()=>{if(initialized)focusRoom(expanding);}).observe(view);
window.addEventListener('message',e=>{if(initialized||window.parent===window||e.source!==window.parent||e.origin!==location.origin||e.data?.type!=='ojjuda-house-test-init'||!e.ports[0]||typeof e.data.owner!=='string'||e.data.owner.length>180)return;port=e.ports[0];key='ojjuda-house-playtest-v1:'+encodeURIComponent(e.data.owner);let stored;try{stored=JSON.parse(localStorage.getItem(key));}catch{}state=normalize(stored);initialized=true;$('#locked').hidden=true;$('#app').hidden=false;renderWorld();renderPanel();focusRoom();updatePeriod();periodTimer=setInterval(updatePeriod,15000);port.onmessage=event=>{if(event.data?.type==='dispose'){persist();stopMotion();clearInterval(periodTimer);initialized=false;$('#app').hidden=true;$('#locked').hidden=false;port.close();}};port.postMessage({type:'ready'});});
document.addEventListener('visibilitychange',()=>{if(document.hidden){stopMotion();if(initialized)persist();}else if(initialized)updatePeriod();});window.addEventListener('pagehide',()=>{if(initialized)persist();stopMotion();});

function updatePeriod(){const next=roomPeriod();document.documentElement.dataset.period=next;$('#period-name').textContent={day:'낮',dusk:'새벽 · 저녁',night:'밤'}[next];if(next!==period){period=next;world.querySelectorAll('.room-bg').forEach(im=>im.src=`assets/room-${period}.webp`);}}
function startPlacement(){editing=true;draft={...(current().shelf||{x:7,y:1.5,direction:'right'})};renderWorld();renderPanel();}
function finishPlacement(commit){if(commit){current().shelf={...draft};save();}editing=false;draft=null;renderWorld();renderPanel();toast(commit?'책장을 배치했어요.':'이전 배치로 돌아왔어요.');}
function moveShelf(dx,dy){draft=normalizeShelf({...draft,x:draft.x+dx,y:draft.y+dy});renderWorld();renderPanel();}
const crops={left:{x:210,y:26,w:240,h:928},center:{x:614,y:32,w:308,h:900},right:{x:1084,y:24,w:244,h:932}};
function shelfStyle(button,s){const {w,d}=shelfSize(s.direction),foot=floorPoint(s.x+w/2,s.y+d),c=crops[s.direction],height=510+((s.y+d)/7)*150,ratio=height/c.h;button.style.left=(foot.x-c.w*ratio/2)+'px';button.style.top=(foot.y-height)+'px';button.style.width=c.w+'px';button.style.height=c.h+'px';button.style.transform=`scale(${ratio})`;button.style.zIndex=String(10+Math.round(foot.y));button.dataset.x=s.x;button.dataset.y=s.y;button.dataset.direction=s.direction;const im=button.querySelector('img');im.style.left=-c.x+'px';im.style.top=-c.y+'px';}
function makeShelf(s,active){const button=element('button','bookshelf');button.type='button';button.setAttribute('aria-label','책장 배치 변경');button.disabled=!active||expanding;const im=element('img');im.src='assets/bookshelf-views.webp';im.alt='원목 책장';im.draggable=false;button.append(im);shelfStyle(button,s);button.onclick=()=>{if(!editing){setTab('room');startPlacement();}};if(active)button.addEventListener('pointerdown',e=>{if(!editing||e.button>0)return;e.stopPropagation();const start=point(e),original={...draft},b=bounds(current()),{w,d}=shelfSize(draft.direction),anchor=floorPoint(draft.x+w/2,draft.y+d),startCell=floorCell(anchor.x,anchor.y);button.setPointerCapture(e.pointerId);
 const drag=ev=>{const p=point(ev),cell=floorCell(anchor.x+(p.x-start.x)/scale,anchor.y+(p.y-start.y)/scale);draft=normalizeShelf({...original,x:original.x+cell.x-startCell.x,y:original.y+cell.y-startCell.y});shelfStyle(button,draft);const grid=button.parentElement.querySelector('.floor-grid');if(grid)grid.replaceWith(makeGrid(draft));$('#shelf-position').textContent=`가로 ${draft.x} · 깊이 ${draft.y}칸`;};
 const up=ev=>{button.removeEventListener('pointermove',drag);button.removeEventListener('pointerup',up);button.removeEventListener('pointercancel',cancel);if(button.hasPointerCapture(ev.pointerId))button.releasePointerCapture(ev.pointerId);};const cancel=ev=>{draft=original;shelfStyle(button,draft);up(ev);renderWorld();renderPanel();};button.addEventListener('pointermove',drag);button.addEventListener('pointerup',up);button.addEventListener('pointercancel',cancel);
 });return button;}
function makeGrid(s){const svg=document.createElementNS('http://www.w3.org/2000/svg','svg');svg.classList.add('floor-grid');svg.setAttribute('viewBox','0 0 1254 1254');for(let axis=0;axis<2;axis++)for(let n=0;n<=(axis?7:8);n+=.5){const a=axis?floorPoint(0,n):floorPoint(n,0),b=axis?floorPoint(8,n):floorPoint(n,7),line=document.createElementNS(svg.namespaceURI,'path');line.setAttribute('d',`M${a.x},${a.y}L${b.x},${b.y}`);line.classList.add(Number.isInteger(n)?'whole':'half');svg.append(line);}if(s){const {w,d}=shelfSize(s.direction),polygon=document.createElementNS(svg.namespaceURI,'polygon');polygon.setAttribute('points',[[s.x,s.y],[s.x+w,s.y],[s.x+w,s.y+d],[s.x,s.y+d]].map(([x,y])=>{const p=floorPoint(x,y);return `${p.x},${p.y}`;}).join(' '));svg.append(polygon);}return svg;}
