import {icon} from './icons.js?v=20261001-1';
import {normalize,roomKey,canAdd} from './model.js?v=20261001-1';
const $=s=>document.querySelector(s),view=$('#viewport'),world=$('#world');
const stepX=1240,stepY=460,reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;
let state,port,key,initialized=false,selected='0:0',tab='pet',expanding=false,scale=1,pan={x:0,y:0},actorX=420,dogX=700,follow=false,raf=0,motion=null,timer,saveFailed=false;
const timers=new Set();const later=(fn,ms)=>{const id=setTimeout(()=>{timers.delete(id);fn();},ms);timers.add(id);return id;};
const bounds=r=>({x:(r.x+2)*stepX,y:(3-r.y)*stepY});
function toast(message){$('#notice').textContent=message;$('#notice').classList.add('show');clearTimeout(timer);timer=setTimeout(()=>$('#notice').classList.remove('show'),2400);}
function persist(){try{localStorage.setItem(key,JSON.stringify(state));if(saveFailed){saveFailed=false;$('#save-warning').hidden=true;}}catch{saveFailed=true;$('#save-warning').hidden=false;}}
function save(){persist();}
function current(){return state.rooms.find(r=>roomKey(r)===selected)||state.rooms[0];}
function title(r){if(!r.x&&!r.y)return '거실';return `${r.y>0?'위 '+r.y+'층':r.y<0?'아래 '+(-r.y)+'층':'시작 층'} · ${r.x<0?'왼쪽 '+(-r.x):r.x>0?'오른쪽 '+r.x:'가운데'}`;}
function applyCamera(){const w=view.clientWidth,h=view.clientHeight;pan.x=Math.max(-6200*scale+w*.1,Math.min(w*.9,pan.x));pan.y=Math.max(-3220*scale+h*.1,Math.min(h*.9,pan.y));world.style.transform=`translate(${pan.x}px,${pan.y}px) scale(${scale})`;}
function focusRoom(all=false){const r=current(),b=bounds(r),w=view.clientWidth,h=view.clientHeight;if(all){const a=expanding?[{x:-2,y:-3},{x:2,y:3}]:state.rooms;const minX=Math.min(...a.map(x=>bounds(x).x)),maxX=Math.max(...a.map(x=>bounds(x).x))+1200,minY=Math.min(...a.map(x=>bounds(x).y)),maxY=Math.max(...a.map(x=>bounds(x).y))+400;scale=Math.max(.045,Math.min(w/(maxX-minX+110),(h-80)/(maxY-minY+90),1));pan={x:(w-(maxX-minX)*scale)/2-minX*scale,y:(h-(maxY-minY)*scale)/2-minY*scale-10};}else{scale=Math.min(1.3,Math.max(w/1260,Math.min(.68,(h-90)/430)) );pan={x:w/2-(b.x+600)*scale,y:h/2-(b.y+210)*scale-15};}applyCamera();}
function zoom(factor,point={x:view.clientWidth/2,y:view.clientHeight/2}){const next=Math.min(1.6,Math.max(.045,scale*factor)),ratio=next/scale;pan.x=point.x-(point.x-pan.x)*ratio;pan.y=point.y-(point.y-pan.y)*ratio;scale=next;applyCamera();}
function element(tag,classes,text){const n=document.createElement(tag);if(classes)n.className=classes;if(text)n.textContent=text;return n;}
function stopMotion(){cancelAnimationFrame(raf);raf=0;motion=null;timers.forEach(clearTimeout);timers.clear();world.querySelectorAll('.walking,.playing,.loved').forEach(n=>n.classList.remove('walking','playing','loved'));world.querySelectorAll('.heart').forEach(n=>n.remove());world.querySelectorAll('.ball').forEach(n=>n.hidden=true);}
function updateActors(){const room=world.querySelector(`[data-room="${selected}"]`);if(!room)return;const a=room.querySelector('.actor'),d=room.querySelector('.dog');if(a)a.style.left=actorX+'px';if(d)d.style.left=dogX+'px';}
function move(kind,to,done){stopMotion();const from=kind==='actor'?actorX:dogX,duration=reduced?0:Math.max(450,Math.abs(to-from)*3);motion={kind,from,to,duration,start:performance.now(),done};const n=world.querySelector(`[data-room="${selected}"] .${kind==='actor'?'actor':'dog'}`);n?.classList.add(kind==='actor'?'walking':'playing');if(kind==='dog'&&n)n.style.scale=to<from?'-1 1':'1 1';function tick(now){if(!motion)return;const m=motion,t=m.duration?Math.min(1,(now-m.start)/m.duration):1,value=m.from+(m.to-m.from)*t;if(m.kind==='actor'){actorX=value;if(follow)dogX=Math.max(30,Math.min(1020,value+145));}else dogX=value;updateActors();if(t<1)raf=requestAnimationFrame(tick);else{motion=null;raf=0;n?.classList.remove('walking','playing');m.done?.();}}raf=requestAnimationFrame(tick);}
function renderWorld(){stopMotion();world.replaceChildren();for(const r of state.rooms){const b=bounds(r),room=element('div','room'+(roomKey(r)===selected?' selected':'')+(r.decor?'':' empty'));room.dataset.room=roomKey(r);room.style.left=b.x+'px';room.style.top=b.y+'px';if(r.decor){const image=element('img','room-bg');image.src='assets/room.webp';image.alt='라벤더 소파와 밝은 원목 가구가 있는 거실';image.draggable=false;room.append(image);}room.append(element('span','room-name',title(r)));if(roomKey(r)===selected){const a=element('img','actor');a.src='assets/avatar.webp';a.alt='내 캐릭터';a.draggable=false;const d=element('button','actor dog');d.type='button';d.setAttribute('aria-label','두부와 놀기');const im=element('img');im.src='assets/dog.webp';im.alt='';im.draggable=false;d.append(im);d.onclick=()=>setTab('pet');room.append(a,d);const ball=element('div','ball');ball.hidden=true;room.append(ball);}world.append(room);}
 if(expanding)for(let y=-3;y<=3;y++)for(let x=-2;x<=2;x++){if(state.rooms.some(r=>r.x===x&&r.y===y))continue;const cell={x,y},b=bounds(cell),button=element('button','expansion');button.type='button';button.dataset.cell=roomKey(cell);button.disabled=!canAdd(state.rooms,cell);button.append(element('strong','',button.disabled?'·':'＋'),element('span','',title(cell)));button.setAttribute('aria-label',title(cell)+(button.disabled?' · 먼저 옆방을 연결해 주세요':' 확장'));button.style.left=b.x+'px';button.style.top=b.y+'px';button.onclick=()=>addRoom(cell);world.append(button);}
 $('#room-name').textContent=title(current());$('#room-count').textContent=state.rooms.length+' / 35개 방';updateActors();}
function addRoom(cell){if(!canAdd(state.rooms,cell)){toast('열린 방 옆으로만 확장할 수 있어요.');return;}state.rooms.push({...cell,decor:false});selected=roomKey(cell);actorX=460;dogX=630;save();renderWorld();renderPanel();toast('새 방이 연결됐어요.');}
function selectRoom(id){if(!state.rooms.some(r=>roomKey(r)===id))return;selected=id;actorX=420;dogX=700;renderWorld();renderPanel();if(!expanding)focusRoom();}
function actionButton(label,fn,symbol){const b=element('button');b.type='button';b.setAttribute('aria-label',label);if(symbol){const mark=element('span','symbol');mark.innerHTML=icon({'◉':'ball','♡':'heart','↝':'follow','▧':'room','□':'room','＋':'room'}[symbol]||'room');b.append(mark);}b.append(document.createTextNode(label));b.onclick=fn;return b;}
function renderPanel(){const body=$('#panel-body');body.replaceChildren();$('#panel-title').textContent=expanding?'집 확장':{pet:'두부와 놀기',room:'방 꾸미기',closet:'나의 아바타',diary:'오늘의 기록'}[tab];if(expanding){const row=element('div','row'),select=element('select');select.setAttribute('aria-label','확장 기준 방');for(const r of state.rooms){const option=element('option','',title(r));option.value=roomKey(r);option.selected=option.value===selected;select.append(option);}select.onchange=()=>selectRoom(select.value);row.append(select);body.append(row);const controls=element('div','actions expansion-actions');for(const [dx,dy,label]of [[-1,0,'← 왼쪽'],[1,0,'오른쪽 →'],[0,1,'↑ 위층'],[0,-1,'↓ 아래층']]){const r=current(),cell={x:r.x+dx,y:r.y+dy},existing=state.rooms.find(x=>x.x===cell.x&&x.y===cell.y),b=actionButton(label+ (existing?' 보기':' 확장'),()=>existing?selectRoom(roomKey(cell)):addRoom(cell));b.disabled=!existing&&!canAdd(state.rooms,cell);controls.append(b);}body.append(controls,element('p','panel-note','가운데에서 좌우 2칸 · 위아래 3층, 최대 35개 방'));return;}
 if(tab==='pet'){const row=element('div','actions');row.append(actionButton('공 던지기',throwBall,'◉'),actionButton('쓰다듬기',petDog,'♡'),actionButton(follow?'따라오기 멈춤':'따라오기',()=>{follow=!follow;renderPanel();toast(follow?'이제 두부가 따라와요.':'두부가 여기서 쉬어요.');},'↝'));body.append(row,element('p','panel-note','바닥을 누르면 캐릭터가 이동해요. 두부를 눌러도 이 메뉴가 열려요.'));}
 if(tab==='room'){const row=element('div','actions');row.append(actionButton('포근한 거실',()=>{current().decor=true;save();renderWorld();toast('라벤더 거실을 적용했어요.');},'▧'),actionButton('빈방으로',()=>{current().decor=false;save();renderWorld();toast('테스트 방을 비웠어요.');},'□'),actionButton('집 확장',()=>toggleExpansion(true),'＋'));body.append(row,element('p','panel-note','이번 테스트에서는 방 분위기를 바꿀 수 있어요. 가구 개별 배치는 다음 단계예요.'));}
 if(tab==='closet'){const box=element('div','closet-preview'),im=element('img');im.src='assets/avatar.webp';im.alt='크림 가디건과 연두 바지를 입은 기본 아바타';box.append(im,element('p','','이번 테스트의 기본 아바타예요.\n얼굴·머리·의상 선택은 다음 단계에서 하나씩 만들어요.'));body.append(box);}
 if(tab==='diary'){const label=element('label','','오늘은 어떤 하루였나요?'),field=element('textarea');field.id='diary';field.maxLength=4000;field.value=state.diary;label.htmlFor='diary';field.oninput=()=>{state.diary=field.value;save();};body.append(label,field,actionButton('기록 저장',()=>{state.diary=field.value;persist();toast(saveFailed?'저장할 수 없어요. 내용을 복사해 주세요.':'이 기기에 기록을 저장했어요.');}),element('p','panel-note','테스트 기록은 이 기기에 저장돼요.'));}}
function setTab(next){if(!['room','closet','pet','diary'].includes(next))return;tab=next;if(expanding){expanding=false;$('#expand').setAttribute('aria-pressed','false');renderWorld();focusRoom();}document.querySelectorAll('[data-tab]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.tab===tab)));renderPanel();}
function toggleExpansion(next=!expanding){expanding=next;$('#expand').setAttribute('aria-pressed',String(next));$('#hint').textContent=next?'연결된 방 옆의 ＋로 확장하세요':'바닥을 눌러 걸어보세요';renderWorld();renderPanel();focusRoom(next);}
function throwBall(){const node=world.querySelector(`[data-room="${selected}"] .ball`),destination=dogX>600?170:1000,back=dogX;if(!node)return;node.style.left=destination+'px';move('dog',destination,()=>{node.hidden=true;later(()=>move('dog',back,()=>{toast('두부가 공을 가져왔어요!');}),200);});node.hidden=false;toast('두부야, 공 가져와!');}
function petDog(){stopMotion();const dog=world.querySelector(`[data-room="${selected}"] .dog`),heart=element('span','heart','♡');heart.style.left=(dogX+50)+'px';dog?.parentElement.append(heart);dog?.classList.add('loved');later(()=>{heart.remove();dog?.classList.remove('loved');},1800);toast('두부가 기분 좋게 꼬리를 흔들어요.');}
const pointers=new Map();let gesture=null;
function point(e){const b=view.getBoundingClientRect();return {x:e.clientX-b.left,y:e.clientY-b.top};}
view.addEventListener('pointerdown',e=>{if(e.target.closest('button,select')||e.button>0)return;const p=point(e);pointers.set(e.pointerId,p);view.setPointerCapture(e.pointerId);if(pointers.size===1)gesture={start:p,last:p,moved:false,multi:false};else if(pointers.size===2){const [a,b]=[...pointers.values()];gesture={multi:true,moved:true,distance:Math.hypot(a.x-b.x,a.y-b.y),center:{x:(a.x+b.x)/2,y:(a.y+b.y)/2}};}});
view.addEventListener('pointermove',e=>{if(!pointers.has(e.pointerId)||!gesture)return;const p=point(e);pointers.set(e.pointerId,p);if(pointers.size>=2){const [a,b]=[...pointers.values()],center={x:(a.x+b.x)/2,y:(a.y+b.y)/2},distance=Math.hypot(a.x-b.x,a.y-b.y);if(gesture.distance>0){zoom(distance/gesture.distance,gesture.center);pan.x+=center.x-gesture.center.x;pan.y+=center.y-gesture.center.y;applyCamera();}gesture.distance=distance;gesture.center=center;gesture.multi=true;}else if(!gesture.multi){if(Math.hypot(p.x-gesture.start.x,p.y-gesture.start.y)>7)gesture.moved=true;if(gesture.moved){pan.x+=p.x-gesture.last.x;pan.y+=p.y-gesture.last.y;applyCamera();}gesture.last=p;}});
function end(e,canceled=false){if(!pointers.has(e.pointerId))return;const p=point(e),tap=!canceled&&gesture&&!gesture.moved&&!gesture.multi;pointers.delete(e.pointerId);if(view.hasPointerCapture(e.pointerId))view.releasePointerCapture(e.pointerId);if(tap){const wx=(p.x-pan.x)/scale,wy=(p.y-pan.y)/scale,r=state.rooms.find(r=>{const b=bounds(r);return wx>=b.x&&wx<=b.x+1200&&wy>=b.y&&wy<=b.y+400;});if(r){if(roomKey(r)!==selected)selectRoom(roomKey(r));else if(!expanding){const b=bounds(r);move('actor',Math.max(35,Math.min(1040,wx-b.x-55)));}}}if(!pointers.size)gesture=null;}
view.addEventListener('pointerup',e=>end(e));view.addEventListener('pointercancel',e=>end(e,true));view.addEventListener('wheel',e=>{e.preventDefault();zoom(Math.exp(-e.deltaY*.001),point(e));},{passive:false});view.addEventListener('keydown',e=>{if(e.key==='+'||e.key==='='){e.preventDefault();zoom(1.2);}else if(e.key==='-'){e.preventDefault();zoom(1/1.2);}else if(['ArrowLeft','ArrowRight','ArrowUp','ArrowDown'].includes(e.key)){e.preventDefault();pan.x+=e.key==='ArrowLeft'?65:e.key==='ArrowRight'?-65:0;pan.y+=e.key==='ArrowUp'?65:e.key==='ArrowDown'?-65:0;applyCamera();}});
$('#zoom-in').onclick=()=>zoom(1.25);$('#zoom-out').onclick=()=>zoom(.8);$('#overview').onclick=()=>focusRoom(true);$('#home-view').onclick=()=>focusRoom();$('#expand').onclick=()=>toggleExpansion();$('#exit').onclick=()=>{if(initialized)persist();port?.postMessage({type:'close'});};document.addEventListener('keydown',e=>{if(e.key==='Escape')$('#exit').click();});document.querySelectorAll('[data-tab]').forEach(b=>{b.querySelector('span').innerHTML=icon(b.dataset.tab);b.onclick=()=>setTab(b.dataset.tab);});
new ResizeObserver(()=>{if(initialized)focusRoom(expanding);}).observe(view);
window.addEventListener('message',e=>{if(initialized||window.parent===window||e.source!==window.parent||e.origin!==location.origin||e.data?.type!=='ojjuda-house-test-init'||!e.ports[0]||typeof e.data.owner!=='string'||e.data.owner.length>180)return;port=e.ports[0];key='ojjuda-house-playtest-v1:'+encodeURIComponent(e.data.owner);let stored;try{stored=JSON.parse(localStorage.getItem(key));}catch{}state=normalize(stored);initialized=true;$('#locked').hidden=true;$('#app').hidden=false;renderWorld();renderPanel();focusRoom();port.onmessage=event=>{if(event.data?.type==='dispose'){persist();stopMotion();initialized=false;$('#app').hidden=true;$('#locked').hidden=false;port.close();}};port.postMessage({type:'ready'});});
document.addEventListener('visibilitychange',()=>{if(document.hidden){stopMotion();if(initialized)persist();}});window.addEventListener('pagehide',()=>{if(initialized)persist();stopMotion();});
