/* No public/signed image URLs. Every file is downloaded with the reader's session. */
(()=>{
'use strict';
const $=id=>document.getElementById(id),el=(tag,text,cls)=>{const n=document.createElement(tag);if(text)n.textContent=text;if(cls)n.className=cls;return n;};
const button=(text,fn)=>{const b=el('button',text);b.type='button';b.onclick=fn;return b;};
const config=window.OJJUDA_CONFIG;let client,user,admin=false,generation=0,reading=0,uploading=false,chosen=[],pageRows=[],index=0,zoom=1,comic=null,observer=null,timer;
const urls=new Map(),pending=new Map(),vp=$('viewport');
function notice(text){$('toast').textContent=text;clearTimeout(timer);timer=setTimeout(()=>$('toast').textContent='',5000)}
function numbers(name){return(name.normalize('NFKC').replace(/\.[^.]+$/,'').match(/\d+/g)||[]).map(BigInt)}
function compare(a,b){const x=numbers(a.name),y=numbers(b.name);if(x.length&&y.length){for(let i=0;i<Math.min(x.length,y.length);i++)if(x[i]!==y[i])return x[i]<y[i]?-1:1;if(x.length!==y.length)return x.length-y.length}else if(x.length||y.length)return x.length?-1:1;return a.name.localeCompare(b.name,'ko',{numeric:true})}
async function result(query){const {data,error}=await query;if(error)throw error;return data}
function remember(){if(comic&&user)try{localStorage.setItem('ojjuda-comic:'+user.id+':'+comic.id,String(index))}catch{}}
function clean(){reading++;observer?.disconnect();observer=null;urls.forEach(URL.revokeObjectURL);urls.clear();pending.clear();$('pages').replaceChildren();$('reader').hidden=true;document.body.style.overflow='';comic=null;pageRows=[]}
function gate(message,login=false){clean();admin=false;$('uploadOpen').hidden=true;$('shelf').hidden=$('editor').hidden=true;$('gate').hidden=false;$('gateMessage').textContent=message;$('login').hidden=!login;$('retry').hidden=login}
async function boot(){const token=++generation;gate('이용 가능 여부를 확인하고 있어요.');$('retry').hidden=true;
 try{const auth=await client.auth.getUser();if(token!==generation)return;user=auth.data?.user;if(auth.error||!user||user.is_anonymous){gate('로그인한 만 19세 이상 회원만 이용할 수 있어요.',true);return}
 const access=await result(client.rpc('comics_access'));if(token!==generation)return;
 if(!access?.allowed){gate('만 19세 이상 회원만 볼 수 있어요.\n생년월일이 등록되지 않았거나 이용이 제한된 계정은 입장할 수 없어요.');return}
 admin=access.admin===true;$('gate').hidden=true;$('uploadOpen').hidden=!admin;await shelf();
 const requested=new URLSearchParams(location.search).get('comic');if(requested&&token===generation)await openComic(requested);
 }catch{if(token===generation)gate('이용 가능 여부를 확인하지 못했어요. 다시 확인해 주세요.')}
}
async function shelf(){const token=generation;clean();$('editor').hidden=true;$('shelf').hidden=false;$('books').replaceChildren(el('p','만화를 불러오는 중이에요.','empty'));
 try{const books=await result(client.from('creative_comics').select('id,title,description,published,created_at').order('created_at',{ascending:false}));if(token!==generation)return;$('books').replaceChildren();
 if(!books.length)$('books').append(el('p',admin?'아직 등록한 만화가 없어요. 위의 ‘만화 올리기’로 시작하세요.':'아직 공개된 창작만화가 없어요.','empty'));
 for(const book of books){const card=el('article','','book');card.append(el('div','▤','book-mark'),el('h2',book.title),el('p',book.description||'한 장씩 넘겨 보세요.'));if(!book.published)card.append(el('small','비공개 · 관리자만 볼 수 있어요'));const actions=el('div','','actions');actions.append(button('읽기',()=>openComic(book.id)));if(book.published)actions.append(button('링크 복사',async()=>{try{await navigator.clipboard.writeText(location.origin+'/comics/?comic='+book.id);notice('만 19세 이상 회원에게 공유할 링크를 복사했어요.')}catch{notice('주소창의 링크를 복사해 주세요.');history.replaceState(null,'','?comic='+book.id)}}));
 if(admin){actions.append(button(book.published?'비공개로 전환':'공개하기',async()=>{if(!confirm(book.published?'이 만화를 비공개로 바꿀까요?':'만 19세 이상 회원에게 공개할까요?'))return;try{await result(client.from('creative_comics').update({published:!book.published}).eq('id',book.id).select('id').single());await shelf()}catch{notice('변경하지 못했어요. 이미지 업로드가 모두 완료되었는지 확인해 주세요.')}}));actions.append(button('삭제',async()=>{if(!confirm('이 만화와 이미지를 삭제할까요?'))return;try{await removeBook(book.id);await shelf()}catch{notice('삭제를 마치지 못했어요. 비공개 상태에서 다시 시도해 주세요.')}}))}card.append(actions);$('books').append(card)}
 }catch{if(token===generation)$('books').replaceChildren(el('p','목록을 불러오지 못했어요. 새로고침을 눌러 주세요.','empty'))}
}
async function removeBook(id){await result(client.from('creative_comics').update({published:false}).eq('id',id).select('id').single());const rows=await result(client.from('creative_comic_pages').select('path').eq('comic_id',id));for(let i=0;i<rows.length;i+=50)await result(client.storage.from('creative-comics').remove(rows.slice(i,i+50).map(p=>p.path)));await result(client.from('creative_comics').delete().eq('id',id).select('id').single())}
function showFiles(){const list=$('fileList');list.replaceChildren();$('fileCount').textContent=chosen.length+'장 선택';chosen.forEach((f,i)=>{const li=el('li'),row=el('div'),name=el('span',f.name);name.title=f.name;row.append(name);for(const [label,delta] of [['↑',-1],['↓',1]]){const b=button(label,()=>{[chosen[i],chosen[i+delta]]=[chosen[i+delta],chosen[i]];showFiles()});b.disabled=i+delta<0||i+delta>=chosen.length;b.setAttribute('aria-label',f.name+(delta<0?' 앞으로':' 뒤로'));row.append(b)}li.append(row);list.append(li)})}
async function imageInfo(file){const bytes=new Uint8Array(await file.slice(0,12).arrayBuffer());let mime,ext;if([137,80,78,71,13,10,26,10].every((v,i)=>bytes[i]===v)){mime='image/png';ext='png'}else if(bytes[0]===255&&bytes[1]===216&&bytes[2]===255){mime='image/jpeg';ext='jpg'}else if(String.fromCharCode(...bytes.slice(0,4))==='RIFF'&&String.fromCharCode(...bytes.slice(8,12))==='WEBP'){mime='image/webp';ext='webp'}else throw Error('이미지 형식을 확인해 주세요: '+file.name);const url=URL.createObjectURL(file);try{const img=new Image();img.src=url;await img.decode();if(!img.naturalWidth||!img.naturalHeight||img.naturalWidth>40000||img.naturalHeight>40000)throw Error('이미지 크기를 확인해 주세요.');return {mime,ext,width:img.naturalWidth,height:img.naturalHeight}}finally{URL.revokeObjectURL(url)}}
$('uploadOpen').onclick=()=>{if(!admin)return;clean();$('shelf').hidden=true;$('editor').hidden=false};$('cancelUpload').onclick=()=>{if(!uploading)shelf()};$('fileInput').onchange=e=>{chosen=[...e.target.files].sort(compare);showFiles()};$('sort').onclick=()=>{chosen.sort(compare);showFiles()};
$('uploadForm').onsubmit=async e=>{e.preventDefault();if(uploading||!admin)return;if(!chosen.length||chosen.length>500){notice('이미지를 1~500장 선택해 주세요.');return}if(chosen.some(f=>f.size>20971520)){notice('한 장의 용량은 20MB 이하여야 해요.');return}const title=$('title').value.trim();if(!title){notice('제목을 입력해 주세요.');return}const token=generation,owner=user.id,files=[...chosen];uploading=true;document.querySelectorAll('#editor input,#editor textarea,#editor button').forEach(n=>n.disabled=true);$('uploadOpen').disabled=true;$('uploadProgress').hidden=false;let id=null;
 try{const items=[];for(let i=0;i<files.length;i++){if(token!==generation)throw Error('로그인이 바뀌었어요.');$('uploadStatus').textContent=`이미지 확인 중 ${i+1} / ${files.length}`;items.push(await imageInfo(files[i]))}
 id=crypto.randomUUID();await result(client.from('creative_comics').insert({id,title,description:$('description').value.trim()}));
 for(let i=0;i<files.length;i++){if(token!==generation)throw Error('로그인이 바뀌었어요.');const info=items[i],path=owner+'/'+id+'/'+crypto.randomUUID()+'.'+info.ext;$('uploadStatus').textContent=`업로드 중 ${i+1} / ${files.length} · ${files[i].name}`;await result(client.from('creative_comic_pages').insert({comic_id:id,position:i+1,filename:files[i].name,path,width:info.width,height:info.height}));await result(client.storage.from('creative-comics').upload(path,files[i],{contentType:info.mime,cacheControl:'0',upsert:false}));$('uploadProgress').value=Math.round((i+1)/files.length*100)}
 if(token!==generation)throw Error('로그인이 바뀌었어요.');await result(client.from('creative_comics').update({published:true}).eq('id',id).select('id').single());$('uploadForm').reset();chosen=[];showFiles();notice('만화를 공개했어요. 만 19세 이상 회원이 읽을 수 있어요.');await shelf();
 }catch(error){let cleanup=true;if(id&&token===generation)try{await removeBook(id)}catch{cleanup=false}if(token===generation)$('uploadStatus').textContent='업로드를 완료하지 못했어요. '+(cleanup?'파일과 연결 상태를 확인한 뒤 다시 시도해 주세요.':'목록에 비공개로 남겨 두었어요. 삭제 후 다시 올려 주세요.');}
 finally{uploading=false;document.querySelectorAll('#editor input,#editor textarea,#editor button').forEach(n=>n.disabled=false);$('uploadOpen').disabled=false;showFiles()}
};
function nav(){const step=$('viewMode').value==='spread'?2:1;$('page').value=index+1;$('page').max=pageRows.length;$('total').textContent='/ '+pageRows.length;$('prev').disabled=index===0;$('next').disabled=index+step>=pageRows.length;remember()}
function resize(){if(!pageRows.length)return;const mode=$('viewMode').value,width=Math.max(80,vp.clientWidth-32),height=Math.max(80,vp.clientHeight-32);let scale=1;if(mode!=='scroll'){const rows=pageRows.slice(index,index+(mode==='spread'?2:1));scale=Math.min(height,...rows.map(p=>height));const ratios=rows.reduce((a,p)=>a+p.width/p.height,0);scale=Math.min(height,(width-8*(rows.length-1))/ratios)}document.querySelectorAll('.sheet').forEach(n=>{const p=pageRows[+n.dataset.index];n.style.width=(mode==='scroll'?Math.min(900,width):scale*p.width/p.height)*zoom+'px';n.style.aspectRatio=p.width+'/'+p.height});$('zoomValue').textContent=Math.round(zoom*100)+'%'}
async function loadImage(n){const i=+n.dataset.index,p=pageRows[i],token=reading;if(!p||n.dataset.loading==='yes'||n.querySelector('img').src)return;n.dataset.loading='yes';const status=n.querySelector('.loading');status.textContent='불러오는 중…';try{let url=urls.get(p.id);if(!url){let task=pending.get(p.id);if(!task){task=result(client.storage.from('creative-comics').download(p.path));pending.set(p.id,task)}let blob;try{blob=await task}finally{if(pending.get(p.id)===task)pending.delete(p.id)}if(token!==reading||!n.isConnected)return;url=URL.createObjectURL(blob);urls.set(p.id,url)}if(token!==reading||!n.isConnected)return;n.querySelector('img').src=url;status.textContent='';
 // Bound decoded files while scrolling; offscreen pages reload with authorization.
 for(const [id,oldUrl] of urls){if(urls.size<=10)break;const old=document.querySelector('.sheet[data-id="'+id+'"]');if(old&&Math.abs(old.getBoundingClientRect().top-vp.getBoundingClientRect().top)<vp.clientHeight*2)continue;if(old)old.querySelector('img').removeAttribute('src');URL.revokeObjectURL(oldUrl);urls.delete(id)}
 }catch{if(token===reading&&n.isConnected)status.replaceChildren(button('다시 불러오기',()=>loadImage(n)))}finally{n.dataset.loading='no'}}
function renderReader(){observer?.disconnect();$('pages').replaceChildren();const mode=$('viewMode').value;$('pages').className=mode==='scroll'?'scroll':'';const indexes=mode==='scroll'?pageRows.map((_,i)=>i):Array.from({length:Math.min(mode==='spread'?2:1,pageRows.length-index)},(_,i)=>index+i);for(const i of indexes){const p=pageRows[i],n=el('figure','','sheet');n.dataset.index=i;n.dataset.id=p.id;const img=el('img');img.alt=p.filename;img.draggable=false;img.onerror=()=>{img.removeAttribute('src');const old=urls.get(p.id);if(old)URL.revokeObjectURL(old);urls.delete(p.id);n.querySelector('.loading').replaceChildren(button('다시 불러오기',()=>loadImage(n)))};n.append(img,el('div','','loading'));$('pages').append(n)}resize();nav();vp.scrollTo(0,0);if(mode==='scroll'){observer=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting)loadImage(e.target)}),{root:vp,rootMargin:'200px'});document.querySelectorAll('.sheet').forEach(n=>observer.observe(n));document.querySelector('.sheet[data-index="'+index+'"]')?.scrollIntoView({block:'start'})}else document.querySelectorAll('.sheet').forEach(loadImage)}
async function openComic(id){clean();const token=reading;try{const access=await result(client.rpc('comics_access'));if(!access?.allowed){gate('만 19세 이상 회원만 볼 수 있어요.');return}const book=await result(client.from('creative_comics').select('id,title').eq('id',id).single());const rows=await result(client.from('creative_comic_pages').select('id,position,filename,path,width,height').eq('comic_id',id).order('position'));if(token!==reading)return;if(!rows.length){notice('아직 만화 이미지가 없어요.');return}comic=book;pageRows=rows;index=0;try{index=Math.max(0,Math.min(rows.length-1,Number(localStorage.getItem('ojjuda-comic:'+user.id+':'+id))||0))}catch{}zoom=1;$('readerTitle').textContent=book.title;$('reader').hidden=false;document.body.style.overflow='hidden';history.replaceState(null,'','?comic='+id);renderReader();$('readerBack').focus()}catch{if(token===reading)notice('이 만화는 볼 수 없거나 불러오지 못했어요.')}}
function go(n){if(!pageRows.length)return;index=Math.max(0,Math.min(pageRows.length-1,Math.floor(n)||0));if($('viewMode').value==='scroll'){document.querySelector('.sheet[data-index="'+index+'"]')?.scrollIntoView({block:'start'});nav()}else{zoom=1;renderReader()}}
function step(n){go(index+n*($('viewMode').value==='spread'?2:1))}
function setZoom(z,x=vp.clientWidth/2,y=vp.clientHeight/2){const old=zoom,px=vp.scrollLeft+x,py=vp.scrollTop+y;zoom=Math.max(.5,Math.min(4,z));resize();vp.scrollLeft=px*zoom/old-x;vp.scrollTop=py*zoom/old-y}
$('readerBack').onclick=()=>{history.replaceState(null,'',location.pathname);clean();shelf()};$('prev').onclick=()=>step(-1);$('next').onclick=()=>step(1);$('page').onchange=e=>go(Number(e.target.value)-1);$('viewMode').onchange=()=>{zoom=1;renderReader()};$('zoomIn').onclick=()=>setZoom(zoom+.25);$('zoomOut').onclick=()=>setZoom(zoom-.25);$('fit').onclick=()=>setZoom(1);$('refresh').onclick=shelf;$('retry').onclick=boot;
vp.ondblclick=e=>{const r=vp.getBoundingClientRect();setZoom(zoom>1?1:2,e.clientX-r.left,e.clientY-r.top)};const points=new Map();let gesture=null,pinch=0,startZoom=1;vp.onpointerdown=e=>{if(e.target.closest('button'))return;vp.setPointerCapture(e.pointerId);points.set(e.pointerId,{x:e.clientX,y:e.clientY});if(points.size===1)gesture={x:e.clientX,y:e.clientY,lx:e.clientX,ly:e.clientY,pinched:false};if(points.size===2){const[a,b]=[...points.values()];pinch=Math.hypot(a.x-b.x,a.y-b.y);startZoom=zoom;gesture.pinched=true}};vp.onpointermove=e=>{if(!points.has(e.pointerId))return;points.set(e.pointerId,{x:e.clientX,y:e.clientY});if(points.size===2){const[a,b]=[...points.values()],r=vp.getBoundingClientRect();setZoom(startZoom*Math.hypot(a.x-b.x,a.y-b.y)/Math.max(1,pinch),(a.x+b.x)/2-r.left,(a.y+b.y)/2-r.top)}else if(gesture){if(zoom>1||$('viewMode').value==='scroll'){vp.scrollLeft-=e.clientX-gesture.lx;vp.scrollTop-=e.clientY-gesture.ly}gesture.lx=e.clientX;gesture.ly=e.clientY}};function end(e){if(gesture&&points.size===1&&!gesture.pinched&&zoom<=1&&$('viewMode').value!=='scroll'&&e.type!=='pointercancel'){const dx=e.clientX-gesture.x,dy=e.clientY-gesture.y;if(Math.abs(dx)>60&&Math.abs(dx)>Math.abs(dy)*1.5)step(dx<0?1:-1)}points.delete(e.pointerId);if(!points.size)gesture=null}vp.onpointerup=vp.onpointercancel=end;
vp.addEventListener('scroll',()=>{if($('viewMode').value!=='scroll'||!pageRows.length)return;const top=vp.getBoundingClientRect().top+120;let next=0;document.querySelectorAll('.sheet').forEach(n=>{if(n.getBoundingClientRect().top<=top)next=+n.dataset.index});if(next!==index){index=next;nav()}});document.addEventListener('keydown',e=>{if($('reader').hidden||/INPUT|SELECT|TEXTAREA/.test(e.target.tagName))return;if(e.key==='ArrowLeft'){e.preventDefault();step(-1)}if(e.key==='ArrowRight'){e.preventDefault();step(1)}if(e.key==='Escape')$('readerBack').click()});new ResizeObserver(resize).observe(vp);window.addEventListener('beforeunload',e=>{if(uploading){e.preventDefault();e.returnValue=''}});
if(!config||!window.supabase){gate('연결을 준비하지 못했어요. 새로고침해 주세요.');$('retry').onclick=()=>location.reload();return}
client=window.supabase.createClient(config.supabaseUrl,config.supabaseKey);client.auth.onAuthStateChange((event,session)=>{if(event==='SIGNED_OUT'||(user&&session?.user?.id!==user.id)){generation++;clean();gate('로그인을 다시 확인하고 있어요.');setTimeout(boot,0)}});boot();
})();
